apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: safetwitch
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.3.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            env:
              URL: &mainHost safetwitch-backend.${ROOT_DOMAIN}
            image:
              repository: codeberg.org/safetwitch/safetwitch-backend
              tag: v1.5.4@sha256:dfa6e182bc5f32d32a7678b54598ebfed35623f496340580630d6a712186c499
      frontend:
        containers:
          main:
            env:
              SAFETWITCH_BACKEND_DOMAIN: *mainHost
              SAFETWITCH_INSTANCE_DOMAIN: &host '{{ .Release.Name }}.${ROOT_DOMAIN}'
              SAFETWITCH_DEFAULT_LOCALE: en
              SAFETWITCH_FALLBACK_LOCALE: en
            image:
              repository: codeberg.org/safetwitch/safetwitch
              tag: v2.4.3@sha256:3a7162f143159a12fdfbcb50db8e250ff2c479ab4e8fb391955af1c713321bb4
    ingress:
      frontend:
        className: nginx
        enabled: true
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: frontend
                  port: http
        tls:
          - hosts:
              - *host
      main:
        className: nginx
        enabled: true
        hosts:
          - host: *mainHost
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *mainHost
    service:
      main:
        ports:
          http:
            port: 8080
      frontend:
        controller: frontend
        ports:
          http:
            port: 80
