apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redlib
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      redlib:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            dependsOn: gluetun
            env:
              REDLIB_DEFAULT_THEME: dark
              REDLIB_DEFAULT_SUBSCRIPTIONS: "ergomechkeyboards+linux+patientgamers+privacy+Piracy+selfhosted+sffpc+olkb+unixporn"
            image:
              repository: quay.io/redlib/redlib
              tag: latest
          # Configure the gluetun sidecar
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.39.1@sha256:6a8058e626763cbf735ac2f78c774dbb24fec2490bd9d9f7d67e22592cb4a991
            env:
              SERVER_COUNTRIES: Germany
              VPN_INTERFACE: wg0
              VPN_SERVICE_PROVIDER: protonvpn
              VPN_TYPE: wireguard
            envFrom:
              - secretRef:
                  name: redlib-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${ROOT_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
