apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redlib
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      redlib:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            dependsOn: gluetun
            env:
              REDLIB_DEFAULT_THEME: dark
              REDLIB_DEFAULT_SUBSCRIPTIONS: "ergomechkeyboards+linux+patientgamers+privacy+Piracy+selfhosted+sffpc+olkb+unixporn"
            image:
              repository: quay.io/redlib/redlib
              tag: latest
          resources:
            requests:
              cpu: 10m
              memory: 53M
            limits:
              cpu: 13m
              memory: 177M
          # Configure the gluetun sidecar
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41.0@sha256:6b54856716d0de56e5bb00a77029b0adea57284cf5a466f23aad5979257d3045
            env:
              FIREWALL_DEBUG: "on"
              FIREWALL_INPUT_PORTS: "8080"
              SERVER_COUNTRIES: Thailand,Indonesia,Vietnam
              VPN_INTERFACE: wg0
              VPN_SERVICE_PROVIDER: protonvpn
              VPN_TYPE: wireguard
            envFrom:
              - secretRef:
                  name: redlib-secret
            resources:
              requests:
                cpu: 10m
                memory: 381M
              limits:
                cpu: 13m
                memory: 716M
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${ROOT_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
