apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.6.0
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      metube:
        containers:
          app:
            env:
              AUDIO_DOWNLOAD_DIR: /audio
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/alexta69/metube
              tag: latest@sha256:1f5999767f04d1768acb1c050ea1c22dbf56f98ed2b3ed911560419511abb03e
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsUser: 568
        supplementalGroups:
          - 100
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: metube.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - metube.${ROOT_DOMAIN}
    persistence:
      audio:
        enabled: true
        path: ${NFS_PATH}/navidrome/media/ytdl
        server: ${NFS_HOST}
        type: nfs
      downloads:
        enabled: true
        path: /mnt/raid/media/metube
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: metube
        ports:
          http:
            port: 8081
