# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pgbackweb
    namespace: utilities
type: Opaque
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:vkUMVikLG3Un,iv:pUqYoB6DHINO2O6uWe/e83LPpfhioiUCjdELyXqu9bM=,tag:auisu3832Zzk9KnzVYh5bw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:RpUpzXBXKW+DKRi+xXZ2tESZOnMIa/Bd6fCm+dpcMPpdiu4jHEVPdBg=,iv:p7Tcg/JTh6pzjBiGWVF2cSeaWe215cUTULV3GRgA1yA=,tag:SsLL41n6xkiBbI2Ypo5e5A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:oyPq2N7/xvRhrhZB0W5Rca+5ReY=,iv:wP0jXZb6xppuNPX0lya8L6cpkm+4pfxNllG06K8ZFPM=,tag:3XdB65JbUuY8mRLcbXCVBg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:xepGe3fEnmN2,iv:R7E7tUsiODBRuYREylimSgjWHl1ze09EQN2QcdukHtU=,tag:18jE7kOmC2VRcZCBs8dhyQ==,type:str]
    PBW_ENCRYPTION_KEY: ENC[AES256_GCM,data:o29gUDLjHy3K7hTFzmXp7SrNhFSd3KbBfpM3cj9J538=,iv:/iktc2eYkeHSkvLlb/xcRUmRKIv0ww4hC/b6+KRpWxg=,tag:pBtemtrcv1/jSCRg70OcCQ==,type:str]
    PBW_POSTGRES_CONN_STRING: ENC[AES256_GCM,data:O0ZW4KAw/Ukrrh1Gne9D/tPCTmM+To0SK6I/hq9zuM+x8SX1HJ1Xp1oRR0YaFY97kTPLahcVRxZHRH3cCk63mCLCdN3izOIC8iOiY+qbsIsiFvcnozqbLGyirVK1L0vJMCtukzoNe2f/uteEiy9BFeIl8rA=,iv:YihCass2BgMAvzKwRqrarspIu76SYH90Eh02F951OdQ=,tag:Dpnpfle0Ld9x2m5A36yZXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T00:13:02Z"
    mac: ENC[AES256_GCM,data:OoCS8hDOrvZwBv4Z4Tud/2eEVYYvJlLjB7jzUCA9pyJ8zmdOMjqs+fH8fekPUxbhPr1xMzxgUXkHj3ToCBCf9YLm3T2PzctBS+LzddmAr30NA73Ak47h58fGqu9Ptj9fhSbzTdNDxguRKTJsoZVSXQ/j4ppgXe8KfG2CbbwtXFs=,iv:MwIIAAzc0KCwKbj2jaYq6QtfFgNe4jTNzlkgO1pHucU=,tag:v6j6wwcwTE2DcIfQqymWPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
