# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pgbackweb
    namespace: utilities
type: Opaque
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:vkUMVikLG3Un,iv:pUqYoB6DHINO2O6uWe/e83LPpfhioiUCjdELyXqu9bM=,tag:auisu3832Zzk9KnzVYh5bw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:f6jJtyDlt+EkziVDds7U4rwsY4DupKGuHRMBOe467UXAnIcG,iv:nPPdD4opxna6Em5CHLQi136xZ5sr2jBcaivB7OjUbZk=,tag:WehX9I/VlRGOaFggiIJNIQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:oyPq2N7/xvRhrhZB0W5Rca+5ReY=,iv:wP0jXZb6xppuNPX0lya8L6cpkm+4pfxNllG06K8ZFPM=,tag:3XdB65JbUuY8mRLcbXCVBg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:xepGe3fEnmN2,iv:R7E7tUsiODBRuYREylimSgjWHl1ze09EQN2QcdukHtU=,tag:18jE7kOmC2VRcZCBs8dhyQ==,type:str]
    PBW_ENCRYPTION_KEY: ENC[AES256_GCM,data:o29gUDLjHy3K7hTFzmXp7SrNhFSd3KbBfpM3cj9J538=,iv:/iktc2eYkeHSkvLlb/xcRUmRKIv0ww4hC/b6+KRpWxg=,tag:pBtemtrcv1/jSCRg70OcCQ==,type:str]
    PBW_POSTGRES_CONN_STRING: ENC[AES256_GCM,data:DZ/x08gMWngg1PsLe0iy2/q3xksll5vnO2FxKMhnHoUtWXkujpjuOlWtzu6BH6n18RB3sPyMDJxAuA0oJGDGlFMw+uaYXCg3ud5WNHqWk+jxy29CJnJTsNyNlq+3U0r+WWJCq5zrq7XivBO9h/2Q,iv:mbi5JogPebfekvHxldU21oTjQLu/3VF2xnFTRZ9phhM=,tag:2zowQWpepW+MQBWJ2bg28w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T04:00:11Z"
    mac: ENC[AES256_GCM,data:2oO3afrXrdeId2zWK8ehBopVDbAFXZKUNXoSVYYw0eN7pPw/Sw5XEEDkjiOIT23ZO7945FYroH3cy/q49CKbZxLv3chXBX/dXiGRH44dGsKrwsHo5Nk+z2ZEGfLQcJHkKenDMgCt5iBeMaU+kh2qgiS6OCdoWDaY5FKUvlDx/Fg=,iv:H8iOKocKtzeqngQNVSmyL/wLCXSQKweUPKFFLkuzdb8=,tag:3qy1XHM2QDspsgPughWidg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
