# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: cluster-18
  annotations:
    # required for seamless bootstrap: https://github.com/cloudnative-pg/cloudnative-pg/issues/5778#issuecomment-2783417464
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
kind: Cluster
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 18
    name: postgresql-standard-trixie
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
  bootstrap:
    # initdb: {}
    recovery:
      source: origin

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store garage-store
        serverName: cluster-18-v3

  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: *store
          serverName: cluster-18-v2
