---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./cluster-vectorchord.yaml
  - ./cluster-18.yaml
  - ./objectstore.yaml
  - ./scheduledbackup-18.yaml
  - ./restore-test-cluster-18.yaml
  # - ./scheduledbackup-pgvecto.yaml
  # - ./scheduledbackup-vectorchord.yaml
