---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-store
spec:
  configuration:
    destinationPath: s3://postgres/
    endpointURL: http://garage-app.cloud.svc:3900
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: aws-access-key-id
      secretAccessKey:
        name: cloudnative-pg-secret
        key: aws-secret-access-key
      region:
        name: cloudnative-pg-secret
        key: region
    wal:
      compression: zstd
    data:
      compression: gzip
  retentionPolicy: "30d"
