# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql18
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  env:
    - name: TZ
      value: ${TIMEZONE}
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie@sha256:bbefe420af6ba639167cf6b5ea385a5a5816db47cfaa8c6b1fecc2c503b8df81
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "250"
      shared_buffers: 128MB
  resources:
    requests:
      memory: "512Mi"
    limits:
      hugepages-2Mi: "512Mi"
  monitoring:
    enablePodMonitor: true
  bootstrap:
    recovery:
      source: &src source
  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store garage-store
  externalClusters:
    - name: *src
      plugin:
        name: *plugin
        parameters:
          barmanObjectName: *store
          serverName: postgresql
