apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-18
spec:
  backupOwnerReference: self
  cluster:
    name: cluster-18
  schedule: "0 37 2 ? * *"
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
