# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:zQ4pdD8=,iv:v6+Z5s7MDja7JUkUm4ndb62E6792XgSh0F5Kb5wpauU=,tag:AB1TKNXxxSMqrnEre+3V5Q==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:L0DTDGohQF7KYh+PEgsDSW5wYqkqNKu1,iv:M+MwYn0vvmZH9uVffY1XU4a/jOJxhsAarUxhBG2jmwA=,tag:Y75wV9idC3YgOxTRNgUirA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ2lxU1JnaEtyK3BIeURG
            R2ZSUW9JcmtncGJxWDhFMXV2NEpDb0JnbmlBCnExSVlONlErMEJHSmNiZ2pFek1E
            NnN0cFdjSVY3eGFNU0NZb29IdjNNSVkKLS0tICtkc2FjcGFJemxaWENFTTdBRmQy
            VjlUUGo1MUJNUmVvODdhdnFXOGxpOGMKe3WS4XP0bMyPYyyrS/4yvX4LtiGNqWtQ
            ynBJCi6fGpf++r2ERuU/sZxgHRo9SbdCsuQm7kR+wRZDtZsOH80zfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NEFmVXAxRjM1NjJlMVBi
            N280UkErR1o1cHF5WCtDWTJUcGVHUWtRNGtnCkxpU05oOTNxUGxaVjV2dnFFUTJM
            YXl5L1RNbXpPODdmb3BwTm5Mc3IzR1kKLS0tIEVheDZEUE9MRWN0ZnFpVThwaFNO
            cEVxUjRFZjE4S1dtZVF6MEFDVkx0WWcKxoBGT0eztdPUB8DwPFnrQw4SdmRxSQsM
            Q5m7KS7/4RRQbYamzMledOQHbHolqe+R8R6eVP1EHCdK/zuSf5f0Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T13:06:00Z"
    mac: ENC[AES256_GCM,data:UoWCQe/LA7QzVK9+XYa9wW3ZOTusFj5gTTVYpNAoGQOgOOM9xaqAH5mvblpfHX1jgdSzczu9nxkGu9V/t+EzsKvTaxXvsryAV55f2uqgOOWZvskLOF6WBEod7LSQ0y8mXbCDND140sOY2EqI2K/HXlurxBRlF6B6u2LnchgD2O4=,iv:zqhyjb6g16TumOG2tLJgivzeIBcmiZzypvM3zkYsJOc=,tag:KHDix2yjywF7lTh6mMr3wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
