apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app memos
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      memos:
        containers:
          app:
            image:
              repository: ghcr.io/usememos/memos
              tag: 0.25.3@sha256:40db300a188ede0c2cf1fc0c49741a03077478d6891fd3ace05c16d702b536a6
    defaultPodOptions:
      enableServiceLinks: false
    persistence:
      memos:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
        - path: /var/opt/memos
    route:
      app:
        hostnames:
        - '{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}'
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        controller: memos
        ports:
          http:
            port: 5230
