apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app memos
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      memos:
        containers:
          app:
            image:
              repository: ghcr.io/usememos/memos
              tag: 0.30.0@sha256:71a5b4738d1bed96e92112004054f0888e92791b64eb78afd79077c96e6f9327
    defaultPodOptions:
      enableServiceLinks: false
    persistence:
      memos:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/opt/memos
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: selfhosted
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Selfhosted
          gethomepage.dev/icon: *app
        hostnames:
          - "{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        controller: memos
        ports:
          http:
            port: 5230
