apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app valkey
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1m
  values:
    controllers:
      valkey:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: valkey/valkey
              tag: 9-alpine@sha256:d1cc70645bbcef743615463a2fa4616e841407545e18f560aed0c49671a90147
    service:
      app:
        ports:
          tcp:
            port: 6379
