apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app valkey
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1m
  values:
    controllers:
      valkey:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: valkey/valkey
              tag: 9-alpine@sha256:a35428eba9043cc0b79dbe54100f0c92784f2de00ad09b01182bfb1c5c83d1bd
    service:
      app:
        ports:
          tcp:
            port: 6379
