apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app valkey
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1m
  values:
    controllers:
      valkey:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: valkey/valkey
              tag: 9-alpine@sha256:1be494495248d53e3558b198a1c704e6b559d5e99fe4c926e14a8ad24d76c6fa
    service:
      app:
        ports:
          tcp:
            port: 6379
