apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app piped
spec:
  interval: 15m
  chart:
    spec:
      chart: piped
      version: 8.0.26
      sourceRef:
        kind: HelmRepository
        name: teampiped
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    postgresql:
      enabled: false
    frontend:
      env:
        BACKEND_HOSTNAME: piped-api.${ROOT_DOMAIN}
      image:
        repository: 1337kavin/piped-frontend
        tag: latest@sha256:8cb104f54608315b3e254c9487a005eaec6cd437359ef90be3b30556cc953a47
    backend:
      config:
        PORT: 8080
        NUM_WORKERS: 2
        PROXY_PART: https://ytproxy.${ROOT_DOMAIN}
        database:
          connection_url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/piped
          driver_class: org.postgresql.Driver
          dialect: org.hibernate.dialect.PostgreSQLDialect
        image:
          repository: 1337kavin/piped
          tag: latest@sha256:9ad2ed9ff568c40bfa50ea4bf07957f7bc2ae0768ce1f494f9fa99598f8c368b
    ytproxy:
      image:
        repository: 1337kavin/piped-proxy
        tag: latest@sha256:eac7e54bd599051b7da708f72bdc962c30762e9d089acc0ef4ad02973696ac94
  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: database.password
      targetPath: backend.config.database.password
    - kind: Secret
      name: *app
      valuesKey: database.username
      targetPath: backend.config.database.username
