apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app piped
spec:
  interval: 15m
  chart:
    spec:
      chart: piped
      version: 8.0.26
      sourceRef:
        kind: HelmRepository
        name: teampiped
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    postgresql:
      enabled: false
    frontend:
      env:
        BACKEND_HOSTNAME: piped-api.${ROOT_DOMAIN}
      image:
        repository: 1337kavin/piped-frontend
        tag: latest@sha256:a545b5e0f6e7ea3b29520f988b92f0fb5979a711d4177bedf931d7ed9a05002a
    backend:
      config:
        PORT: 8080
        NUM_WORKERS: 2
        PROXY_PART: https://ytproxy.${ROOT_DOMAIN}
        database:
          connection_url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/piped
          driver_class: org.postgresql.Driver
          dialect: org.hibernate.dialect.PostgreSQLDialect
        image:
          repository: 1337kavin/piped
          tag: latest@sha256:b0462b15a951061878d13abf3e3706b60a33c1941cb28bb48f86227d0fbeb730
    ytproxy:
      image:
        repository: 1337kavin/piped-proxy
        tag: latest@sha256:b7545be55f85d0ace1be574fb6baa0f9505b6c0144a18c645d9ef87ec147bc9f
  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: database.password
      targetPath: backend.config.database.password
    - kind: Secret
      name: *app
      valuesKey: database.username
      targetPath: backend.config.database.username
