apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.6.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      flaresolverr:
        containers:
          app:
            env:
              PGID: '568'
              PUID: '568'
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.3.21@sha256:f104ee51e5124d83cf3be9b37480649355d223f7d8f9e453d0d5ef06c6e3b31b
    resources:
      limits:
        memory: 292Mi
      requests:
        cpu: 15m
        memory: 105Mi
    service:
      app:
        controller: flaresolverr
        ports:
          http:
            port: 8191
