apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      flaresolverr:
        containers:
          app:
            env:
              PGID: '568'
              PUID: '568'
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.3.19@sha256:0bdf9ed48f3c54c998bc160be46244ce3a88a7783b6cfd31eec9c1667786152f
    resources:
      limits:
        memory: 292Mi
      requests:
        cpu: 15m
        memory: 105Mi
    service:
      app:
        controller: flaresolverr
        ports:
          http:
            port: 8191
