apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: downloads
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      flaresolverr:
        containers:
          app:
            env:
              PGID: "568"
              PUID: "568"
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.3.24@sha256:72e5a8bc63899ebeeb6bc0aece2b05a8d725c8a518aa30c610a8d61bb50303e1
    resources:
      limits:
        memory: 292Mi
      requests:
        cpu: 15m
        memory: 105Mi
    service:
      app:
        controller: flaresolverr
        ports:
          http:
            port: 8191
