apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app theme-park
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      theme-park:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/theme-park
              tag: 1.22.1@sha256:8087a8c3a81e342014ce2528870bc97a50c86ccd8e316287cac2d200d44e19c1
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: "{{ .Release.Name }}.${ROOT_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "{{ .Release.Name }}.${ROOT_DOMAIN}"
    service:
      app:
        controller: theme-park
        ports:
          http:
            port: 8080
