apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pairdrop
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.6.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            env:
              TZ: ${TIMEZONE}
            image:
              repository: lscr.io/linuxserver/pairdrop
              tag: 1.10.7@sha256:58f9ff35fc0d2e889fd00caee431fc0d69032f5be49436c08fcd4e3167b8c24a
    ingress:
      main:
        className: nginx
        enabled: true
        hosts:
          - host: &host '{{ .Release.Name }}.${ROOT_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    service:
      main:
        ports:
          http:
            port: 3000
