apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pairdrop
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      pairdrop:
        containers:
          app:
            env:
              DEBUG_MODE: true
              TZ: ${TIMEZONE}
            image:
              repository: lscr.io/linuxserver/pairdrop
              tag: 1.10.10@sha256:b35c4269b692db852d8d0e27c043808ae0be191316eec57e041f425006d6140d
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host '{{ .Release.Name }}.${ROOT_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /root/.npm/_cacache
      logs:
        type: emptyDir
        globalMounts:
          - path: /root/.npm/_logs
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
