---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-companion
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: technitium-companion-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: technitium
    - extract:
        key: technitium-companion
