apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app invidious
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    fullnameOverride: *app
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      invidious:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          invidious:
            envFrom:
              - secretRef:
                  name: *app
            image:
              repository: quay.io/invidious/invidious
              tag: 2026.02.24-21d0d10@sha256:eae2227bd1609692930dab504c6abfb4f45212b44679b1a2516b75746ad4e97b
            env:
              TZ: "${TIMEZONE}"
              INVIDIOUS_PORT: "3000" # https://github.com/iv-org/invidious/issues/2970
              INVIDIOUS_QUALITY: dash
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/stats
                    port: &port 3000
                  initialDelaySeconds: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 200Mi
              limits:
                memory: 400Mi
      companion:
        strategy: RollingUpdate
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          companion:
            envFrom:
              - secretRef:
                  name: *app
            image:
              repository: quay.io/invidious/invidious-companion
              tag: master-6267af7@sha256:4320469a01fd3e7f554c8a7ad8d0fd388f325b27cc39a760c64edb36914f06ea
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
              limits:
                memory: 1Gi
    route:
      invidious:
        hostnames:
          - "{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
    service:
      invidious:
        controller: *app
        ports:
          http:
            port: *port
      companion:
        controller: companion
        ports:
          http:
            port: 8282
