apiVersion: v1
kind: Secret
metadata:
    name: invidious
    namespace: media
    labels:
        app: invidious
type: Opaque
stringData:
    SERVER_SECRET_KEY: ENC[AES256_GCM,data:9tnVoIg1uE3SN2PdqNmYwQ==,iv:CoNzdcc9hIVX4U00o8T4wsBWZgCxERNShNSk0Q4LcvA=,tag:3fAAgg+rpuC93wG68k+fTQ==,type:str]
    INVIDIOUS_CONFIG: ENC[AES256_GCM,data:CRuJAL9FOha5iPjwVnrodLVe0cP6Vb2UrO7bgp4DWbqrVfXU4bne+p+OO2lGtnQDSe3PNhmB3XbOK4l522IAkLK8CulEuxxEqasY3/RfVVGAwOAWg+VXR3XS0HJbQsaZg9sQKsIcGiVzU0V/xxgBehcceUrrkUOSs1OEO93FuculPcE0Cm8ec1LUsunMnj0ZEdok7O4nzugVQFDso+xGyy6hSLutmBg4/tbVq+cvvU0C0eUb9Vird/MdMvuyOswK5UkX03cSpWzOZ5EQY5O/puD+oDZGKWEcds2NZn49VTY/gcumc2GwkuH9+NzP5orBA+HfgojkcnOZ9dmqNKH73NF5IggpMfhwDI3poYyOt7vsgxtE4vzn+ZqSxsEo83i7IFUkRiNF0N+pek790s5c8ElzEN9QC1DQCftIm1FHbhHR6zZcDMGrtaMjqGEWHL5z5r08Zorlai5X02d+hm9L3AmpKJkWdZ3reuenrhS7wfh0TvrHmMYBIlXyv7r/sjQNao4VzIC3xvxsRw==,iv:XL8Ysp90/UrXMCnZHYpBUM0GPyu01kWOlknfvy3BZPQ=,tag:4d9+llY3e6gl+VmtoDlWPQ==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ1d1dVU5cTV4ZlBHN2s0
            VDMxdjdtaEhkRVRTcndnMmU2S0RXYXRQZmd3CjhVQUhFbTAzcVdmWkZjNkJRaTNS
            cnMrS1JUakYwK3l4ak1uS0dzOUdHVWsKLS0tIFF4UG02ZXhJL2FMb09XNDFiTGRZ
            YVEyV0RZZ1RnNTk2OStXZVphdDBsV0EKMHEURCNIY544u+p0FYQ7r1khrpujEXaq
            JfTazsYnF7nn5hrsiER3dhyhzovzpr2WyFSiKLn2gt7KrWx9bmAVgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d3BYekVDRGJNYmdWNnVG
            dEp2NjhyYUFIMlg4MGtCUlFKOFlab05aRG1FCnh0OUU2ZTBHUm5OZjB6MnN6Q1VS
            TU1CN0VtS1RJaENmM2dsVjdEZENtYUEKLS0tIGN6SXdZOEdSbWg2K3lBOTVzUk90
            VlQ2Q3BXbWtUdUU3Qklla0srbGpJTVUKRLd0rlnFMI5gOMVckFRhjQec0ZChwRmf
            nTF3NE5fFeLUwVIOAZ6W2nZh3PhhqZLiuG4+JDTpRAIijH54xWJO/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T12:58:50Z"
    mac: ENC[AES256_GCM,data:jy8VB77szgRHtzBHuwvFmiru1exJlQTVLT6t+JnLOPmcKW0aDoIPwv1xvVxDJxhYNXilJUxMsQvZWDlLTI6a0LIir4nE5s6sJmBOyfDLOr36+uN3lWv/M2QqW1oIhlJRn4ApCbVP6SJkruPj8PrZW7aRWTcRerRYo6nZWyJiwJE=,iv:xrNdhasODXKR7y5HDBt0WeC+zIqm1rL6V1DtqW5QWzA=,tag:TK/ScZyx4SccsOxGbOvgGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
