apiVersion: v1
kind: Secret
metadata:
    name: invidious
    namespace: media
    labels:
        app: invidious
type: Opaque
stringData:
    SERVER_SECRET_KEY: ENC[AES256_GCM,data:R3ThHkaUp3qHZCSjJ3bjIg==,iv:FT0w9zgVH2xcq+X6F+Svv7GpRqm3P8rPGT60T41N680=,tag:UxtRYbg/QRWdgb7WIQKA/A==,type:str]
    INVIDIOUS_CONFIG: ENC[AES256_GCM,data:hxeawBIJR2SdO0CHvxiFaAul9dl33Ny5wRouGfFCmS+1BVSh5n0BkZXdV6xWuWdxVy1qs3BAa/5iAOtrPE0Xju/E3vfNnW4XbpuvCDGueX5pwy8+FYJI0DrSyK4seIlSllwxk5f/9pJtH9szPgiGYo5Vsw1TZiWgpefwfF5IbyaHMIsIA3phlCFckJqec8v8EcnnTN6yWZIV04ZzrXxLyeaBO69sUgbhSl0CE5D8tUltcjXsMs8S8Sf+rv6tWaqvn4O0OR7+EkRidIT6xx2JD01QcwaFfbd9vO1XX3X3sglzPUW7VCo+FHZgMByQD78EcgHh3AsjWinz+1m07TxeLXPgUMk9mpMes0Hr6pVT2D33/GYsZMvxhLPOwMTY+eBmrzSqonBWXwQ5VQrJr0c6PHNRYCQmz8h0YB/aSmru5+CiVHsQ6F26XMHcNpzSK+A4uA51D2XX7T6UAR7VHx27kI6QtcMsivjvZ89OrcwcK4KXzMADVef0iU76QLVxF1E9ACWLz7LQZ0EF3g==,iv:8npkEd8ULyfglgmNLmDuHUxW3Nd0nQQSycdU/Q+w0G0=,tag:3DVmo7PEWLEXIDc32B+6TA==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ1d1dVU5cTV4ZlBHN2s0
            VDMxdjdtaEhkRVRTcndnMmU2S0RXYXRQZmd3CjhVQUhFbTAzcVdmWkZjNkJRaTNS
            cnMrS1JUakYwK3l4ak1uS0dzOUdHVWsKLS0tIFF4UG02ZXhJL2FMb09XNDFiTGRZ
            YVEyV0RZZ1RnNTk2OStXZVphdDBsV0EKMHEURCNIY544u+p0FYQ7r1khrpujEXaq
            JfTazsYnF7nn5hrsiER3dhyhzovzpr2WyFSiKLn2gt7KrWx9bmAVgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d3BYekVDRGJNYmdWNnVG
            dEp2NjhyYUFIMlg4MGtCUlFKOFlab05aRG1FCnh0OUU2ZTBHUm5OZjB6MnN6Q1VS
            TU1CN0VtS1RJaENmM2dsVjdEZENtYUEKLS0tIGN6SXdZOEdSbWg2K3lBOTVzUk90
            VlQ2Q3BXbWtUdUU3Qklla0srbGpJTVUKRLd0rlnFMI5gOMVckFRhjQec0ZChwRmf
            nTF3NE5fFeLUwVIOAZ6W2nZh3PhhqZLiuG4+JDTpRAIijH54xWJO/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T11:42:16Z"
    mac: ENC[AES256_GCM,data:uPECQMNFqKaUwKL7z2GrpSrRQzh/yXfp6WYImW3BrfzA4BSPQss8GR6ITf5yem2L8GWpjPRtmk5p6QWyqrWdBkuGSMCV2MzjlbO5KdKWla6HsYd/rJmN3b5Pyye+/Hc26dtwHXHxUd+t2lP6gYkVTCU03cUDvoyoU9lAqYdeGzk=,iv:tmbLqptqOm7TqvgjV7fubbm2ix5HYjCzcDUJqiTHV6o=,tag:PBYEoi+fLCo6HyEsi81HHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
