apiVersion: v1
kind: Secret
metadata:
    name: invidious
    namespace: media
    labels:
        app: invidious
type: Opaque
stringData:
    SERVER_SECRET_KEY: ENC[AES256_GCM,data:9tnVoIg1uE3SN2PdqNmYwQ==,iv:CoNzdcc9hIVX4U00o8T4wsBWZgCxERNShNSk0Q4LcvA=,tag:3fAAgg+rpuC93wG68k+fTQ==,type:str]
    INVIDIOUS_CONFIG: ENC[AES256_GCM,data:uAGlRvoqfDl0zac9eLZ07vR5ITcr4tG1+814sWQHaPRAfQDUjM3zQvjLxaNwELRem6qTG7oQcZiXJQBIebJaFBTMgNH3bROuaMyqX58TquTrUcGPAMoBC0VlloZs7/YGq8VbOGsPwQXzeCf3JugXFPI85ztELsj2p+IJO5sUIuhN8x5/77oqCZxRuJJloI+pSK4jsBYtDeccyVhfdjx0idLSOvMQpWTGAiPaA0AeRVyNYX9LVw2N8wODmdCLrYVhVroH0ASjeR6blfbjvdp0r7GxVF395g2X8HtsT3SUfFesO9W3I69k48VdjaUBfzAZqVUxBK72Tgct5W86G/0vbkKEaKOWtkEAmm9KGtzO2VU4XxLDxzp85gqp/ZMlKhDExLRaKGg6pebAfgeTE3V5jcozIl4Iz8Uzer0w2budzthfpcy7rw33Vii0TdKkj2hCX+of4D5JTcIDdN9jUC0nhR1zY9SPKqA2I86zaY9FI71+r1RhV/W7xELwMojv6EH3Yh5L+rLFOwvKOR/8waUHrmbk43GW3RD3yDhY3HbhfsOW/ZqPyBXu0C6kTZGCnSIpctFTx+D0IYZWh5Y/buvcyC0sx1n90Fsyc57fNTKHli5O/g7kncG7WLwo6T4=,iv:SyFn6vEDf99Fs9A0xSpbzMvI6JNfBfd+ZXKJkSJcKnU=,tag:L2UT5ITJKMPJjbURHA2eag==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ1d1dVU5cTV4ZlBHN2s0
            VDMxdjdtaEhkRVRTcndnMmU2S0RXYXRQZmd3CjhVQUhFbTAzcVdmWkZjNkJRaTNS
            cnMrS1JUakYwK3l4ak1uS0dzOUdHVWsKLS0tIFF4UG02ZXhJL2FMb09XNDFiTGRZ
            YVEyV0RZZ1RnNTk2OStXZVphdDBsV0EKMHEURCNIY544u+p0FYQ7r1khrpujEXaq
            JfTazsYnF7nn5hrsiER3dhyhzovzpr2WyFSiKLn2gt7KrWx9bmAVgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d3BYekVDRGJNYmdWNnVG
            dEp2NjhyYUFIMlg4MGtCUlFKOFlab05aRG1FCnh0OUU2ZTBHUm5OZjB6MnN6Q1VS
            TU1CN0VtS1RJaENmM2dsVjdEZENtYUEKLS0tIGN6SXdZOEdSbWg2K3lBOTVzUk90
            VlQ2Q3BXbWtUdUU3Qklla0srbGpJTVUKRLd0rlnFMI5gOMVckFRhjQec0ZChwRmf
            nTF3NE5fFeLUwVIOAZ6W2nZh3PhhqZLiuG4+JDTpRAIijH54xWJO/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T10:32:19Z"
    mac: ENC[AES256_GCM,data:L6elqrBgfMEZHjyozE0MM+l7x7gaDWjnAv/Dvmu3OTCMczELo7lgRpMpeIP9LLWOkSP5Q1jK5XuLbCDy1nW32oqZsGx5tWUFdRmzAyj0I3uydkVxyab/rU0nu3yWWRFI6Pj3UWfxlETMYkLLbWzeHtXHxb9mAtwB9Hgs6Hj2ekw=,iv:e8on4vtI4oGAgBMZwXbXu6nXH7T0Avoq60Z7KcgeQEI=,tag:BEChn/iBkSWOxS/6Q/xHhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
