---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app astroluma
  namespace: utilities
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      navidrome:
        containers:
          app:
            env:
              PORT: 8000
              NODE_ENV: production
              SECRET_KEY: hdwoDnPWslAtK3079kWYjPnSfCwcfiFz
              MONGODB_URI: mongodb://mongodb:27017/astroluma
            image:
              repository: sanjeet990/astroluma
              tag: latest@sha256:ba9568c5d0ee83bd2b1ba71babf3137edee3df15afb270225fc0ed4941827a6d
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host astroluma.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8000
