apiVersion: v1
kind: Secret
metadata:
    name: adguard-secret
    namespace: networking
type: Opaque
stringData:
    ADGUARD_USER: ENC[AES256_GCM,data:NG1eyvs=,iv:6nPQNxKOa07GG7PVQib/pULWc8a2jaXl7gL+rwqPM3U=,tag:toWvy1FAAKduMd/Y2/IQ2w==,type:str]
    ADGUARD_PASSWORD: ENC[AES256_GCM,data:TRZivOBCKi+e8OSa8cBHRRL+yDWY7VgrFnY=,iv:NKiIzA1037R29B8nBWRtnnqz2BGuUOgpMIfK7NE+iVg=,tag:TjnaOq7QI1Z5MiujIwEbJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb09FUnJDMWtoRE42K21k
            OEY3Q1c0SXFFMHJEajBLd2FSZnZhcmxjdVdNCnJOSXkyUnJacGh0S0p0UjhqTUwy
            NHZoRkFSU0VoTHdCWWZvekVVenJxL3MKLS0tIGVPaXBSeXhTU0J2U25wMnV4YVVC
            WC9XSFE5WGdXSjR4bys1SzhFUGtHcFEKDa8ZemOHc8J29tJBJ/GGvz4meK0Oe+6p
            8ZDktzF3BjG+PKmp8wTKcFakJZktcbEvhcYVZqPhYfeV8b//2vyVKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV3hGaVJRenY3eExtcnc1
            dXdza2R1TjRVcElUWiszbjRNUzNTSW0raWpBCnZoUkxjTkdmS0J4Y2VVV2pudURV
            RnE3cUdJWXpOTHZOK05HUHdHSEJzbEEKLS0tIEJtYXM0eFppdE01SmgrcElTbktG
            WUUvc1RnOWxzZnprd2F2WjYwVkpuYzgK1QRRZ/StxnwKLPMDhb8tZQi4R6smEFri
            XDzxrVkbj7fnFO6AkETjD6lHyVSDsEKUu81WxTFmtNX7pygkPEQzIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-27T07:16:58Z"
    mac: ENC[AES256_GCM,data:B3XwjZsP6hg6WxVf6CfeQYaRTMzzVJsREqIem0CQtyHrc/f/6bvFcRqjvZC9XbNk4leVrYxTSW7Fn0OYqDVz4482VuC1xGahYpdyqcViLS4lMa9pEzWIQvQZ++WQhWe8fpQIMqiUqm37K9N2rgHws6rwE3bPSgra8yJKspKCyAw=,iv:MhJ9OEmainHSZAdUXAFGbxBVP996FMFZbYD1CCCtLn4=,tag:ZcZXyrZr7xWX95YT7dprhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
