---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/common
  - ../../components/sops
  - ../../components/privileged-namespace

resources:
  - ./namespace.yaml
  - ./listenarr/ks.yaml
  # - audiobookshelf
  # - calibre
  # - calibre-web-automated
  # - flaresolverr
  # - invidious
  # - jellyfin
  # - jellyseerr
  # - metube
  # - navidrome
  # - piped
  # - prowlarr
  # - qbittorrent
  # - radarr
  # - sabnzbd
  # - sonarr
