apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - forgejo
  - frigate
  - goldilocks
  - homepage
  - home-assistant
  - mosquitto
  - reloader
  - renovate
  - pgadmin
  - pgbackweb
  - theme-park
  - uptime-kuma
  - vpa
