apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyseerr
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: fallenbagel/jellyseerr
              tag: 2.7.3@sha256:4538137bc5af902dece165f2bf73776d9cf4eafb6dd714670724af8f3eb77764
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/config
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 5055
