---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      pgadmin:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: dpage/pgadmin4
              tag: 9.13@sha256:d243a4bcc02d2ee6b447c601692813531d2d0fbca18b583d9f7f9658da835d81
            env:
              PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
            envFrom:
              - secretRef:
                  name: pgadmin-secrets
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 500Mi
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /var/lib/pgadmin
    route:
      app:
        hostnames:
          - '{{ .Release.Name }}.${ROOT_DOMAIN}'
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 80
