# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: hoarder-secret
    namespace: selfhosted
type: Opaque
stringData:
    encryption_key: ENC[AES256_GCM,data:+A7X4AxlAI/CSN3z2Sykgo7tHOf3zh9wFeed/qQbXWqDYikYYKYcY0smCPoT77xX,iv:Wi9ci31duyKyiDrv/U5HblT4rbSJtGvNoVg5xOh7cHM=,tag:oR44xgHO6fLPNPKnRkkhnQ==,type:str]
    meilisearch_master_key: ENC[AES256_GCM,data:XwJlmgFvEJMFqpqtFIv5grbJdPTBj8vC90UI3uluBF0GsG8yBaHeu9x2wRk1jUas,iv:rwqbJJSKHu373Gtsx8LPcFS0/NRXYPnYOo/l1i2Y+us=,tag:FMSWq1JBUjqrSWcVFU1uSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQWRHZ1dmRXJicGNSdEF1
            bm9MUWRFZFRubUtnZWdIOFNDVTNHYUM3K0I0CkVHck5paVB3OWtRMlhqU08yWmxv
            Z1JFcm5kemRpVE5UcWNIbisxNW5PaFUKLS0tIGxjaFpISDVIRjkvWGNocTZOZlEr
            TEI5UmpJb2g0S0l2Sm9MdnRXSGZ0c2MK7bg4LBw4GVe4WGb/sbig/YT7cCN9UtSm
            DviIgmGu1GUtRNXAJEajUq1rryct0oOuorFR2FXKvyqKPpaINEGjxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OTZKb0pMRENETk9pdTFS
            ZG5SYWNTOXVyNktJT2pIWjM4enlTZFVabkZVCjgxd2crYVk1MkdYdVVJV0UxLzNw
            ZElHWFZBTkt2SWFMZFc4V2kxdTh5VUEKLS0tIHVMZlN5WmtBeFVybCtoSzBRVmtY
            LzM1OTY1OXhSd1VLazkzWU1EOFdVbncK1H8j901+IZhDjAdDeZOsZ1y4DH1QP0GW
            gV9h+LTJpjknGS4K77j4hba7SrZPkYj+Ezyc5VlX/NcuJhPJ8Riyfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T07:27:23Z"
    mac: ENC[AES256_GCM,data:8lGj8U9RQNMsl/PkrGyDCyMYM5wTE/sj83H2cvb4OIHj5iS002svf/fUq0hiSJiyZ28tuXusfi9i+oT8aD1GTdR6IkrxRqBr/EgtBVIHMwOEmFnOBkbFk2Os5kbdzEHydkfZ+02la/n3CVtJQ4spptiZ4hsZCFTI0rJKFjOPWBY=,iv:Zg9zGUmO6+RD/rYoSU1dRvKKLiBKeqmRtVJVLapGp2I=,tag:thkaENAs9ehXsnaJnNFDuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
