---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app databasus
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      databasus:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-chmod-data:
            image:
              repository: busybox
              tag: 1.37
            command: ["sh", "-c", "chmod -R 700 /databasus-data"]
        containers:
          app:
            image:
              repository: databasus/databasus
              tag: v3.16.3@sha256:91498d6a50222c62db3cc4e2a40b01b9c448d15709d649976cc88568f881b5e4
            securityContext:
              readOnlyRootFilesystem: false
              capabilities:
                add:
                  - CHOWN
        type: statefulset
    persistence:
      databasus-data:
        existingClaim: *app
    route:
      app:
        hostnames:
        - '{{ .Release.Name }}.${ROOT_DOMAIN}'
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        ports:
          http:
            port: 4005
