---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app databasus
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      databasus:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/databasus/databasus
              tag: v3.49.0@sha256:18fd2e22f6a2ccb04e30ff0dd4805f518b1d1ef2157490c9e3841f083ef67197
    persistence:
      databasus-data:
        existingClaim: *app
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Database
          gethomepage.dev/name: Databasus
          gethomepage.dev/icon: https://raw.githubusercontent.com/databasus/databasus/main/assets/logo.svg
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 4005
