apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rxresume-client
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.3
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      rxresume-client:
        containers:
          app:
            image:
              repository: amruthpillai/reactive-resume
              tag: client-3.7.2@sha256:04b561446fb40852e72ce62fd15340424c73cde86a0df4b6e0b7888bf5e53102
        replicas: 0
    envFrom:
      - secretRef:
          name: rxresume
    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            rewrite /api/(.*) /$1 break;
        className: internal
        enabled: true
        hosts:
          - host: &host rxresume.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
              - path: /api
                pathType: Prefix
                service:
                  name: rxresume-server
                  port: 3100
        tls:
          - hosts:
              - *host
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
