apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: utilities
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:YUfjpsOg+L7/ywX6+a8heg==,iv:dzdOzmYgnFdoBxFx1spqrqQrBc2S8EXCf1ZNX4SG0wo=,tag:n3PyGBTcT1LrFBEG36kbyQ==,type:str]
    password: ENC[AES256_GCM,data:xuL1MvdDM6rjxgLKpEMbv9g6+a506Am1,iv:uMaFb8H6Xyo9kEsl3pDhPTj3Aqxo6zhIPxczu6X/9Ck=,tag:2BgEgR0zJpnXnqWt03Einw==,type:str]
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:EylgQz2mcTK2aODeJE9pAQ==,iv:nmC00TVztBSzrxUCd+dmKv3KoZUEBu9d5uzxJKKExSA=,tag:93qtEtQtrSngRcakVM9rXw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:ZSDI/UQZe22pfhB41ctz5/SP4x6einSe,iv:7K6ndPgxnQcfJizlbM96ObN/CDTi0FZTEcYN/DbwBMw=,tag:uBouyJD2ChdQkO6K2ohYpA==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYTUyZ1dGbHZCOXRMaHlv
            Y01OeFJtS0dFQ3hndHZPbFN5RzYvSVd1UFRZClA2QThLZlpncDRxTzg3V0JBZVlF
            YW5yaWkrMnZaK2YwS2NmRFpGdm9Uc1kKLS0tIEwwcGI0dFVCUDE1RDRWRWMvcUM2
            cDhTb1gxYm1qVFlDcGpNU081UE1USG8KPVJGE7SQ9dlpFfMJ/MOThI1Ydb2xUEcC
            Ed6aj1UHZlbmJw0ZNCv6J4Q45r0kD90BSBiKUOIJrrZJw44K2m6Seg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ai9DYy9Wd3dORmdIYlFw
            T2dEV0VuVmE4S0wweGhJVzNaM0FKbjFDSmpnCjZ4YmtMUy9yam1WVy9vNHlNY0RZ
            V05HTlNwakx6UVFzSElDSW5LOVhYYmMKLS0tIEQ4S01ML1VIK0E2TlNDTG1SMXk3
            bDd2aEJlYm56V1hOQ1ErNlprdmtPSTAK6PyICVKZoNrZBqK4E+sZP9l++senA/6t
            E4KxssZ/qeGf9VHEmwS4oP2nU4qG/aGN7XRsqjVibQvULr4a5D7iSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T09:21:26Z"
    mac: ENC[AES256_GCM,data:Lv0F5Clx0l8WZp9uyPYnkcyxb4t3NZPl7pCJGywkFnnOvTOGQEfAsWW+fFu9ryWNe795lxDs5QtGGK7u+6md/dMLeVcvgC53/eXmNM7H89l4nWmmLLydRg1rXCIbt1MtqqpRKB63++g6iweZ4oy16N9fFJCvO1qO4Fg7iaj2Eu8=,iv:mnKfwD9D3U1Qagz87yIrT01DL2h1+CLL6TWR9K0HEus=,tag:bbZDxh7Gm2Otz4y7yyG9TA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
