apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: fallenbagel/jellyseerr
              tag: 1.9.2@sha256:8f708df0ce3f202056bde5d7bff625eb59efe38f4ee47bdddc7560b6e4a5a214
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: jellyseerr.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - jellyseerr.${ROOT_DOMAIN}
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /app/config
        path: ${NFS_PATH}/jellyseerr
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: jellyseerr
        ports:
          http:
            port: 5055
