apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ytdlpwebplayer
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      ytdlpwebplayer:
        containers:
          app:
            image:
              repository: matszwe02/ytdlp_web_player
              tag: v1.0.0@sha256:74dc924e3b0228f24016a1c023f39eb8621b0bbe6e1163b0317a33748e73d48d
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: false
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: *app
        hostnames:
          - "web-player.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 5000
