apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ytdlpwebplayer
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      ytdlpwebplayer:
        containers:
          app:
            image:
              repository: matszwe02/ytdlp_web_player
              tag: v1.1.0@sha256:f327ed4979487de4b2171c2aac20b47ad24928e672da093ec1159b6b2baa850b
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: false
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: *app
        hostnames:
          - "web-player.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 5000
