apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ytdlpwebplayer
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      ytdlpwebplayer:
        containers:
          app:
            image:
              repository: matszwe02/ytdlp_web_player
              tag: v1.0.1@sha256:d273e32612c848e38b044306d72b9496bde2cf52003cf6fbed35f40a1c1ccebc
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: false
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: *app
        hostnames:
          - "web-player.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 5000
