apiVersion: v1
data:
  DB_STORAGE_TYPE: "HDD"
  DISABLE_REVERSE_GEOCODING: "true"
  NODE_ENV: "production"
  REDIS_HOSTNAME: valkey.default.svc.cluster.local
  IMMICH_SERVER_URL: http://immich-server.cloud.svc.cluster.local:2283
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.cloud.svc.cluster.local:3003
  IMMICH_LOG_LEVEL: "debug"
  TYPESENSE_HOST: immich-typesense.cloud.svc.cluster.local
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  TYPESENSE_DATA_DIR: /config
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: immich-configmap
  namespace: cloud
