apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: cloud
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      machine-learning:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.106.2@sha256:3aecde307deb0c881a1b4cbaf51db965e5ba1c085b8b4abb1a88c0225812cb05
            resources:
              limits:
                memory: 5000Mi
              requests:
                cpu: 100m
                memory: 800Mi
      server:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.106.2@sha256:7c853eee0f9a6f742dafe71db64486a34067f24d253cba3ddc7b7eaa7420f00c
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: '0'
          nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          external-dns.alpha.kubernetes.io/target: external.${ROOT_DOMAIN}
        className: external
        enabled: true
        hosts:
          - host: immich.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: server
                  port: http
        tls:
          - hosts:
              - immich.${ROOT_DOMAIN}
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc
        globalMounts:
          - path: /usr/src/app/upload
    service:
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
      server:
        controller: server
        ports:
          http:
            port: 3001
