---
# yaml-language-server: $schema=https://schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-database
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: external-secrets
      namespace: external-secrets
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: immich-cluster
      namespace: cloud
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      current: status.phase == 'Cluster in healthy state'
  path: ./kubernetes/apps/cloud/immich/database
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
  prune: true
  targetNamespace: cloud
  timeout: 5m
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: immich
# spec:
#   interval: 1h
#   path: ./kubernetes/apps/cloud/immich/app
#   postBuild:
#     substituteFrom:
#       - name: cluster-secrets
#         kind: Secret
#       - name: cluster-settings
#         kind: ConfigMap
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: immich
#     namespace: flux-system
#   targetNamespace: cloud
#   wait: false
