# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: renovate-secret
    template:
      data:
        RENOVATE_TOKEN: "{{ .renovate_token }}"
        RENOVATE_GITHUB_COM_TOKEN: "{{ .pat_renovate_operator }}"
  dataFrom:
    - extract:
        key: renovate
