# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: renovate-secret
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: forgejo
        property: renovate_token
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        key: forgejo
        property: pat_renovate_operator
