---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo
spec:
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        ["pnpm run bundle"]
  image: ghcr.io/renovatebot/renovate:43.249.0
  parallelism: 5
  provider:
    name: forgejo
    endpoint: https://git.${ROOT_DOMAIN}/api/v1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 */6 * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-secret
        key: RENOVATE_TOKEN
    forgejo:
      sync:
        enabled: true
        webhookURL: https://git.${ROOT_DOMAIN}/webhook/v1/forgejo
        topic: renovate
        tokenSecretRef:
          name: renovate-secret
          key: RENOVATE_TOKEN
        authTokenSecretRef:
          name: renovate-secret
          key: RENOVATE_TOKEN
