# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secret
    namespace: selfhosted
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Yx3a9rVRX2vcgaaUhANnhXz/52uM3k9RT4aFyvumSvIxoHVghHFNaueVedgnjuAzJgOhjFUiO1vdgA+SalRKTJdHiJI4wfafPHqgibpi5XzaZHZCt2BV9oSB8BW8AY/GULQhiP8=,iv:7LAoZNyLaNkVt7Tyz3pPqPucJiZnilcFAQRKS/oa11M=,tag:j3QH8oLR9AQmDHdpMKE2gg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:199YYWjvRr+8Dw==,iv:hACeb2a01PLIWtpUBWwpCNjCG7EaNgcqWZ/k5Oquy6c=,tag:SpufeE27azudE7pFwuA/mg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:f6jJtyDlt+EkziVDds7U4rwsY4DupKGuHRMBOe467UXAnIcG,iv:nPPdD4opxna6Em5CHLQi136xZ5sr2jBcaivB7OjUbZk=,tag:WehX9I/VlRGOaFggiIJNIQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:GMzBhb5pNOG1sL+q4TzBtymOaCrWK8RK,iv:5J6ZNFnHXQiGCFe/ZrQ59snkeY6a1DtVCHzOt3cEDF0=,tag:yGeuYYZrRM3ll5Y90oXzYA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:kTL/GaoxAbBvYA==,iv:ynrnE1ju6kQVthkpvG7DHGR5X/Z5Ck/VIu6UcUVURjs=,tag:1qyY9pVkI19vfIx1vCCQ4Q==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:i/oIbtgKRtH79F52tX9WU8YUEOjDpACTEibGSvCzgVdZgGR5t/S9EUcgO13n28gCSwG8p1ttxs3EPQlQrnd6Mg==,iv:QrvXKDopgkAyY0EzPK+Ks7DD3JlUdUGLBxIVJrVyqUE=,tag:Ni/UQU3jYVjqXkRsgvHkkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T08:55:19Z"
    mac: ENC[AES256_GCM,data:187LfEdGjGbBDVhD3SySg2mmo9sbhXxfSh2WNZiOqqDtY9qFskVuqK75RJjiJNf9jIp6FBxJo0lp1JaLD2tShmvYDu0e0KD4yzXa4kRHd8oytKsAEGO3G3OyrHnedXEymYcIFZHo24xWcJzMPNLV5991tbvR0ZzHQ1y1PLr3r68=,iv:kHmTWS+4AUUeNtvBW267z/unbEA74rL2zvKMahwmVK8=,tag:fLP7JfU73Of+QTVtERz6lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
