apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: utilities
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      frigate:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
              USE_FP16: 'False'
              YOLO_MODELS: yolov4-tiny-416
            envFrom:
              - secretRef:
                  name: frigate-secret
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.14.0-rc1@sha256:d414443dfae21320b775fbd5c783824fcb665d5d644879b079b214ba720f082e
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: &port 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 600
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              limits:
                memory: 8Gi
              requests:
                cpu: 100m
            securityContext:
              privileged: true
                # pod:
                # runtimeClassName: nvidia
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host "{{ .Release.Name }}.${ROOT_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      cache:
        enabled: true
        globalMounts:
          - path: /dev/shm
        medium: Memory
        sizeLimit: 4Gi
        type: emptyDir
      config:
        enabled: true
        existingClaim: frigate-data-pvc
        globalMounts:
          - path: /data
      config-file:
        globalMounts:
          - path: /config/config.yml
            readOnly: true
            subPath: config.yml
        name: frigate-configmap
        type: configMap
      media:
        enabled: true
        existingClaim: frigate-media-pvc
    service:
      app:
        controller: frigate
        ports:
          http:
            port: *port
          rtsp:
            port: 8554
