---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crowdsec-config-pv
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: ${NFS_PATH}/crowdsec/config
    server: ${NFS_HOST}
  storageClassName: crowdsec-config-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-config-pvc
  namespace: utilities
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: crowdsec-config-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crowdsec-data-pv
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: ${NFS_PATH}/crowdsec/data
    server: ${NFS_HOST}
  storageClassName: crowdsec-data-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-data-pvc
  namespace: utilities
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: crowdsec-data-nfs
