apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: infra
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.4.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      authelia:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            args:
              - --config
              - /config/configuration.yaml
            envFrom:
              - secretRef:
                  name: authelia-secret
            image:
              repository: ghcr.io/authelia/authelia
              tag: 4.38.14
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 5m
                memory: 10Mi
        pod:
          enableServiceLinks: false
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: auth.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - auth.${ROOT_DOMAIN}
    persistence:
      config:
        enabled: true
        name: authelia-configmap
        type: configMap
    service:
      app:
        controller: authelia
        ports:
          http:
            port: 9091
          metrics:
            enabled: true
            port: 8080
