apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-microservices
  namespace: cloud
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.6.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            args:
              - start-microservices.sh
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.101.0@sha256:0097562444db38ebd2e5f98e71bd27dc6dd69b7f786207f7d323febbf99b8f93
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc
        globalMounts:
          - path: /usr/src/app/upload
    service:
      main:
        enabled: false
