---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name crunchy-postgres
  namespace: dev
spec:
  postgresVersion: 16
  metadata:
    labels:
      crunchy-userinit.ramblurr.github.com/enabled: "true"
      crunchy-userinit.ramblurr.github.com/superuser: "postgres"

  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      replicas: &replica 1
      dataVolumeClaimSpec:
        storageClassName: local-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

  users:
    # Superuser
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: atuin
      databases:
        - atuin
      password:
        type: AlphaNumeric
    - name: autobrr
      databases:
        - autobrr
      password:
        type: AlphaNumeric
    - name: piped
      databases:
        - piped
      password:
        type: AlphaNumeric

  backups:
    pgbackrest:
      configuration: &backupConfig
        - secret:
            name: crunchy-postgres-secret
      global: &backupFlag
        compress-type: "bz2"
        compress-level: "9"
        # Minio
        repo1-block: "y"
        repo1-bundle: "y"
        repo1-path: /crunchy-pgo
        repo1-retention-full: "30" # days
        repo1-retention-full-type: "time"
        repo1-s3-uri-style: path
      manual:
        repoName: repo1
        options:
          - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-backup
      repos:
        - name: repo1 # Backblaze
          s3: &backblaze
            bucket: ${BACKBLAZE_BUCKET}
            endpoint: ${BACKBLAZE_ENDPOINT}
            region: "us-east-1"
          schedules:
            full: "0 2 * * 0" # Sunday at 02:00
            incremental: "0 2 * * 1-6/2" # Mon-Sat at 02:00, every 2nd day

  # dataSource:
  #   pgbackrest:
  #     stanza: "db"
  #     configuration: *backupConfig
  #     global: *backupFlag
  #     repo:
  #       name: "repo1"
  #       s3: *backblaze

  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M
