apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app atuin
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.6.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      atuin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            args:
              - server
              - start
            env:
              ATUIN_HOST: 0.0.0.0
              ATUIN_METRICS__ENABLE: "true"
              ATUIN_METRICS__HOST: 0.0.0.0
              ATUIN_METRICS__PORT: 8080
              ATUIN_OPEN_REGISTRATION: "true"
              ATUIN_PORT: 80
              ATUIN_TLS__ENABLE: "false"
            envFrom:
              - secretRef:
                  name: atuin-secret
            image:
              repository: ghcr.io/atuinsh/atuin
              tag: 18.4.0@sha256:8c6fa0aea944bf2a39665c9c69df1c2c0f9c05207bda5b942d450142285e3ee1
            resources:
              requests:
                cpu: 15m
                memory: 42M
              limits:
                cpu: 15m
                memory: 42M
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
        initContainers:
          init-db:
            env:
              - name: INIT_POSTGRES_SUPER_PASS
                valueFrom:
                  secretKeyRef:
                    key: postgres-password
                    name: postgresql-superuser
            envFrom:
              - secretRef:
                  name: atuin-secret
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        className: internal
        enabled: true
        hosts:
          - host: &host "{{ .Release.Name }}.${ROOT_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: emptyDir
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
          metrics:
            port: 8080
    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - interval: 1m
            path: /metrics
            port: metrics
            scheme: http
            scrapeTimeout: 10s
        serviceName: *app
