apiVersion: v1
kind: Secret
metadata:
  name: atuin
  namespace: selfhosted
type: Opaque
stringData:
  # App
  ATUIN_DB_URI: "postgres://atuin:KtaruroqeafA8SWpSuh5EhSj@cloudnative-pgvecto-rw.default.svc.cluster.local/atuin"
  # Postgres Init
  INIT_POSTGRES_DBNAME: atuin
  INIT_POSTGRES_HOST: cloudnative-pgvecto-rw.default.svc.cluster.local
  INIT_POSTGRES_PASS: KtaruroqeafA8SWpSuh5EhSj
  INIT_POSTGRES_USER: atuin
