apiVersion: v1
kind: Secret
metadata:
    name: atuin-secret
    namespace: selfhosted
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jp6k5A==,iv:MsydI/ddUme2S8xYQqyBWBKnZ9p1CYoyhivuXL61mes=,tag:T1BjXJfKFnVAeBLdtkwQrw==,type:comment]
    ATUIN_DB_URI: ENC[AES256_GCM,data:YeThvNZ9zliCp8e2TPjXYq1EMFpnlyZ1PjQ6h7yhHtAxt3X1b9coLBBR6eRcmUFjcAIJv4i8/bFNxKxAYDYwfmPSDmYoxARTiyF5hcuOB5PSiscdbpBkXkuc6j1BVwvm,iv:7xeCm2SD0il5YhHzqEKs7aH8/qIAhdQKPcTHV8EciNo=,tag:mm2j3aia081gcq9TDs8e2g==,type:str]
    #ENC[AES256_GCM,data:lQHwGeIGy7vSS+p/YQg=,iv:PmSrqbzgVECxv26UUOpfiu6msjzesHNdTAVpOTGjJQI=,tag:HqPVGkQCjO+Z6zg1i7pTOA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ZMzxLQ0=,iv:tRpdDmOLUD4SnMvm4onxsJpL/K1WG+BSQPsvUTeCkzI=,tag:UzXcMiWhufRxNsu8CB+CUw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:RAn3kEGTryD7tZCLkIA24jk/i2zRohvzenNq+S9KbXMQlf/znUQ1trwJhDfj3LQr+ByEhA==,iv:7PsNTTfrwlxyU7JaIq75NaIfa6Sai6k6vVrLwNMB9bA=,tag:HDkySDg2vp4g+aig8w41Nw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:M5gp+AfWa80DIhslK6NfOsKtfW2E2393,iv:BHHfCNd0TZQbFWgYF6E05VIJSeHfu7E1y/5fzoJ0CcI=,tag:164vPyxXu8EPGh1SKVFL3Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:spalcW4=,iv:9coQaBFLF0LBpbfNd0fghzvyhuSg/UPfYSaig0PT15Y=,tag:ordiZpbSF/OhOcaKJ4XNjQ==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TExyL0FwNEsraWYzT1NU
            b2lsdGkvUkM3T0R4NUtDVlRIdGh4ODdreW1BCnJYS1lyY3hiZkNCRHFIK3V0TEFU
            WDN1a1BlRVRyc3dxclg3M09WTFZrZjQKLS0tIFNEMGovNmV2ZFp3SVkvVUVJNG5l
            S05QMEI0a0QveERic3FmNXMrdEl6RjgKp03aXneRhjHRtP8hXLs2/ebAubf6q1Af
            HEZIxwyxfm8nMDgIw+6OsHO6l5ZfSsfaIUiJiLIbvkv1Hjmq7IsjMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MEpKZU0xeHUwT2lmUDZQ
            SnllLzg1U1FQcjNjdDVJT1cycUJxQlZLcjFrCk1rMUV6Z2hsQ1F3blgzMktZZGRK
            UUFQL3RWRkR1bEZ1ZXdjQUdndkxXa0kKLS0tIFhXK3QySW4rZ1BZVXJGV3RONUJw
            RzJFSDBSM3VKanhtVXo4NytuaEJFN00KxYW/JINnoRuHQn5USyvC9T+Ls8Jo1ztI
            ZCKSNgdYAZcKTVML2DIw6Z1YAhqpeAAEInYJF97jeenlAm8AFGeg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T01:07:52Z"
    mac: ENC[AES256_GCM,data:9gutps122I6oPU7whSFH7MD5XM5lYntpa6ODRjqbdYfThsmsDNd58pqTGHO8RN6WsQpwl3QYt/jnKuAOTa0x9rHYl3TVAl0gzkslhn/lvYLMjs6nEbT6jjkPQ3VYzPDwWA/AQEhq3oTqBid2+9rq/A/KZOCJgwjnbI8Fs0jkTZI=,iv:drhjHjsdn8G97BjN6WowKVVpNP7rODLMIU/kitCBcls=,tag:U/JRnr2FCuf/IfAKVN+OIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
