apiVersion: v1
kind: Secret
metadata:
    name: atuin-secret
    namespace: selfhosted
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jp6k5A==,iv:MsydI/ddUme2S8xYQqyBWBKnZ9p1CYoyhivuXL61mes=,tag:T1BjXJfKFnVAeBLdtkwQrw==,type:comment]
    ATUIN_DB_URI: ENC[AES256_GCM,data:E+huwQf+7tFhIgVaAdUGw1ISJyKFz3LcQtXJyGmA7cz8Okj7vlnTV+tzbswe5m/vqAckYSsji02lOLmAtBQhPdbOiylzqsRxePevPz8oXEwinJtRzYn27Pketm8VQJdO,iv:uMiQzWb2UUuCiMQH7S0Vipr1q6QfU4z3Rim3qQvm1xw=,tag:YM5/b4HfV73D+ic1E3OX0w==,type:str]
    #ENC[AES256_GCM,data:lQHwGeIGy7vSS+p/YQg=,iv:PmSrqbzgVECxv26UUOpfiu6msjzesHNdTAVpOTGjJQI=,tag:HqPVGkQCjO+Z6zg1i7pTOA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ZMzxLQ0=,iv:tRpdDmOLUD4SnMvm4onxsJpL/K1WG+BSQPsvUTeCkzI=,tag:UzXcMiWhufRxNsu8CB+CUw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:FIN1KKTCX0Egg/VLtHp1yCjUEVMNg7fzfb7lmnP7SRfTQmak6OxHbUGghrJgztwI,iv:gT2BBmo9C9rx9Ao88fLrXuXuNZ0EMSGQpsTK6tiVChI=,tag:yTn2oUd68VM7UuyRU06vfA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:M5gp+AfWa80DIhslK6NfOsKtfW2E2393,iv:BHHfCNd0TZQbFWgYF6E05VIJSeHfu7E1y/5fzoJ0CcI=,tag:164vPyxXu8EPGh1SKVFL3Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:spalcW4=,iv:9coQaBFLF0LBpbfNd0fghzvyhuSg/UPfYSaig0PT15Y=,tag:ordiZpbSF/OhOcaKJ4XNjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TExyL0FwNEsraWYzT1NU
            b2lsdGkvUkM3T0R4NUtDVlRIdGh4ODdreW1BCnJYS1lyY3hiZkNCRHFIK3V0TEFU
            WDN1a1BlRVRyc3dxclg3M09WTFZrZjQKLS0tIFNEMGovNmV2ZFp3SVkvVUVJNG5l
            S05QMEI0a0QveERic3FmNXMrdEl6RjgKp03aXneRhjHRtP8hXLs2/ebAubf6q1Af
            HEZIxwyxfm8nMDgIw+6OsHO6l5ZfSsfaIUiJiLIbvkv1Hjmq7IsjMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MEpKZU0xeHUwT2lmUDZQ
            SnllLzg1U1FQcjNjdDVJT1cycUJxQlZLcjFrCk1rMUV6Z2hsQ1F3blgzMktZZGRK
            UUFQL3RWRkR1bEZ1ZXdjQUdndkxXa0kKLS0tIFhXK3QySW4rZ1BZVXJGV3RONUJw
            RzJFSDBSM3VKanhtVXo4NytuaEJFN00KxYW/JINnoRuHQn5USyvC9T+Ls8Jo1ztI
            ZCKSNgdYAZcKTVML2DIw6Z1YAhqpeAAEInYJF97jeenlAm8AFGeg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T12:38:11Z"
    mac: ENC[AES256_GCM,data:Atwmr4m1+aILWCkVuNDAlwJCDPxeneA4k1JTRRd1dVAG7iLa2RXeHEe9oTdERyB6LuZ6ShOMpJgiTIZcQHO3OqgmNeybCMSRlvamUTvWI9eMtuVR+VSTlKw4URghaXmIdExoIAUxNAKUiySGSIWH+kYodcWVLooRBLE5hJv2EBA=,iv:iUj6kCxKNad35ztFwJeCbF4kS61x3KmsauHjLpEvsjk=,tag:gjiQ5sq3ZC0UVMaWEu6srQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
