apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app searxng
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      searxng:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/searxng/searxng
              tag: 2024.6.30-39aaac40d@sha256:149477f50e9fd7a90bd1455009b332433d65a9beeb0e0a6f9a4bdc11a860c0b6
            env:
              TZ: ${TIMEZONE}
              SEARXNG_BASE_URL: https://search.${SECRET_DOMAIN}
              SEARXNG_REDIS_URL: "redis://:${REDIS_PASSWORD}@${REDIS_HOST}:6379"
              SEARXNG_URL: https://search.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: searxng-secret
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${ROOT_DOMAIN}
        enabled: true
        hosts:
          - host: &host search.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
