---
httpRoute:
  enabled: true
  hostnames: ["git.${ROOT_DOMAIN}"]
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
tcpRoute:
  enabled: true
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: ssh
  port: 22

image:
  rootless: true
  registry: code.forgejo.org
  repository: forgejo/forgejo
  tag: 15.0.2-rootless

gitea:
  admin:
    existingSecret: forgejo-admin-secret

  config:
    cache:
      ENABLED: true
      ADAPTER: redis
      HOST: redis://valkey.default.svc:6379/14?pool_size=100&idle_timeout=180s
    database:
      DB_TYPE: postgres
      HOST: cluster-18-rw.database.svc.cluster.local:5432
      USER: forgejo
      NAME: forgejo
      SSL_MODE: disable
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
    lfs:
      PATH: /data/git/lfs
    mailer:
      ENABLED: true
      FROM: Forgejo <forgejo@${ROOT_DOMAIN}>
      PROTOCOL: smtp
      SMTP_ADDR: smtp-relay.${ROOT_DOMAIN}
      USER: forgejo@${ROOT_DOMAIN}
    migrations:
      ALLOWED_DOMAINS: "*"
    openid:
      ENABLE_OPENID_SIGNIN: false
      ENABLE_OPENID_SIGNUP: false
    queue:
      TYPE: redis
      CONN_STR: redis://valkey.default.svc:6379/14?pool_size=100&idle_timeout=180s
    repository:
      ROOT: /data/git/repositories
    session:
      PROVIDER: redis
      PROVIDER_CONFIG: redis://valkey.default.svc:6379/14?pool_size=100&idle_timeout=180s
    server:
      APP_DATA_PATH: /data/gitea
      ROOT_URL: https://git.${ROOT_DOMAIN}
      START_SSH_SERVER: true
      SSH_DOMAIN: git.${ROOT_DOMAIN}
      SSH_SERVER_HOST_KEYS: ssh/ssh_host_ed25519_key
      SSH_LISTEN_PORT: 2222 # rootless image
    service:
      ALLOW_ONLY_EXTERNAL_REGISTRATION: false
      ENABLE_INTERNAL_SIGNIN: true
      SHOW_REGISTRATION_BUTTON: true
      ENABLE_PASSWORD_SIGNIN_FORM: true
      ENABLE_NOTIFY_MAIL: true
    time:
      DEFAULT_UI_LOCATION: ${TIMEZONE}
    webhook:
      ALLOWED_HOST_LIST: matrix.${ROOT_DOMAIN},*.lithium.${OLD_DOMAIN}

  oauth:
    - adminGroup: admin
      autoDiscoverUrl: https://id.${ROOT_DOMAIN}/.well-known/openid-configuration
      existingSecret: forgejo-admin-secret
      iconUrl: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/pocket-id-light.svg
      name: PocketID
      provider: openidConnect
      scopes: openid profile email
  additionalConfigFromEnvs:
    - name: GITEA__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: forgejo-pguser-secret
          key: password

# service:
#   ssh:
#     clusterIP: 2001:cafe:43::ef37

valkey-cluster:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  create: false
  claimName: ${APP}

extraVolumes:
  - name: forgejo-ssh
    secret:
      secretName: forgejo-ssh

extraContainerVolumeMounts:
  - name: forgejo-ssh
    mountPath: "/data/gitea/ssh/ssh_host_ed25519_key"
    subPath: ssh_host_ed25519_key
