# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    CLOUDNATIVE_PG_HOST: ENC[AES256_GCM,data:Gpiw3kDhKyqkIKPt2JNls8/7mZnDH6rJmw==,iv:yw4xBTVvLeFnPJAyTGcihIj0Hd1ZBF6rWNVQumk30mQ=,tag:a8NYXIXlWPMTDtkfrIqtiw==,type:str]
    CLUSTER_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:BT0WoIX3G5TOH+8rLfEftRIKTSXmLKAxF6XY1wFlgNmMr/LY,iv:cUZhiO/a3QSIxpu88E3n/plTc1BpfEds6cjuQP0EH4A=,tag:IXb+5A6F+9B1pmq7T5SPCw==,type:str]
    DOCKER_HUB_PASSWORD: ENC[AES256_GCM,data:f3WzCyZYj0X5vHx29cW8RYQeGE74r+uB,iv:AOYDnNHbdUVCTgTSnst6bir5Vjwu/10P6+Rgcp9K2lQ=,tag:Hz+G0ivZp5inYNihbfd7sw==,type:str]
    DOCKER_HUB_USERNAME: ENC[AES256_GCM,data:tvpr2jIvHAww,iv:KyrE/A/6OS4cuErwEolfdvekJW2rPrQ0z8WFtuEJCeA=,tag:xqFLgrGWGU3PG1yyG7QTmw==,type:str]
    FRIGATE_RTSP_USERNAME: ENC[AES256_GCM,data:UnggBwHP,iv:TIwIPyGJAm1+/NxRBk5eVlGGBcIlm9AHgY86qhyhK3s=,tag:uTPQbI0DZHj8Xwov4Z0j9A==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:00Yvzy0b5VP7WcISwvtsg24RCi0=,iv:Z18agQOGTdEwwWQC22Tci5lQBDGNqHCdPdr6C+iUQsM=,tag:GSXowUWCNqIr8jrtgJWBnQ==,type:str]
    GIT_REPO_URL: ENC[AES256_GCM,data:5c9p3yQ0C2TMSq8FStl3b9Z82X5zuVHxlGxAKzcLlq7ZRYt+ISGPzAtqRSHRwQn+kF3VzS4pSILknQ==,iv:qluJQqTgDJ70XLG62zVV4Re0q2vhNjJSSsnPDO/JtVw=,tag:zBun4ymMtlgBHKAWroMTsw==,type:str]
    GITEA_REPO_URL: ENC[AES256_GCM,data:UB5t3U7dgjhWd4xMjcTV1QlDmi+kcR8EZJolfsbb96HtKIyPo1k8Sp/etUXzagWIKffnBNW48qafy6X3U2vjJTRMOMAF,iv:GE8dYEm+VgNhv6wIGkfEXu106cO40JtVJWfH/k8iOrk=,tag:T3iEsuVR6EZacXktNVgE6g==,type:str]
    REGION: ENC[AES256_GCM,data:vbQmT2CxQeaj/TJIbyQ=,iv:8mHRRxDqU3NNiLjAlrjwCJc75HXNLxjGwJ+sbF3LQvg=,tag:3HclHWXCsmGctNwPXAFsfQ==,type:str]
    ROOT_DOMAIN: ENC[AES256_GCM,data:bp6Zpcu4+nCtrQ==,iv:K5d4db+r8FlLUSD6mCYQdLxzCHXn1LYaFr9H005jdjk=,tag:mbF/vWfhnqr/x6f+ItQnOg==,type:str]
    OLD_DOMAIN: ENC[AES256_GCM,data:0ADDlueq8S+oSdUb6PQd,iv:iQBED5IdtW3PUqGvNUAf19s7frtjpQCFqa3Xenwzodc=,tag:IHKCpJG85pL3w9QWjsSfYw==,type:str]
    SECRET_LATITUDE: ENC[AES256_GCM,data:jFmcwWDu4g==,iv:ely+Cu9x6HMtpSbce95WcOU8+vNCwuP+3cFjTqPSZ5k=,tag:TpUKPFOKYH1T9TKgBtaJaA==,type:str]
    SECRET_LONGITUDE: ENC[AES256_GCM,data:LNwSJVOYfELu,iv:glF38SglzKfQQ3McT6qX/JD6LCLDlRnwsmrA/kB6/9I=,tag:ymnFVmMDh0+CW9GPNLr4jg==,type:str]
    SHORT_ROOT_DOMAIN: ENC[AES256_GCM,data:fp4H/gYvGlhjFg==,iv:j2fvYzQd9iBoGtBxs9CQGxn6/tkP7WFrADw0FvdXsQo=,tag:Yoo/n3aTtlOrCuM8wl+UUQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:UZAShRSBIg+0dOhR8R2V5rPSNNvgkQ/5cSDcVBf3lYlh7M1vuxhw3n96bhDjLt4zcv0n3oTU/XCl,iv:VYMHZm4z2WZu/DdeBddFn/1cJURtq1kLJnFQBw3paYM=,tag:7qJRUcYIVdn4Zts83ESooQ==,type:str]
    S3_POSTGRESQL_BUCKET: ENC[AES256_GCM,data:vb7ijnMZUS9nSRuC9qUgyrNi,iv:WPSuCW3aW9YFIk4S3APhTM6EaoBsw6LKMh+fmUi0NcY=,tag:HWDOwEzxK/zodbmZ8rnDuw==,type:str]
    BACKBLAZE_ENDPOINT: ENC[AES256_GCM,data:5paKLchg0QLpjELwVziYZYZAN/SyePqeo/k6ncS8,iv:4aSAvoy/Lt+Ffn+nQcT0UKz/AhZSXcP8M1Kcl13QjbA=,tag:fzaE2PUk3UqvVSnNUgostA==,type:str]
    BACKBLAZE_BUCKET: ENC[AES256_GCM,data:L+8kz6XwxZFwaOVTetFT2RuuB6qDIh59hkw=,iv:LGIoxaKZkJl7MqvcVhpNak+Lq6QYtPMK7VHVWjl2PwA=,tag:NI8PDGIXLavVcGHiy7whOw==,type:str]
    USERNAME: ENC[AES256_GCM,data:L5AreZo=,iv:TVjxVmfIlkuPKtQrndJHGvjMH2lfOYC/HxEp6PxUERg=,tag:KZBrJUCiT3pb3MmJ9Smg1g==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTm5WZS94MHVzVFdzL0ll
            Tk03SnZTaU5oQkJGcTdNdWNvVFVVeUFSZ1gwCmFHTUlSd1lXNUdYMmlGSWhmazFy
            NW45ZHhrSHZiNW0vN3c4dG9SL2l0a0EKLS0tIHU1M05pRWhiM2tFRnpvUWJkcWlp
            NE5vMDNkTmVzN2ZaUzVFTFhjYW15cWMKCYLD/K8vmECsJj7BRzKkpQ38Zw5KfYen
            6mAHu2NipqPuGHmFzifWPU4HV5wDLdxFft7wQQd+O0wVFQGafaUPKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MzljeDl1NnpZbzJMOU9s
            TTZiU2JpM1dDVXg2bFVkSzlncm1kVlUwWGpFCldHcnFTSWJ5UGx5Tnpnckgyamt3
            NjJid21JWC9WbDRkWnhHZEFacDk4VWMKLS0tIDd6U1A3TjczcFJUcXNJd3k3Z085
            MDVnc3I2U1VGN1pXS3J2Y0k4UGlHOVEKxNhlolP59NPJGjSTjN+8pLei8qn70duw
            Qe3wo1FDj4sIkpOI3dgi8iK/c+zDW+1BLxp8tn80I6EeCXzt0JH8xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T13:42:42Z"
    mac: ENC[AES256_GCM,data:Xk2ouhNHpBNGcUzgQhk+bW+rbgzrjKCzajWqddgxIZ07zmpESoP0c4cq4hY2rjlgFrPKrxJI+oOuPyDG1B1+rwJqe8ePQQk+HwhAY5Y7J3GbGoEfUySQckbs85Aq57oYaiYM32jKAxXneWJ/8GfPoMQx6gUxzvUYlkHxP7EFTFE=,iv:pb48IgT6CWQNvOO926Ka9Hhu0tuweeOFgLhT0FNBtDU=,tag:ecSpODI31Jym7XnQ0pgZ8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
