---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fbq
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: fbq-secret
    template:
      data:
        FILEBROWSER_OIDC_CLIENT_SECRET: "{{ .FILEBROWSER_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: fbq
