apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app fbq
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      fbq:
        containers:
          app:
            env:
              FILEBROWSER_CONFIG: "/data/config.yaml"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            image:
              repository: gtstef/filebrowser
              tag: 1.2.4-stable-slim@sha256:fa0754b5025d93d0a7d5f87a7e5ebf1cc9bbbea8a803aeacc5d09e7b81d2d0c8 
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    configMaps:
      config:
        data:
          config.yaml: |-
            server:
              sources:
                - path: /mnt/media
                  config:
                    defaultEnabled: true
                - path: /mnt/nfs
                  config:
                    defaultEnabled: true
                - path: /mnt/nfsBackup
                  config:
                    defaultEnabled: true
            auth:
              methods:
                oidc:
                  enabled: true
                  clientId: fbq
                  issuerUrl: https://id.${ROOT_DOMAIN}
                  scopes: "email openid profile groups"
                  userIdentifier: "preferred_username"
                  createUser: true
    persistence:
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /data/config.yaml
            subPath: config.yaml
      media:
        globalMounts:
        - path: /mnt/media
        path: /media
        server: ${NFS_HOST}
        type: nfs
      nfs:
        globalMounts:
        - path: /mnt/nfs
        path: ${NFS_PATH}
        server: ${NFS_HOST}
        type: nfs
      nfs-backup:
        globalMounts:
        - path: /mnt/nfsBackup
        path: /nfsBackup
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: selfhosted
        hostnames:
        - '{{ .Release.Name }}.${ROOT_DOMAIN}'
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        ports:
          http:
            port: 80
