---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./cluster-pgvecto.yaml
  - ./cluster-vectorchord17.yaml
  - ./postgresql16.yaml
  - ./scheduledbackup-postgresql16.yaml
  - ./scheduledbackup-pgvecto.yaml
