---
apiVersion: v1
kind: Service
metadata:
  name: cloudnative-pg-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: cloudnative-pg
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/instance: cloudnative-pg
    app.kubernetes.io/name: cloudnative-pg
