apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: utilities
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:B/iwxU5DXliRljLinSNoE99CiQ3yRmcRfI/8CeBtuL8Dps+/Bkp88hP1rp5TJv6sXw1NQKYSqyvOss/KgJXvAA9tbU0vAx57MGhsfqpQtH7P7IkJJUhYOGzYmQRz,iv:XrdqHFMABfwwlOLLgAa/k6Q1L9eVhr23LavP7/xN4JA=,tag:KCzzr9ZfiA731Q3raejX2Q==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:GVOJ+Ag59dxMQx81/HIWZEajWUduCflQrsbr04I=,iv:utqFGqRipnnGzHwf2NntPmJH6QijiJ3cKD6GIzjOnFo=,tag:m7UWf5zkiMkJ2/+64aKhHw==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:52FijgLU9mj6AftU3MdMfzKEw4Fg3NbH+rcVWeh/k1q3efA7cdKA,iv:NlHpfK5ApcPoDXhLSIGq33UPcSkHZwQpJAi30/4O5lo=,tag:pmKwLqtD8UNIN3qJLzMDAw==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:BeNXQ7cuJO+dgrGyHMh5VtmyDpGgJFDIeyTTSfiLKiMnC+qZ+DNx4g==,iv:Xz5IYBXQuosV9q8KJEdfhgdV641r7Ahx+Mkclzbcuuk=,tag:sgV3mE1QhYb/vLUTEF74Vg==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNForb082dG1vdERHNU9s
            TGJ6V00xdzIwZW9NRG5laWNnbWdKQVAvejJFClpIYU9EeW00K1ZQMWdaMHZ5Z1ZD
            aStqMjhIT0xvOTByVlBEclozUEtpdW8KLS0tIHM0Nzc3VjJUcnJkM1c1RSt6M2hq
            TU9hNjBiM3JFbWtNZUJmUUl0M0VCejQK1j1oZMBa1MPxWsug8H7YP8d6Jm636fCs
            IczwWSjJYYnU1VXuS5AovlzAfJQzn61ahjBIBCrvRpS6f5XOATuwLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ako2TWtRbnpIaFoxOVRu
            dFhVSmVQcWNFZmpSTCtSN1ovQURqMGhkcjNzCmIxcVBGVlYwQXNVRmxIRVMwbFp4
            RWpnM1UwZFFNUEdyODJYSDVMNklNKzQKLS0tIE1PNWsrWkhIL1ZEcWZScUJIYkV6
            ZVpRYkx1NVhEL2gweHJwdGpqK2tFdmsKRIPxTwafZDAob05BTULCt6SkXK4RJTGx
            4hb/O9fkkqmFBes8creJtx6i8EECCDoq7L63EshdLhv+NXdT8k3SaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T01:47:17Z"
    mac: ENC[AES256_GCM,data:CJx5IimdZHarH6QEkupbhDpTULREieCvUbf+RDawOVWKUg1bVCSvV5FfFfrl89d7FFMIty0mWb7kN+3wK7x2mmB1ns9keC6NZOW9IYLjM82lr6ue+TBFJTI93xXs7895JrDkngyUCepDfIBWB7fCm6DOluTuzT0Y78970MkHTlo=,iv:44dP+ZDAKq+9Z/s0hvCVvVTyiCOnK3r+lsh/sGf460Q=,tag:VSOzHG6Hl6XVgy9ctiP9Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
