---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name "${SHORT_ROOT_DOMAIN/./-}-tls"
spec:
  secretName: *name
  issuerRef:
    name: letsencrypt-staging-clusterissuer
    kind: ClusterIssuer
  commonName: ${SHORT_ROOT_DOMAIN}
  dnsNames:
    - ${SHORT_ROOT_DOMAIN}
    - "*.${SHORT_ROOT_DOMAIN}"
