apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photoview
  namespace: cloud
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      photoview:
        containers:
          app:
            envFrom:
              - secretRef:
                  name: photoview
            image:
              repository: viktorstrate/photoview
              tag: 2.4.0
        pod:
          securityContext:
            fsGroup: 33
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 33
            runAsNonRoot: true
            runAsUser: 33
        replicas: 0
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: photoview.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - photoview.${ROOT_DOMAIN}
    persistence:
      cache:
        globalMounts:
          - path: /app/cache
        path: ${LOCAL_PATH}/photoview-cache-pvc
        server: ${NFS_HOST}
        type: nfs
      photos:
        path: ${NFS_PATH}/nextcloud/data
        server: ${NFS_HOST}
        type: nfs
    resources:
      limits:
        memory: 2000Mi
      requests:
        cpu: 100m
        memory: 250Mi
    service:
      app:
        controller: photoview
        ports:
          http:
            port: 80
