---
- Cluster:
    - Cluster:
        icon: talos.svg
        description: Prometheus
        widget:
          type: prometheusmetric
          url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          refreshInterval: 10000 # in milliseconds
          metrics:
            - label: Cluster Age
              query: round((time() - min(kube_node_created) ) / 86400)
              format:
                type: number
                suffix: d
            - label: Cluster Memory Usage
              query: round(avg(instance:node_memory_utilisation:ratio) * 100, 0.1)
              format:
                type: number
                suffix: '%'
            - label: Cluster CPU Usage
              query: round(avg(instance:node_cpu_utilisation:rate5m) * 100, 0.1)
              format:
                type: number
                suffix: '%'
            - label: Running Pods
              query: sum(kube_pod_status_phase{phase="Running"})
              format:
                type: number
            - label: Available Nodes
              query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
              format:
                type: number
- Lithium:
    - Dozzle lithium:
        href: https://dozzle.lithium.${OLD_DOMAIN}
        icon: dozzle.png
        description: Simple Container Monitoring and Logging
    - Forgejo lithium:
        href: https://forgejo.lithium.${OLD_DOMAIN}
        icon: forgejo.png
        description: Beyond coding. We forge.
    - Isaiah:
        href: https://isaiah.lithium.${OLD_DOMAIN}
        icon: isaiah.png
        description: TBD
    - Pocket-ID:
        href: https://pocketid.lithium.${OLD_DOMAIN}
        icon: pocket-id.png
        description: A simple OIDC provider that allows users to authenticate with their passkeys to your services
    - Komodo:
        href: https://komodo.lithium.${OLD_DOMAIN}
        icon: komodo.png
        description: Deploy, configure, troubleshoot and secure containers
        widget:
          type: komodo
          url: https://komodo.lithium.${OLD_DOMAIN}
          key: "{{KOMODO_KEY}}"
          secret: "{{KOMODO_SECRET}}"
          showSummary: true
          showStacks: true
    - Unifi:
        href: https://unifi.lithium.${OLD_DOMAIN}
        icon: unifi.png
        description: Unifi console
    - Whoogle lithium:
        href: https://whoogle.lithium.${OLD_DOMAIN}
        icon: whoogle.png
        description: Ad-free, privacy-respecting metasearch engine
- Cloud:
    - Immich:
        href: https://immich.${ROOT_DOMAIN}
        icon: immich.png
        description: High performance self-hosted photo and video backup solution
        namespace: cloud
        app: immich
        widget:
          type: immich
          url: https://immich.${ROOT_DOMAIN}
          key: {{IMMICH_KEY}}
          version: 2
    - Minio:
        href: https://minio.${ROOT_DOMAIN}
        icon: minio.png
        description: S3 object storage
        namespace: cloud
        app: minio
    - OpenCloud:
        href: https://opencloud.${ROOT_DOMAIN}
        icon: sh-opencloud.svg
        description: Cloudstorage
        namespace: cloud
        app: opencloud
- Infra:
    - OPNSense:
        href: https://oxygen.${OLD_DOMAIN}
        icon: opnsense.png
        description: Firewall and router
        widget:
          type: opnsense
          url: https://oxygen.${OLD_DOMAIN}
          username: ${SECRET_OPNSENSE_USERNAME}
          password: ${SECRET_OPNSENSE_PASSWORD}
- Media:
    - Calibre:
        href: https://calibre.${ROOT_DOMAIN}
        icon: calibre.png
        description: calibre is a powerful and easy to use e-book manager
    - Invidious:
        href: https://invidious.${ROOT_DOMAIN}
        icon: invidious.png
        description: An alternative front-end to YouTube
    - Jellyfin:
        href: https://jellyfin.${ROOT_DOMAIN}
        icon: jellyfin.png
        description: Mediaserver
        widget:
          type: jellyfin
          url: https://jellyfin.${ROOT_DOMAIN}
          key: ${SECRET_JELLYFIN_KEY}
    - Navidrome:
        href: https://navidrome.${ROOT_DOMAIN}
        icon: navidrome.png
        description: Music Player
        widget:
          type: navidrome
          url: https://navidrome.${ROOT_DOMAIN}
          user: ${USERNAME}
          salt: ${SECRET_NAVIDROME_SALT}
          token: ${SECRET_NAVIDROME_TOKEN}
    - Piped:
        href: https://piped.${ROOT_DOMAIN}
        icon: piped.png
        description: An alternative front-end to YouTube
    - Stump:
        href: https://stump.${ROOT_DOMAIN}
        icon: /icons/stump.png
        description: Comics, manga and digital book server
- Media Management:
  - Jellyseerr:
      href: https://jellyseerr.${ROOT_DOMAIN}
      icon: jellyseerr.png
      description: TODO
      widget:
        type: jellyseerr
        url: https://jellyseerr.${ROOT_DOMAIN}
        key: ${SECRET_JELLYSEERR_KEY}
  - Metube:
      href: https://metube.${ROOT_DOMAIN}
      icon: metube.png
      description: Web GUI for youtube-dl
  - Prowlarr:
      href: https://prowlarr.${ROOT_DOMAIN}
      icon: prowlarr.png
      description: TODO
      widget:
        type: prowlarr
        url: https://prowlarr.${ROOT_DOMAIN}
        key: ${SECRET_PROWLARR_KEY}
  - Radarr:
      href: https://radarr.${ROOT_DOMAIN}
      icon: radarr.png
      description: TODO
      widget:
        type: radarr
        url: https://radarr.${ROOT_DOMAIN}
        key: "{{RADARR_API_KEY}}"
  - SABnzbd:
      href: https://sabnzbd.${ROOT_DOMAIN}
      icon: sabnzbd.png
      description: SABnzbd is an open-source binary newsreader written in Python
      widget:
        type: sabnzbd
        url: https://sabnzbd.${ROOT_DOMAIN}
        key: ${SECRET_SABNZBD_APIKEY}
  - Sonarr:
      href: https://sonarr.${ROOT_DOMAIN}
      icon: sonarr.png
      description: TODO
      widget:
        type: sonarr
        url: https://sonarr.${ROOT_DOMAIN}
        key: "{{SONARR_API_KEY}}"
- Selfhosted:
    - FileBrowser:
        href: https://filebrowser.${ROOT_DOMAIN}
        icon: filebrowser.png
        description: File managing interface
    - Linkwarden:
        href: https://linkwarden.${ROOT_DOMAIN}
        icon: /icons/linkwarden.png
        description: ️Self-hosted collaborative bookmark manager to collect, organize, and preserve webpages and articles
        widget:
          type: linkwarden
          url: https://linkwarden.${ROOT_DOMAIN}
          key: ${SECRET_LINKWARDEN}
    - Memos:
        href: https://memos.${ROOT_DOMAIN}
        icon: memos.png
        description: A lightweight, self-hosted memo hub
    - OpenSpeedTest:
        href: https://openspeedtest.${ROOT_DOMAIN}
        icon: openspeedtest.png
        description: HTML5 Network Performance Estimation Tool
    - Paperless-ngx:
        href: https://paperless-ngx.${ROOT_DOMAIN}
        icon: /icons/paperless-ngx.svg
        description: Scan, index and archive all your physical documents
    - PairDrop:
        href: https://pairdrop.${ROOT_DOMAIN}
        icon: /icons/pairdrop.png
        description: Sublime alternative to AirDrop that works on all platforms
    - Planka:
        href: https://planka.${ROOT_DOMAIN}
        icon: planka.png
        description: Kanban board
    - Redlib:
        href: https://redlib.${ROOT_DOMAIN}
        icon: reddit.png
        description: Private front-end for Reddit
    - RxResume:
        href: https://rxresume.${ROOT_DOMAIN}
        icon: /icons/rxresume.png
        description: Resume Builder
    - Stirling-PDF:
        href: https://stirling-pdf.${ROOT_DOMAIN}
        icon: /icons/stirling.png
        description: PDF manipulation tool
    - Vaultwarden:
        href: https://vaultwarden.${ROOT_DOMAIN}
        icon: bitwarden.png
        description: Password tool
    - Whoogle:
        href: https://whoogle.${ROOT_DOMAIN}
        icon: whoogle.png
        description: Ad-free, privacy-respecting metasearch engine
- Utilities:
    - Checkmate:
        href: https://checkmate.${ROOT_DOMAIN}
        icon: sh-checkmate.png
        description: Track and monitor server hardware, uptime, response times, and incidents in real-time
    - Dozzle:
        href: https://dozzle.${ROOT_DOMAIN}
        icon: dozzle.png
        description: Simple Container Monitoring and Logging
    - Element Web:
        href: https://element.${ROOT_DOMAIN}
        icon: element.png
        description: Element is a Matrix-based end-to-end encrypted messenger and secure collaboration app
    - Frigate:
        href: https://frigate.${ROOT_DOMAIN}
        icon: frigate.png
        description: Frigate is an open source NVR built around real-time AI object detection
    - Forgejo:
        href: https://forgejo.${ROOT_DOMAIN}
        icon: forgejo.png
        description: self-hosted lightweight software forge
    - Goldilocks:
        href: https://goldilocks.${ROOT_DOMAIN}
        icon: https://raw.githubusercontent.com/FairwindsOps/goldilocks/master/img/goldilocks.svg
        description: Helps identify a starting point for resource requests and limits
    - Grafana:
        href: https://grafana.${ROOT_DOMAIN}
        icon: grafana.png
        description: Metric Monitoring
    - Kubernetes:
        href: https://k8s.${ROOT_DOMAIN}
        icon: kubernetes-dashboard.png
        description: Kubernetes Dashboard
    - Weave:
        href: https://weave.${ROOT_DOMAIN}
        icon: /icons/weave.svg
        description: GitOps for K8s
    - Uptime Kuma:
        href: https://uptime.${ROOT_DOMAIN}
        icon: uptime-kuma.png
        description: A fancy self-hosted monitoring tool
        widget:
          type: uptimekuma
          url: https://uptime.${ROOT_DOMAIN}
          slug: up
