---
- Cluster:
    - Cluster:
        icon: talos.svg
        widget:
          type: prometheusmetric
          url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          refreshInterval: 10000 # in milliseconds
          metrics:
            - label: Cluster Age
              query: round((time() - min(kube_node_created) ) / 86400)
              format:
                type: number
                suffix: d
            - label: Cluster Memory Usage
              query: round(avg(instance:node_memory_utilisation:ratio) * 100, 0.1)
              format:
                type: number
                suffix: '%'
            - label: Cluster CPU Usage
              query: round(avg(instance:node_cpu_utilisation:rate5m) * 100, 0.1)
              format:
                type: number
                suffix: '%'
            - label: Running Pods
              query: sum(kube_pod_status_phase{phase="Running"})
              format:
                type: number
            - label: Available Nodes
              query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
              format:
                type: number
    - OPNSense:
        href: https://oxygen.${OLD_DOMAIN}
        icon: opnsense.png
        widget:
          type: opnsense
          url: https://oxygen.${OLD_DOMAIN}
          username: {{HOMEPAGE_VAR_OPNSENSE_USERNAME}}
          password: {{HOMEPAGE_VAR_OPNSENSE_PASSWORD}}
- Lithium:
    - Dozzle lithium:
        href: https://dozzle.lithium.${OLD_DOMAIN}
        icon: dozzle.png
    - Forgejo lithium:
        href: https://forgejo.lithium.${OLD_DOMAIN}
        icon: forgejo.png
    - Pocket-ID:
        href: https://pocketid.lithium.${OLD_DOMAIN}
        icon: pocket-id.png
    - Komodo:
        href: https://komodo.lithium.${OLD_DOMAIN}
        icon: komodo.png
        widget:
          type: komodo
          url: https://komodo.lithium.${OLD_DOMAIN}
          key: "{{HOMEPAGE_VAR_KOMODO_KEY}}"
          secret: "{{HOMEPAGE_VAR_KOMODO_SECRET}}"
          showSummary: true
          showStacks: true
    - Unifi:
        href: https://unifi.lithium.${OLD_DOMAIN}
        icon: unifi.png
    - Whoogle lithium:
        href: https://whoogle.lithium.${OLD_DOMAIN}
        icon: whoogle.png
    - Zerobyte:
        href: https://zerobyte.lithium.${OLD_DOMAIN}
        icon: zerobyte.png
- Cloud:
    - Immich:
        href: https://immich.${ROOT_DOMAIN}
        icon: immich.png
        namespace: cloud
        app: immich
        widget:
          type: immich
          url: https://immich.${ROOT_DOMAIN}
          key: {{HOMEPAGE_VAR_IMMICH_KEY}}
          version: 2
    - Minio:
        href: https://minio.${ROOT_DOMAIN}
        icon: minio.png
        namespace: cloud
        app: minio
    - OpenCloud:
        href: https://opencloud.${ROOT_DOMAIN}
        icon: sh-opencloud.svg
        namespace: cloud
        app: opencloud
- Media:
    - Calibre:
        href: https://calibre.${ROOT_DOMAIN}
        icon: calibre.png
    - Invidious:
        href: https://invidious.${ROOT_DOMAIN}
        icon: invidious.png
    - Jellyfin:
        href: https://jellyfin.${ROOT_DOMAIN}
        icon: jellyfin.png
        widget:
          type: jellyfin
          url: https://jellyfin.${ROOT_DOMAIN}
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
    - Navidrome:
        href: https://navidrome.${ROOT_DOMAIN}
        icon: navidrome.png
        widget:
          type: navidrome
          url: https://navidrome.${ROOT_DOMAIN}
          user: ${USERNAME}
          salt: {{HOMEPAGE_VAR_NAVIDROME_SALT}}
          token: {{HOMEPAGE_VAR_NAVIDROME_TOKEN}}
    - Piped:
        href: https://piped.${ROOT_DOMAIN}
        icon: piped.png
- Media Management:
  - Jellyseerr:
      href: https://jellyseerr.${ROOT_DOMAIN}
      icon: jellyseerr.png
      widget:
        type: jellyseerr
        url: https://jellyseerr.${ROOT_DOMAIN}
        key: {{HOMEPAGE_VAR__JELLYSEERR_KEY}}
  - Metube:
      href: https://metube.${ROOT_DOMAIN}
      icon: metube.png
  - Prowlarr:
      href: https://prowlarr.${ROOT_DOMAIN}
      icon: prowlarr.png
      widget:
        type: prowlarr
        url: https://prowlarr.${ROOT_DOMAIN}
        key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}
  - Radarr:
      href: https://radarr.${ROOT_DOMAIN}
      icon: radarr.png
      widget:
        type: radarr
        url: https://radarr.${ROOT_DOMAIN}
        key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
  - SABnzbd:
      href: https://sabnzbd.${ROOT_DOMAIN}
      icon: sabnzbd.png
      widget:
        type: sabnzbd
        url: https://sabnzbd.${ROOT_DOMAIN}
        key: {{HOMEPAGE_VAR_SABNZBD__API_KEY}}
  - Sonarr:
      href: https://sonarr.${ROOT_DOMAIN}
      icon: sonarr.png
      widget:
        type: sonarr
        url: https://sonarr.${ROOT_DOMAIN}
        key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
- Selfhosted:
    - FileBrowser:
        href: https://filebrowser.${ROOT_DOMAIN}
        icon: filebrowser.png
    - Linkwarden:
        href: https://linkwarden.${ROOT_DOMAIN}
        icon: /icons/linkwarden.png
        widget:
          type: linkwarden
          url: https://linkwarden.${ROOT_DOMAIN}
          key: ${SECRET_LINKWARDEN}
    - Memos:
        href: https://memos.${ROOT_DOMAIN}
        icon: memos.png
    - OpenSpeedTest:
        href: https://openspeedtest.${ROOT_DOMAIN}
        icon: openspeedtest.png
    - Paperless-ngx:
        href: https://paperless-ngx.${ROOT_DOMAIN}
        icon: /icons/paperless-ngx.svg
    - PairDrop:
        href: https://pairdrop.${ROOT_DOMAIN}
        icon: /icons/pairdrop.png
    - Redlib:
        href: https://redlib.${ROOT_DOMAIN}
        icon: reddit.png
    - Stirling-PDF:
        href: https://stirling-pdf.${ROOT_DOMAIN}
        icon: /icons/stirling.png
    - Vaultwarden:
        href: https://vaultwarden.${ROOT_DOMAIN}
        icon: bitwarden.png
    - Whoogle:
        href: https://whoogle.${ROOT_DOMAIN}
        icon: whoogle.png
- Utilities:
    - Checkmate:
        href: https://checkmate.${ROOT_DOMAIN}
        icon: sh-checkmate.png
    - Dozzle:
        href: https://dozzle.${ROOT_DOMAIN}
        icon: dozzle.png
    - Element Web:
        href: https://element.${ROOT_DOMAIN}
        icon: element.png
    - Frigate:
        href: https://frigate.${ROOT_DOMAIN}
        icon: frigate.png
    - Forgejo:
        href: https://forgejo.${ROOT_DOMAIN}
        icon: forgejo.png
    - Goldilocks:
        href: https://goldilocks.${ROOT_DOMAIN}
        icon: https://raw.githubusercontent.com/FairwindsOps/goldilocks/master/img/goldilocks.svg
    - Grafana:
        href: https://grafana.${ROOT_DOMAIN}
        icon: grafana.png
- VolsyncSystem:
    - Kopia:
        href: https://kopia.${ROOT_DOMAIN}
        icon: kopia.png
        widget:
          type: kopia
          url: http://kopia.${ROOT_DOMAIN}
