---
background: /images/background.jpg
backgroundOpacity: 0.5
color: slate
headerStyle: clean
theme: dark
target: _self
title: Dashboard
layout:
  Cluster:
    style: row
    columns: 2
    icon: mdi-chip-circle
  Lithium:
    style: row
    columns: 4
    icon: mdi-pi-circle
  Cloud:
    style: row
    columns: 3
    icon: mdi-cloud-circle
  Media:
    style: row
    columns: 2
    icon: mdi-play-circle
  Media Management:
    style: row
    columns: 2
    icon: mdi-play-network-circle
  Selfhosted:
    style: row
    columns: 4
    icon: mdi-cupboard-circle
  Utilities:
    style: row
    columns: 4
    icon: mdi-screwdriver-circle

