apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.3
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      sabnzbd:
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.4.1@sha256:36674664a94760ae934c09b1d97546a3e79a0f110edda88085e74778c26d68e3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsUser: 568
        runAsNonRoot: true
    hostname: qbittorrent
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: sabnzbd.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - sabnzbd.${ROOT_DOMAIN}
    persistence:
      config:
        path: /mnt/raid/media/sabnzbd/config
        server: ${NFS_HOST}
        type: nfs
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      sabnzbd:
        path: /mnt/raid/media/sabnzbd/downloads
        server: ${NFS_HOST}
        type: nfs
      tmp:
        type: emptyDir
    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: 8080
