# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: &cluster immich-cluster
  annotations:
    # required for seamless bootstrap: https://github.com/cloudnative-pg/cloudnative-pg/issues/5778#issuecomment-2783417464
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
kind: Cluster
spec:
  enableSuperuserAccess: true
  instances: 2
  imageName: "ghcr.io/tensorchord/cloudnative-vectorchord:18.0-0.5.3@sha256:267f6cbb32af6e109e138a143c7e9dd5d44d68433ec2303f0c30e745c788d1a9"
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 2Gi
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: immich-database-secret
  bootstrap:
    recovery:
      source: origin
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store immich-store
        serverName: immich-cluster-v2
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: *store
          serverName: immich-cluster-v1
