---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: immich-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        # app
        DB_DATABASE_NAME: "{{ .DB_DATABASE_NAME }}"
        DB_HOSTNAME: "{{ .DB_HOSTNAME }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_USERNAME: "{{ .DB_USERNAME }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"

        # cnpg
        aws-access-key-id: "{{ .AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "{{ .AWS_SECRET_ACCESS_KEY }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        region: "{{ .REGION }}"
        username: "{{ .POSTGRES_SUPER_USER }}"
  dataFrom:
    - extract:
        key: 4f1902eb-ac8f-471c-916d-b3aa00f019c7
