apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app memos
  namespace: selfhosted
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      memos:
        containers:
          app:
            image:
              repository: ghcr.io/usememos/memos
              tag: 0.24.4@sha256:c1518ccbeb1c54e54734ad2ca918c16b964e1b6aa2ccebdbac617ed827a80345
    defaultPodOptions:
      enableServiceLinks: false
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host "{{ .Release.Name }}.${ROOT_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      memos:
        enabled: true
        globalMounts:
          - path: /var/opt/memos
        path: ${NFS_PATH}/memos
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5230
