apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shelfmark
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      shelfmark:
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/calibrain/calibre-web-automated-book-downloader
              tag: v1.0.2@sha256:130252047eaf1e4fc813c73b3250e4b6f0f244f8d2de8d42bf5380bddca643b7 
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      cwa-book-ingest:
        path: /media/books/auto
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: &port 8084
    service:
      app:
        ports:
          http:
            port: *port
