apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shelfmark
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      shelfmark:
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/calibrain/calibre-web-automated-book-downloader
              tag: v1.2.0@sha256:8140f9513f89d8617871316cf8778e4a3d71957ca290a0e59d58caf3ccbb24d7 
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      books:
        path: /media/books/auto
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: &port 8084
    service:
      app:
        ports:
          http:
            port: *port
