apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shelfmark
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      shelfmark:
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/calibrain/calibre-web-automated-book-downloader
              tag: v1.3.1@sha256:80c8d561ae6ff9407d51f37266cd2ab44a38bf4df17834e42fde01982eefe6af
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      books:
        path: /media/books/auto
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: *app
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: &port 8084
    service:
      app:
        ports:
          http:
            port: *port
