---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app sonarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: sonarr-secret
    template:
      data:
        # Database
        SONARR__POSTGRES__HOST: &dbhost "postgresql-rw.database.svc.cluster.local"
        SONARR__POSTGRES__MAINDB: &dbname sonarr_main
        SONARR__POSTGRES__PASSWORD: &dbpass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__USER: &dbuser sonarr
        # Database Init
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: cloudnative-pg
