---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app sonarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: sonarr-secret
    template:
      data:
        # Database
        SONARR__POSTGRES__PASSWORD: "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
  dataFrom:
    - extract:
        key: sonarr
