---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sonarr
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      sonarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              PGID: "1000"
              PUID: "1000"
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__LOG__DBENABLED: "False"
              SONARR__LOG__LEVEL: info
              SONARR__POSTGRES__HOST: ${POSTGRESQL_HOST}
              SONARR__POSTGRES__MAINDB: sonarr_main
              SONARR__POSTGRES__PORT: "5432"
              SONARR__POSTGRES__USER: sonarr
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: sonarr-secret
            image:
              repository: quay.io/11notes/sonarr
              tag: 4.0.17@sha256:633e1ed7c43c39e2424d2a34f4627b8c2c2cd6fcac3efdac750bc8443b9f85c3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    persistence:
      config:
        advancedMounts:
          sonarr:
            app:
              - path: /sonarr/etc
        existingClaim: "{{ .Release.Name }}"
      media:
        advancedMounts:
          sonarr:
            app:
              - path: /media/qbittorrent/downloads
        enabled: true
        path: /media/qbittorrent/downloads
        server: ${NFS_HOST}
        type: nfs
      sabnzbd:
        advancedMounts:
          sonarr:
            app:
              - path: /mnt/sabdnzb
        enabled: true
        path: /media/sabnzbd/downloads
        server: ${NFS_HOST}
        type: nfs
      tv:
        advancedMounts:
          sonarr:
            app:
              - path: /media/tv
        enabled: true
        path: /media/qbittorrent/downloads/tv
        server: ${NFS_HOST}
        type: nfs
      tmpfs:
        type: emptyDir
        advancedMounts:
          sonarr:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: *app
          gatus.home-operations.com/endpoint: |-
            url: https://sonarr.${ROOT_DOMAIN}/ping
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        controller: sonarr
        ports:
          http:
            port: 8989
