apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100          # max weight = 100
          preference:
            matchExpressions:
            - key: cpu
              operator: In
              values:
              - high
    controllers:
      calibre:
        containers:
          app:
            env:
              PGID: 1000
              PUID: 1000
              TZ: ${TZ}
            image:
              repository: lscr.io/linuxserver/calibre
              tag: 8.16.2@sha256:51e42276a0b0755e11fc9a4f6ea51c4179080e66f7befe41e2ac9b55d57b4c6e
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        globalMounts:
          - path: /data
        path: /media/books
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: &port 8080
      content-server:
        hostnames:
          - calibre-content.${ROOT_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: content-server
                port: &content-server-port 8081
    service:
      app:
        ports:
          http:
            port: *port
      content-server:
        ports:
          http:
            port: *content-server-port
