apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      calibre:
        containers:
          app:
            env:
              PGID: 1000
              PUID: 1000
              TZ: ${TIMEZONE}
            image:
              repository: lscr.io/linuxserver/calibre
              tag: 9.11.0@sha256:1993e0bb0be26c031f579f162e34c1fb7ebb0ab3599d79c34a33ebd026ac0957
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        globalMounts:
          - path: /data
        path: /media/books
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/href: "https://{{ .Release.Name }}.${ROOT_DOMAIN}"
          gethomepage.dev/icon: *app
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: &port 8080
      content-server:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/href: "https://calibre-content.${ROOT_DOMAIN}"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: *app
        hostnames:
          - calibre-content.${ROOT_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: content-server
                port: &content-server-port 8081
    service:
      app:
        ports:
          http:
            port: *port
          crosspoint:
            port: 8081
      content-server:
        ports:
          http:
            port: *content-server-port
