---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app eddrit
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      eddrit:
        containers:
          app:
            env:
              VALKEY_URL: valkey://valkey.default.svc.cluster.local
            image:
              repository: ghcr.io/corenting/eddrit
              tag: 0.19.0@sha256:6b206913ed8a8d972f48dc1c32c80c0de912cc2f99d74569759bc10ac29c8a1f
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Selfhosted
          gethomepage.dev/icon: *app
          gatus.home-operations.com/endpoint: |
            group: selfhosted
        hostnames:
          - "${GATUS_SUBDOMAIN:=${APP}}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
