---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app eddrit
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      eddrit:
        containers:
          app:
            env:
              VALKEY_URL: valkey://valkey.default.svc.cluster.local
            image:
              repository: ghcr.io/corenting/eddrit
              tag: 0.18.1@sha256:bc5afa465e120efee7570b7e1eeac655263608e5d4b071dcac582a3165d35a7c
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: selfhosted
        hostnames:
          - "${GATUS_SUBDOMAIN:=${APP}}.${ROOT_DOMAIN}"
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
