apiVersion: v1
kind: Secret
metadata:
    name: invidious
    namespace: media
    labels:
        app: invidious
type: Opaque
stringData:
    INVIDIOUS_CONFIG: ENC[AES256_GCM,data:l3uk7HE/WZe/uRcnhI5/RAcS/59CfcCWmuTTZauX295Vww+9tUQ3+x7O+s1136zyadB8kiQCpWZxl5GV+K5oYlifL1Fup7SpPpg8wrIdc+PI1cagpolrU7Wy6R+0duNPFJPkolUrlSKXwu2Eq7LU4CIUvsM9UY3s4b6Ms6ItSAuqbfIqcrDFWu66OhK1IEIIo6Q1MEmNvdFzoG0nNkttTFMPMCBpiSvNKC5+h8DXLiD+3qB/QaqrG2eEHY5mDhawx3GS0giJmYjlsL9bAbqxezBANYkB8m3Is1G1ZM3Y0mmUGWDbolVSsT8D33zWcwfnkPIN5d2HwXgTnpPXE/Jc9Mnld3RNkm7Ojcm6b/ibtY2VXUwMX5GFGtSFXkuPlwsICexe7DesHNVRp8Z3Gxzmd8+q9VCUgTNISZPLPFM53be64wy+Bf/yIkGeH1SbFjM+cpB8DDBns+9U+YpJeSbZxnP/RjKZAdDSNhlJv4zU6R7Rdx3bpMU9+HLHBbiOhMc=,iv:sdhnl/MdhF4s3xznc7Shi6NT8bsDWFWUI+3IMaq7/Wk=,tag:uGZp9JszHVDMiMCXFItpgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ1d1dVU5cTV4ZlBHN2s0
            VDMxdjdtaEhkRVRTcndnMmU2S0RXYXRQZmd3CjhVQUhFbTAzcVdmWkZjNkJRaTNS
            cnMrS1JUakYwK3l4ak1uS0dzOUdHVWsKLS0tIFF4UG02ZXhJL2FMb09XNDFiTGRZ
            YVEyV0RZZ1RnNTk2OStXZVphdDBsV0EKMHEURCNIY544u+p0FYQ7r1khrpujEXaq
            JfTazsYnF7nn5hrsiER3dhyhzovzpr2WyFSiKLn2gt7KrWx9bmAVgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d3BYekVDRGJNYmdWNnVG
            dEp2NjhyYUFIMlg4MGtCUlFKOFlab05aRG1FCnh0OUU2ZTBHUm5OZjB6MnN6Q1VS
            TU1CN0VtS1RJaENmM2dsVjdEZENtYUEKLS0tIGN6SXdZOEdSbWg2K3lBOTVzUk90
            VlQ2Q3BXbWtUdUU3Qklla0srbGpJTVUKRLd0rlnFMI5gOMVckFRhjQec0ZChwRmf
            nTF3NE5fFeLUwVIOAZ6W2nZh3PhhqZLiuG4+JDTpRAIijH54xWJO/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T02:02:00Z"
    mac: ENC[AES256_GCM,data:DqoL5TCdk8ferSsrcaPl9vuQW8GCqZyp34Vp0kiakxEamkWu2cRQElEvwi/ThBbH+sXfqnq17ClHeXB/XPkdPOStG/66Pdvi2SgumR5n1pNaaR0hW23zn24MIG0UebqWtZnjjIXHnZhRCYqHmZmt2B44dytPjSh47UlreNgg+PI=,iv:pmZ7vnpPRAIEcnTPSf7IJscRGOcxO8m2dFfeuTQXzoo=,tag:f0+BN2WB24rFJ/KjaJ4xFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
