apiVersion: v1
kind: Secret
metadata:
    name: invidious
    namespace: media
    labels:
        app: invidious
type: Opaque
stringData:
    INVIDIOUS_CONFIG: ENC[AES256_GCM,data:hHaLf2BahF/OPwlAYiesLFM2whA13jRDg3xGRWhl5dRJDDIOEUCHtzfvFt4JpHaFEryh47Wn4Tvk5ZXPmHZV86vNUtYHO4Pg5OQG085qusTDNmcnD1aD6MZRLIxu3xoXMYgD1+GhMXnU2pIq7a13yFh7FMRH8iGIyZcomO2PL3N56sxhrKT5gEds1CYqVbFombKJGo4fDiHlCn15oMESbAC4rGrqVxg5Z4ASUzGlqzzTYlm/9l3HSWBWdignA6kQrd+Yr2YfSi+LCsvfaqDOZC/wFc4DS4OEC9Yxrw2qd8JArCbUIc+PEZiwB5GP0jkdD8x2o5D31Lu8yNDCHPJL2BeluUGTlWBEXuZCD3IJef+WExiSiNS07DxVdR6y879C6FLm1+wCJJPQCiInk8EPurKLNZObnhIZABI6hq9RR7oX4eufoRsWDZQiZ0HvRGWTgUbIMFTBiM7he5u5qCSusZu5dOhP3jdPWzwsCp8IWhNBwH0Ktg==,iv:ahCUeRBv+tC0fUwoejnFBfftj4RF1R9yJWfPVems0DU=,tag:YWXleO7clIo1a+BLNgGnBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ1d1dVU5cTV4ZlBHN2s0
            VDMxdjdtaEhkRVRTcndnMmU2S0RXYXRQZmd3CjhVQUhFbTAzcVdmWkZjNkJRaTNS
            cnMrS1JUakYwK3l4ak1uS0dzOUdHVWsKLS0tIFF4UG02ZXhJL2FMb09XNDFiTGRZ
            YVEyV0RZZ1RnNTk2OStXZVphdDBsV0EKMHEURCNIY544u+p0FYQ7r1khrpujEXaq
            JfTazsYnF7nn5hrsiER3dhyhzovzpr2WyFSiKLn2gt7KrWx9bmAVgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d3BYekVDRGJNYmdWNnVG
            dEp2NjhyYUFIMlg4MGtCUlFKOFlab05aRG1FCnh0OUU2ZTBHUm5OZjB6MnN6Q1VS
            TU1CN0VtS1RJaENmM2dsVjdEZENtYUEKLS0tIGN6SXdZOEdSbWg2K3lBOTVzUk90
            VlQ2Q3BXbWtUdUU3Qklla0srbGpJTVUKRLd0rlnFMI5gOMVckFRhjQec0ZChwRmf
            nTF3NE5fFeLUwVIOAZ6W2nZh3PhhqZLiuG4+JDTpRAIijH54xWJO/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T01:49:27Z"
    mac: ENC[AES256_GCM,data:VPYkzSzajBXgCU9E3ukYVZo0/J+zyYbq5MwGSBSfx3Y3CkiNa21lVKd1ciw+X86G/+w5deNRJM9lfGGIYqvdB/x/K3gXLrbotfVKQAHgr20pTjstj2bLwS05kJcGfHw/cqr5B9nEQbrR3aKx6BMOlS171IpYUreS6Rqt21u/7K0=,iv:aT8IOVAQpoCw+/6CxhI+/x7P4M9fxFtoasuztdoWxqg=,tag:BlP07133Vq6qzZjvciC+Lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
