---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: listenarr
spec:
  chartRef:
    kind: OCIRepository
    name: listenarr
  interval: 1h
  values:
    controllers:
      listenarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              LISTENARR_PUBLIC_URL: https://{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}
              TZ: Asia/Singapore
            image:
              repository: ghcr.io/therobbiedavis/listenarr
              tag:  canary-0.2.40@sha256:8df01f5d9801ab2c8c97fa469f229786be0ef63b0c08cf7e49694833a4ef0a93 
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/config
      media:
        enabled: true
        path: /mnt/raid/media/
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        controller: listenarr
        ports:
          http:
            port: 5000
