apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewall
  namespace: utilities
spec:
  chart:
    spec:
      chart: kubewall
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: kubewall
        namespace: flux-system
      version: 0.0.10
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    pvc:
      name: kubewall-data # Name of the PVC
      storage: 20Mi # Storage size requested for the PVC
      accessModes: ReadWriteOnce # Access mode for the PVC
      storageClass: local-hostpath # Storage class for the PVC (leave empty for default)
