apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewall
  namespace: utilities
spec:
  chart:
    spec:
      chart: kubewall
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: kubewall
        namespace: flux-system
      version: 0.0.10
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
