apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
type: Opaque
stringData:
    #ENC[AES256_GCM,data:yGbKQeeWW6pAm394z7CEPx7pJoR06pwNEVDt8k4zwtIIsai1xDe8V1laC1xGKGaQ3UTbfRpd+EFMxRujtbz7zyw=,iv:TD5JfNOwxVvbcaSY5O6qewNnIL4GavgBdPfWRhDOnxc=,tag:wr01FcavORN5F6+8aYF6AQ==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:6ovKhGX/eYVNQU4xQ4nIRnQGiwwwfsjSM16CplyuT93DHBB/cbXoEzT190JjeD21taRW68mU1SjQ/Y3GWOlLihqqIJqG6YD+sq2ShrJZUoq+bs6xLW7FVczXaME4ToxOxR7N8Ygg51OBaUCp1iEqyoNT8YMXofUSWYgR,iv:HUZQ95BowUP+JLPG1MbbEuxQu2sni5UeIGn32yOh6+M=,tag:blqN6MYt004uuMlWj7IIag==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:aCVQbvcDro8Q/1Ebta8PdDRyEIMiw1UXQftNo6VLaB1/7RAsOwsIrqvt738JQMN8Mf8piOTHKuC7OoO8ACV84BMF0n2JY5NKrGucTbGs5SehN9CHp1AcDxXdizPtm0snY6qg1dSa8rP9ChrSiE4Xy0Yxdlspc3DA1MZOVg==,iv:IHRomMMH1O9+ZX3jMOs5RFonpFmPENZjcFR2S9lKMyw=,tag:hQ0PEgMT8AZvTjmVvRtCLQ==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UHBmWG1QM3hkR2dzSGhE
            NDgyTVdjKzZSQmtQYmlUT291emg4OHZFbkg4CjdQNnp0d0R0RS9QTkthRmF1VVpF
            OTMzenlqTEY0bkc0SStreEdNc3FMeFEKLS0tIG9qZ2xsRCt3NHNjMmd0cCsweTQy
            TW01bEVnWXlRSWZEYS80bFFHMS9rTGsKTsLvoqhWZfQYNwdnEMhx9jG0933mEHAf
            jgiWCd2i3dlKyWx+XD2xyoDT2pjlXzsIYbI/IdVO7+wFvULyV244gw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSEdVSHdVa1ArOVNwOStk
            Z3ZNS0FrS1d6NUFESzYvaGNhS082UXVKR1E0CmkvaEtXby9xeVRLZ24vSjVnN25E
            WkdjdERtOUVXa3ZwRDB5cy9tWXVoOUkKLS0tIFdMeDNXdmMzQ01OVTVGalM3OEpP
            MFRsdXBaOTN4UENLdEw0bXVEUUN3OVkKDZuyyDvecttIFPGk356z8ysqAdW7oUkQ
            YPbQOTLSUIy1bsE6xm/WLP770fVjbsQo/bTCPY0UH1DVhgZ/So1oAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T01:45:53Z"
    mac: ENC[AES256_GCM,data:MDb7g1pPxzDNCic6d5fgAraOs5vu8MVTNdX/I/ZZRKKmXXECY6X9xWkXVHloNkSYLsX6HvUPxnuX81E70HqIHRTVF3Khhgn45qKKhKYppk0GBUsoBHIqwU7T6WNum6oy+H2ossZLPWfIxMqCGzkXogxrPc3nHtso3y0HUkHJMo8=,iv:uVW+0Z/X2YkiYFy2DMu6ncmh/sxOr23lZKM2T87ODXA=,tag:/De8GXkGt0f7oQjqzS1jXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
