---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-backup
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "@daily"
          ttlSecondsAfterFinished: 43200
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          enableServiceLinks: false
        containers:
          main:
            image:
              repository: docker.io/prodrigestivill/postgres-backup-local
              tag: 16@sha256:c577b0d62673d4dce0471c75d21e3e08e4e9789903f5a3fd6613c410442e9670
            command: ["/backup.sh"]
            envFrom:
              - secretRef:
                  name: cloudnative-pg-superuser
            env:
              - name: POSTGRES_HOST
                value: cloudnative-pg-r.default
              - name: POSTGRES_DB
                value: "immich"
              - name: BACKUP_KEEP_DAYS
                value: "7"
              - name: BACKUP_KEEP_WEEKS
                value: "4"
              - name: BACKUP_KEEP_MONTHS
                value: "6"
              - name: BACKUP_KEEP_MINS
                value: "7200"
              - name: POSTGRES_EXTRA_OPTS
                value: "-b -C -Z6"

    service:
      main:
        enabled: false

    persistence:
      backups:
        enabled: true
        existingClaim: cloudnative-pg-backup-pvc
        globalMounts:
          - path: /backups
