apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-backup
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      postgres-backup:
        containers:
          app:
            command:
              - /backup.sh
            env:
              - name: POSTGRES_HOST
                value: cloudnative-pgvecto-r.default
              - name: POSTGRES_DB
                value: immich
              - name: BACKUP_KEEP_DAYS
                value: '7'
              - name: BACKUP_KEEP_WEEKS
                value: '4'
              - name: BACKUP_KEEP_MONTHS
                value: '6'
              - name: BACKUP_KEEP_MINS
                value: '7200'
              - name: POSTGRES_EXTRA_OPTS
                value: -b -C -Z6
            envFrom:
              - secretRef:
                  name: cloudnative-pg-superuser
            image:
              repository: docker.io/prodrigestivill/postgres-backup-local
              tag: 16@sha256:f873bbfb406db633ab879628b11ef8092279639c467a2ea5f5bfa08b776252fb
        cronjob:
          schedule: '@daily'
          ttlSecondsAfterFinished: 43200
        pod:
          enableServiceLinks: false
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsUser: 568
        type: cronjob
    persistence:
      backups:
        enabled: true
        existingClaim: cloudnative-pg-backup-pvc
        globalMounts:
          - path: /backups
    service:
      app:
        controller: postgres-backup
        enabled: false
