---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: gatus-secret
    template:
      data:
        ACCESS_TOKEN: "{{ .ACCESS_TOKEN }}"
        INTERNAL_ROOM_ID: "{{ .INTERNAL_ROOM_ID }}"
  dataFrom:
    - extract:
        key: gatus
