apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
    namespace: utilities
stringData:
    secret.yaml: ENC[AES256_GCM,data:Aht/Pvon+5a6BiFnSSlAEDtrcsAc6s6973z8lL5pruGz40HAcuBIC2rOwpr9w17VXhZouSQkulI0nYp0IxkEZBZ/8nYFN37IwmiEGv4cs0TdIcNgpmCEOBzxZEzqlQN+twZViFuoftODdk2BP3CrQxTICqr+ynsDilLWhPNy4xEvdOtnkC/Wm2uWON28JcvbM6XPw7xxPYTYIfCP1stSMmlkpaB14HUlyjmwyyyKxr5fbJX7109LLGys8/ig7jC8bM6a/M3QD5bSn2YMvuaFYrI51JJCZYthdVk9ev5m0wWetvA5f7zidWP3d5MoiLdHBkMmEHqvu7j5uG/TRnks5HS3hiN+0UMGXwlZrNhGoKUVgiACX++ceETXUVUuUWukXqZ9Pzm0GeVXH+Y3HackE9ipL/D4lodGivqt0ew2Fjxn/MimWPNJ7zUcbh9K9Fu8KVID/jXhGigRv+qQArY=,iv:tdcCAM5mehN2iZr9J0cI1/sFKa3CtMI1e5zTLt+FAio=,tag:xvs6ObkRSx1XvM/qLF3fTw==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaUcyZE5ESFM5OU9RdzhM
            cW5wdUNIMjQ2ODhnaVlZN2dHY0NyRnFETVNjCitoRVM3MkgrTldzVjY3b3V4c2hq
            a2E2ZXJGT2F3UVgzbFRXcjBSWlI3N1UKLS0tIFRvVldQZWpOSFdvajJWdlU1cHJu
            MytYTFBVN2FjM1Y1VnhYaEtaSzgzSncKi4OeLDasOZh0AUhgukrVEbIyBKhbf22B
            B3adR//PfQfLu8dF7DWh0g3kDYnr2cbJRMffSD8yNAs+zcTtFq83HA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVU13MDVVS09qMkQwbUZD
            VWRzcUw5Ri9XcEVJZXZ3cE9MQllJQlIxamxvCjg4amxkbC9KMTYrKy9lZEhKTTgr
            cnZBRWRYTUMvMmsxUjUwTjVjTU9Md1UKLS0tIExyRHZNMXRrMXc4ZWNLMzhpZklP
            ZmNkcURIQVFUK1dMNS9zTjdSM2VJR1EK+wk7tm4ZnSS6Hvq25U+E1vfJTBKGG+DV
            fvlmIQKp10LWsDUYEzfOLFzkZFSsan9JuEIajZku24MwYAnGUnanLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:32:04Z"
    mac: ENC[AES256_GCM,data:IyQjIazPYgFMCw5ijeRVn6Gk+WMReVT9zKel0xMzdGVsz/0VPinSiMlMweolDS3VhrxY5OEKMrV+QYf7uR3dXyDdJqfN/IAGicT5o3BXg/nxjzSixT+EpQYt+/RptzBAPR5mJDOpbC3zsmKeVRVd0uZwFloeu0aTCAfRTEdDaf4=,iv:aUvanBSfYwUKnPkvqGCXRkjb5xaojGafCam4NL0ufUg=,tag:k2WENWrFTP2jGWFbjUi1vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
