apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      prowlarr:
        containers:
          app:
            env:
              PGID: '568'
              PUID: '568'
              TZ: Asia/Singapore
            image:
              repository: ghcr.io/onedr0p/prowlarr-nightly
              tag: 1.25.1.4770@sha256:36eaef3d76e8d80935119305c04fa785605bb09173fbf067783d71eb6e531c3b
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsUser: 568
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: prowlarr.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - prowlarr.${ROOT_DOMAIN}
    persistence:
      config:
        enabled: true
        path: ${NFS_PATH}/arrs/prowlarr/config
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: prowlarr
        ports:
          http:
            port: 9696
