apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app handbrake
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      handbrake:
        containers:
          app:
            env:
              TZ: ${TZ}
            image:
              repository: docker.io/jlesage/handbrake
              tag: v24.09.1@sha256:a932aa8b9379d30c9ae2e735619d0684e8846b9191937bd085fc37fb069bfb9b
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host '{{ .Release.Name }}.${ROOT_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: handbrake-pvc
      videos:
        enabled: true
        path: ${MEDIA_PATH}/videos/handbrake
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5800
