---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app apprise
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      apprise:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/caronc/apprise
              tag: v1.3.2@sha256:1aafc2118b6eae5d70d17831d9a8a52adee7104fd6f2bb018e6421664699c903
            env:
              TZ: ${TIMEZONE}
              APPRISE_WORKER_COUNT: 4
              IPV4_ONLY: true
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          apprise:
            app:
              - path: /config
                subPath: config
              - path: /plugin
                subPath: plugin
      tmpfs:
        type: emptyDir
        advancedMounts:
          apprise:
            app:
              - path: /attach
                subPath: attach
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
        - '{{ .Release.Name }}.${ROOT_DOMAIN}'
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        ports:
          http:
            port: 8000
