---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app apprise
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      apprise:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/caronc/apprise
              tag: v1.4.1@sha256:25e0577915c2f06233ae1dce077f05c0fc9ba4f0ea89de5aee18a32b2ee9a75c
            env:
              TZ: ${TIMEZONE}
              APPRISE_WORKER_COUNT: 4
              IPV4_ONLY: true
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          apprise:
            app:
              - path: /config
                subPath: config
              - path: /plugin
                subPath: plugin
      tmpfs:
        type: emptyDir
        advancedMounts:
          apprise:
            app:
              - path: /attach
                subPath: attach
              - path: /tmp
                subPath: tmp
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: utilities
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: *app
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8000
