---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scanopy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      scanopy:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "18"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-initdb-secret"
        containers:
          daemon:
            env:
              SCANOPY_MODE: daemon_poll
              SCANOPY_NAME: scanopy-daemon-oxygen
              SCANOPY_SERVER_URL: "https://{{ .Release.Name }}.${ROOT_DOMAIN}"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            image:
              repository: ghcr.io/scanopy/scanopy/daemon
              tag: v0.15.3@sha256:bdad14bd39de3b427db7c755e75b839db08dd63146482d7109ff8a666d99baeb
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
          server:
            env:
              SCANOPY_INTEGRATED_DAEMON_URL: http://daemon:60073
              SCANOPY_WEB_EXTERNAL_PATH: /app/static
              SCANOPY_PUBLIC_URL: https://{{ .Release.Name }}.${ROOT_DOMAIN}
              SCANOPY_DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-pguser-secret"
                    key: uri
            image:
              repository: ghcr.io/scanopy/scanopy/server
              tag: v0.15.3@sha256:423f0448ff2b5d852db816fbb748b72e2e6478c13fa079a6dfa263ac0a2c8987
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    persistence:
      data:
        existingClaim: *app
    route:
      server:
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      daemon:
        ports:
          http:
            port: 60073
      server:
        ports:
          http:
            port: 60072
