apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-secret
    namespace: networking
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:OQlCcxrfRdV/Ib7lXxfFCtU7w9kuPPPfXq/M9SHUbTKQMOzOR4HckqKZXWl/3qLJBQD63BxMFwriQ3NfNIfQE6IVg+P1kllwq97KPg2G/jMOPY2TAzb3jV5aZvZERTTafyIxE/vVtHl9sXKCgYoKsPBYLKwveXKvbu+gyTuQqDgPxAJlUSULPskgvTLVctlpblzl1WVh486AO6+LNXHy4+37,iv:VA8/JlF62p+rHZ/KQTSdl0jZbTeXDqAQE8Cr+pErjMA=,tag:+4qy9JZPBotNVxdEBNE+cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVWJPRmZjY3dJOW9iZjQ0
            blpVcnM2Tnl2Z3BHZEx3UWdhQWxYM3d2c1JrCnJmTWk4OVlETlFJNVNjOHJJODYx
            OU5QNUpRdzVPZDVDK21qVGNpbFVsNUEKLS0tIFVsRVpFWENqVzg1SXE3QXdMWkJt
            QkZxS0llV25jTHVkTFFMaGh5LzNDazQKUK4RnkZmUbcLj3H81PDgjqKndzPd/aPO
            ZWvNQG1imrYspGvHKs+nASikyB1hiilAjFJSNRnrmxKL5AkAbtmDpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWkJ0UC9MaHhudnpJUFFl
            VGlxQWxBM3dNZUpPUi9uSkNyeVFORldMUXgwCkJFTno1OWFzTU80QXhuZUdvdFpk
            ajhlMzRRejdwS3d2VHRReWNPTk5vNTAKLS0tIGFBU2JlbVRsZWtnc2JaRXU4bWha
            UEdRZHpsakxGS0lUemlwZE9qUU1PMzQKYmd8SNI5xExH7OFx76jARJ1VmlLSk5aJ
            7XU5JFqO8O8r3AiAi82BdftBvJZOp30W0yZo7wlmFSdeF8+eImFruA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-27T02:11:06Z"
    mac: ENC[AES256_GCM,data:RnrqvWIEMk1Ivio8bSy+EOWTsBlmos2N+5RqstMNs8szRkoFGCgDZKV18pI7w2ExLPV4kOv3miAxwwt1OAPp40/9weQ9q0PwVuuTZY8qaxJN6tnBlLTgiF9uI3ARbjlPq9CbXp/AG0wGUqg/U1rj0htcCD9pLs/zsAnJUUSVeGw=,iv:XZ/MUm0925+lq6UYctPbnlQlaVRH3OpeRU00Xycvj4M=,tag:zu5w9MjLwlj41QBS8K0kTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
