apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secrets
    namespace: utilities
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:PSP7UUQFSw==,iv:l+Nk715Sobi1jX4H5mdoggSX+mMCYjz3xpI+Zyse9k0=,tag:KC9mr1a0Lfjz2w06x8lSDQ==,type:str]
    password: ENC[AES256_GCM,data:9rLRBrT5RMaQArsifFicPIV+Se+87LCd,iv:2qjAX8bMjeeVCYOA3+FBp67IaEeNccXMh93m1kUA+bo=,tag:wstDHsVQhDgxXo9xJCr1Jw==,type:str]
    email: ENC[AES256_GCM,data:YXp4BU0KZHzpXGrF+hUTdnzvoT8B,iv:+nJB0Ok1WjHd64Fs77WvGUcTWoqOq3bpYlO5KNlPTWE=,tag:SDYE88M5EgnOLL3DY4Jrgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva1BneFFsM2RWT21RblpD
            NXdObXJPbE9XelRvQUVRWEFEZSs1WnBKaG1vCmlMQy9wckJtUUV5ZHJmWjFFcFhK
            eWNmb3ZLb0UrOURlbUcvUWdVQ1RhYUkKLS0tIEpmMUc3NHhmV3JaOUl1ZnlSVFlZ
            dnY1UWl5d2RDMFByUXBDSWhYZFRIMU0KetcE4q/JAF8x1jmJq+yddE5WvxGr2yFR
            aJLhol8vKpoFzIfgJYmQGkW5KQvT5mOxzrIEfAuS0iDcmTE+2moD9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNzBPVHQvclRrRTNzTVlp
            TGc0QTBEQXh0czlZY3N4ZWpqbjU2a01yaHdFClVtNXNndW94TksyVkhGeHVxZTQ5
            Y1prSEVJMXNYZUpFanBPamgzYms0SmMKLS0tIHhrenNCMjh5RlluUytNRy9YNHpo
            WTlWUHZicnZ0MzdUUjg1WENMZzNhYWcKD+in86M8OUy8Ltk5lAIrZRJOrceZ6hqq
            egCKSAVMOwIzgHab7NrEDojZRZi5y5jzwhG2vYidJTLUlxpT3sjs6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T04:26:46Z"
    mac: ENC[AES256_GCM,data:iwjOTZFH4oAU9Q/QfNro7EroYQftjVbR56kp1KPmls9IQRF5iLmEMivdJASj/67e7xaEhWb0J3BtmX289BY9h7POSZnzq+tY4ZRbBXAxDme3EBwXibRw4kdm881BqKycvMAZ3OQOKQ9VML25CdnzQaD0mIWlNwjI741xbvV+mZA=,iv:MnwRqqdMZxsVkwDi+V0vRCDkaqyowMQamViw6UusgOk=,tag:inHMP1KOJXNq0Kd0LLY14w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-config-database-secret
    namespace: utilities
type: Opaque
stringData:
    NAME: ENC[AES256_GCM,data:8PER9EFCJUMx,iv:LfzjISd3SV2Ted8hQQ7SWiaKMIBbWMzkI41adXI7A6A=,tag:OBhK+QEvwgraoZUS/P6NDQ==,type:str]
    USER: ENC[AES256_GCM,data:a3H9lTA7+Q==,iv:rLnH2GRC2skpHiGMxHThtQtBqt0zLSwBPqGQqC5wBqI=,tag:Vk+AG8yfNUsvfvc0Jb7oCw==,type:str]
    PASSWD: ENC[AES256_GCM,data:c71RiDJQfuxR4xSPVo+3a3lNWGtSLFTX,iv:TVE2xurSZ/v4l19cogs4QKmDmv3m93sKln1s0CT+7tA=,tag:sM9xVXJJVx14y01TcRV+ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva1BneFFsM2RWT21RblpD
            NXdObXJPbE9XelRvQUVRWEFEZSs1WnBKaG1vCmlMQy9wckJtUUV5ZHJmWjFFcFhK
            eWNmb3ZLb0UrOURlbUcvUWdVQ1RhYUkKLS0tIEpmMUc3NHhmV3JaOUl1ZnlSVFlZ
            dnY1UWl5d2RDMFByUXBDSWhYZFRIMU0KetcE4q/JAF8x1jmJq+yddE5WvxGr2yFR
            aJLhol8vKpoFzIfgJYmQGkW5KQvT5mOxzrIEfAuS0iDcmTE+2moD9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNzBPVHQvclRrRTNzTVlp
            TGc0QTBEQXh0czlZY3N4ZWpqbjU2a01yaHdFClVtNXNndW94TksyVkhGeHVxZTQ5
            Y1prSEVJMXNYZUpFanBPamgzYms0SmMKLS0tIHhrenNCMjh5RlluUytNRy9YNHpo
            WTlWUHZicnZ0MzdUUjg1WENMZzNhYWcKD+in86M8OUy8Ltk5lAIrZRJOrceZ6hqq
            egCKSAVMOwIzgHab7NrEDojZRZi5y5jzwhG2vYidJTLUlxpT3sjs6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T04:26:46Z"
    mac: ENC[AES256_GCM,data:iwjOTZFH4oAU9Q/QfNro7EroYQftjVbR56kp1KPmls9IQRF5iLmEMivdJASj/67e7xaEhWb0J3BtmX289BY9h7POSZnzq+tY4ZRbBXAxDme3EBwXibRw4kdm881BqKycvMAZ3OQOKQ9VML25CdnzQaD0mIWlNwjI741xbvV+mZA=,iv:MnwRqqdMZxsVkwDi+V0vRCDkaqyowMQamViw6UusgOk=,tag:inHMP1KOJXNq0Kd0LLY14w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
