apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-pv
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: ${NFS_PATH}/forgejo
    server: ${NFS_HOST}
  storageClassName: forgejo-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-pvc
  namespace: utilities
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: forgejo-nfs
