apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prowlarr
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      prowlarr:
        containers:
          app:
            env:
              PGID: '1000'
              PUID: '1000'
              TZ: Asia/Singapore
            image:
              repository: quay.io/11notes/prowlarr
              tag: 2.3.0@sha256:46e0ca1a9117eff5c0b09029a93244d1e81828d562ae2153631a748e88394988
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
    persistence:
      config:
        advancedMounts:
          prowlarr:
            app:
            - path: /prowlarr/etc
        existingClaim: "{{ .Release.Name }}"
      tmpfs:
        type: emptyDir
        advancedMounts:
          prowlarr:
            app:
            - path: /config/cache
              subPath: cache
            - path: /config/log
              subPath: log
            - path: /tmp
              subPath: tmp
    route:
      app:
        hostnames:
        - '{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}'
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        ports:
          http:
            port: 9696
