apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: utilities
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:qnzx3m6DDfsSerzPw3VoAmwUflhqBCHVK7cpS5gQQ98CLdm3Nzs66xGV4Z/9mXFDWj8dYjmYIuMgJcESKq9+2/5rou5NhI/MylxKvYvCum/QiEEMCf9vPh3KEbGQ,iv:yfWUfAgJsv0Cj2X3HMZFxn5MMQuxqN0gdL6lIz3ZzTk=,tag:SjnNqykgYCPqoIUaLEr1zg==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:6tdDNqm5sI+VGnR0+NZupT9CktvFnHONS+gKlAmUK64CCUMORPU=,iv:NUiSzbS4TP5PD5MzQSSeEu0iGmp8egxSO9o4dnAzzHQ=,tag:bSmXyxAybGzbcc8h1TBGaw==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:52FijgLU9mj6AftU3MdMfzKEw4Fg3NbH+rcVWeh/k1q3efA7cdKA,iv:NlHpfK5ApcPoDXhLSIGq33UPcSkHZwQpJAi30/4O5lo=,tag:pmKwLqtD8UNIN3qJLzMDAw==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:OVuv2bmZyrur2EJnQINL6Beyvg0XEc4BuxyJpkEObiO5AJgW+3fS5g==,iv:DxsAwYnBL9RAvrSKRssdBXg686q1HsHJsa7hs4OMu2A=,tag:sEI5/9TxP2Juu8RQPLml7Q==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNForb082dG1vdERHNU9s
            TGJ6V00xdzIwZW9NRG5laWNnbWdKQVAvejJFClpIYU9EeW00K1ZQMWdaMHZ5Z1ZD
            aStqMjhIT0xvOTByVlBEclozUEtpdW8KLS0tIHM0Nzc3VjJUcnJkM1c1RSt6M2hq
            TU9hNjBiM3JFbWtNZUJmUUl0M0VCejQK1j1oZMBa1MPxWsug8H7YP8d6Jm636fCs
            IczwWSjJYYnU1VXuS5AovlzAfJQzn61ahjBIBCrvRpS6f5XOATuwLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ako2TWtRbnpIaFoxOVRu
            dFhVSmVQcWNFZmpSTCtSN1ovQURqMGhkcjNzCmIxcVBGVlYwQXNVRmxIRVMwbFp4
            RWpnM1UwZFFNUEdyODJYSDVMNklNKzQKLS0tIE1PNWsrWkhIL1ZEcWZScUJIYkV6
            ZVpRYkx1NVhEL2gweHJwdGpqK2tFdmsKRIPxTwafZDAob05BTULCt6SkXK4RJTGx
            4hb/O9fkkqmFBes8creJtx6i8EECCDoq7L63EshdLhv+NXdT8k3SaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T01:48:41Z"
    mac: ENC[AES256_GCM,data:0KxRpf0hmexxqsb3vIIiqnlfoKivDQnqf4MKjTCad8B0e/hqrWgrXS0NsxQ0Rx/pHZUFYPU3VFPS73xYxpZkOKDdW2kBmHVGrhMgOjMOv4B6id8D5yPs0oHMwrGRHw0Zxb+ObkSa1UnrUVCLUQChBdscOZhvjzt+MJgZ80JjZfY=,iv:sFl7XtO5DQgXYXmazpetTzKbU0N7Kec2UR5qksLJOHk=,tag:oUffNS3GICev4ZA5iJ3/9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
