apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudnative-pg-superuser
    namespace: dev
stringData:
    username: ENC[AES256_GCM,data:qQDM9CABVac=,iv:z1MnZF14kzOBWUE8sxDoY9E38Ix7IyReJPJNvHY3yaw=,tag:mFg/V1WlIWbRxcPAr/GWUA==,type:str]
    password: ENC[AES256_GCM,data:WHHKVisDH0MD4A==,iv:dTCKY7q0b8ZWh4hS6F0fIqFL8GuOhhBeteDhTtSq1RQ=,tag:lmU3C2qN4jSJFCJOAAbf+w==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:NFYLecKEtD8bVvEfa+Rf9jPY6jsCARkt9w==,iv:ieX2lhfVxHEb01rN0v1f+SwSy5kCj/pbDL8bF7BTYhk=,tag:Wmr7lkF2AC/p+8XO19iYZQ==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:Cs6OSTLaqgCiBDE6geiC1klr1NCjGEZuAM+ILPgvJw==,iv:HkZtxcR7kJh/XrbCtMlnUBDm3HVbcas8cyMf+g/mM20=,tag:Hgt9gMQDonhTxnoCnOLR+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R0I3NGtHWERwWUJnT09i
            S3V3L0E2T0FFZUMzNzRxcDgzSkNieTRSSEdjCk5vd1h5ZEFrMTNPeUswYjc2dG4v
            QjNkREpYR0xlaklBMHNqcnl4TjlwOXcKLS0tIEF4bWhCV0plN1pyKzlVRmJJcyt0
            TzVXUkx2TW5GeDcyVjc0WTJEVVQrS1EKLjpqKyH5XHT5idDucMdRUb2VWVu1HPsP
            /HkCjJ6B3WaZ+kz0YP4bNN6CJPhPUZm/RnLjz/i1yXf9Ms6ybvyQrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQmozNms5SmQxcHBCL0VO
            VGVsc25EdUdDV1AvSW54ajFKM2FYeWRRYkhrCmJRWDlzUGpEY1o1MjFiSTNDS2RQ
            MFc2WlZDc1NVOUtTV2grK2VpTEd0SFUKLS0tIGVqYUd0d1lMVDdqKzFOcE9Udjdl
            alBHZGpMQnlHL200Z2RxR282cUprRHMKbJzzXiRawhekKdXmt/0LT31dcNZmULOI
            oox1LaXbZZrAiXCpGvr9nSDrHMbtAh4+vStl3UrzTG+JL0+vlkDSnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T12:40:38Z"
    mac: ENC[AES256_GCM,data:tI5AYBuFIcWPfGCl2x05el8bh+7gFJ4eB119IrjHGA5bPTQWhlzYDEHhJth4x7FqKWMvYEcN9MSWDJayzgl4tMuJBUGBXvSNCC1RQFNbFvyRPDEUaBSM4ttpL5uBC7bF9QkEGXRJzQU37OT9KTDtRucmwzOkxWw221S3DxvhRQY=,iv:QyYQFfblLqS5wMFTIfYqtdHcty6TfseFRLc8h/m35NM=,tag:JRV5GQfUCGhN8vpGMbwihQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
