apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudnative-pg-superuser
    namespace: dev
stringData:
    username: ENC[AES256_GCM,data:YI25+hcEnMU=,iv:jGDnSuU9aOzqOMpmVE4Zjmc6su4xeZZosnetZKXoYh0=,tag:uLpIA96iYPWNUHa0o4h3Lw==,type:str]
    password: ENC[AES256_GCM,data:SPfYKIbX0QgLEw==,iv:GgRbYdWGIhE2QJ0r28dfnBcptVjzf1OYDdYmLuL7qrE=,tag:X6wGzw5Jv6b8dI7ynss9SQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:dnRiTyh7I8I=,iv:I32V2Sifd++6AtNb0fnhl2MmK6OF66fOm3FIOnvh/g8=,tag:HNRrOnaP2HjwYYPegxoz1g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rUOjeXPm9Nvg2Q==,iv:sUHqW7pAhvN7M/W9VJJse1O+3YVmEUxqcV2JxEX6vEc=,tag:8atd3qya6omgcFXTYiy36Q==,type:str]
    minio-access-key-id: ENC[AES256_GCM,data:CzOd07LzdgxKWPScl3NBpoB0fUQ=,iv:GBki5nyMa3tivo2T1kb6DVw16Gyx9BERuoPWsJbsz3E=,tag:NMTgv5Ikhj/u17Ud++xGwQ==,type:str]
    minio-secret-access-key: ENC[AES256_GCM,data:kHRLjPWJmJcNN8KdxvZd3uJMBBZcsQ17g7TYwBEQB7LUXWpuxPv8kQ==,iv:B+F3PTYDMrQFHDS+Ml87x8e9fCDrLx6qQf7oRU0eKEo=,tag:dRFxHoa93cMQI8OfuAIrqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbnREVG9lZm5rL0dzV2NN
            N0xIYmwvS3ZlekRPNGdpa2puVmZMb2N0S0NjCndCcklTdHNtSE9ucmxZb21NZDJq
            cW1BQXZTam9WRmllQUQ0dWVyUUV5OU0KLS0tIDY1NHdkTGNWNUU1WmV4bm4wZGlI
            VXF4aWprcWFaU1dtN1g4S1p1VXNWRHMKDDKZHgXNWGvnuzrmccApluoGWfht0CLg
            ngu+QAL8IGGwBwJCDZM2xyahGGcvSdTNKvC6z5zbjpAW7Cs6XhwYQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeXd0bmxIcno0TWZpaU0r
            dmZ2RTFRTSs5K0dxQjgvZWZiNm1pYWFSNTJRCnNxNHQ5MnkzOEhsZStlbEl1Nldp
            SW5nQUpUNGVrMSs3QzJPUnI5dmlEazQKLS0tIDNhMkRsWCtTVHYxQ3h6M0tYQXV5
            bUJjUEFXMkZBcC85Y3gyemtkRHZwbDgK0wfOE8ugawkOTzoHRFexPMc6Fq1TwvnA
            5e21h8mkCipd8frt5AA+M8UhtWxgZ5lT80RUZbRGRZKfhzOEotqq1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T05:08:11Z"
    mac: ENC[AES256_GCM,data:XvGiH1hawnhC0KFUBG27GO5cdgcIER5MjFAB/AGvXuY1YYMc4MvwLM0Ij7NQSYrecU9auLjy0l/AjBNau6Or+diNhuuiR3HEcWZMOxc8t9nVsVCnH3vJ4Khpnj8cJoMVSTCfS1Bwg+nd3OERd5AFjN835y6fttWjwv8PD/NZOWk=,iv:JGAWRFXAexugekRgQus3CF29WnsdWDTB1xhZi6hkqZQ=,tag:JPs0sKhHP9dZv1ZAW3p4sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
