apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.4.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      radarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              PGID: "568"
              PUID: "568"
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: radarr-secret
            image:
              repository: ghcr.io/onedr0p/radarr-develop
              tag: 5.12.0@sha256:87c788eb150218172c951e8f37ec60dbc5a3033c909f1467c3bbee88e5a51f3b
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsUser: 568
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: radarr.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - radarr.${ROOT_DOMAIN}
    persistence:
      config:
        enabled: true
        path: ${NFS_PATH}/arrs/radarr/config
        server: ${NFS_HOST}
        type: nfs
      media:
        enabled: true
        path: /mnt/raid/media/qbittorrent/downloads
        server: ${NFS_HOST}
        type: nfs
      sabnzbd:
        enabled: true
        path: /mnt/raid/media/sabnzbd/downloads
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: radarr
        ports:
          http:
            port: 7878
