# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: downloads
type: Opaque
stringData:
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:SZ90pb5863QFKtijlc5uV+dLYrd6ZFqLyCpcsI+Bto5gDsYG,iv:fQ8/o2IP3bHdXOw6uupjUE+cyPIgdgPLYf7E2RicClw=,tag:q1FG7lvVwKX+W0l6WbRHfw==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:X+c38w==,iv:rnpeV4MWiwgDDIHmOb39kE689Q32wfpqI09i7Ke7jrY=,tag:gUF9uqx3st5KuDlbcXnTZQ==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:sPnaB3kh,iv:fWZ8W7HT3BPBEUuHvrHWC8AMMsPbQ0hWhVFTNGVfFOU=,tag:inPp6Z7DrQf08HdGnilOkw==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:diLLdMLsyk15dVM2YzjyMdphsd8=,iv:geTKcbnl9W0Zc7S0fxoNBFMtGPgx+a7yoapy5Fl+PQc=,tag:a938VHPp7Z9WHYPaYZ0+bg==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:pPwsarao,iv:ppbpbswRqf2r/CnEVIZbIGZfTOI7aXhf5sdCKO6f98w=,tag:4vV9BoEuX3sX9q+xH0t9bw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:x+979CBe,iv:7OSnBZWyw95fw/9VJMbzZPg2aAdRrRRkimUevdUG+rg=,tag:8SV4ctX8tnPHugtlfnyB1A==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:f6jJtyDlt+EkziVDds7U4rwsY4DupKGuHRMBOe467UXAnIcG,iv:nPPdD4opxna6Em5CHLQi136xZ5sr2jBcaivB7OjUbZk=,tag:WehX9I/VlRGOaFggiIJNIQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Q8bTkGXYaZ0mh+JGKYkvviSPWJc=,iv:3GF6aEwWIkI4dqF9orUjOFmdrn4zerkW4jMsrYTjCRo=,tag:rEGGumxw/Tp5z7PfppaKCA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:su6OchSL,iv:xT714D2zIaYA9xRR9w/pKTSkwIjw5fPLnZg1oUa52zc=,tag:jtCDL2Jz70kfRqxCDuWBRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-04T05:26:02Z"
    mac: ENC[AES256_GCM,data:NNXl6mcjwo2fdjfihmtVD2OgerUBEpCE4UXrtjTOwRaL3b4OfKGwRDkjb4dxJxPK4Z+fxp1TK5x1WDSqD5LFn09YOdQeDgbjvRiWZHlLJg2BxqgDSuZKM/+7U17xy/IDQs3+aIdmLfQyZk7ALQz5r1ZsTPskf3sWeaknArXwbyc=,iv:CT8ykakWk0TbzL1/u47mfW9zjEEID6hK8HVb5wKWfr0=,tag:uV++ejf14MhX4XeaDw5l3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
