# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: downloads
type: Opaque
stringData:
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:aZnUYTNSE/lhyD2foMFcmjtr2pcCOzK2dzBPfTxzY7xwptMgqN11gJE=,iv:7M/eTFOtZTpkPljRvnCADC0/kOauTqLqghYGmKwuxuU=,tag:B0pnCNfawbJI2by0nv4tPw==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:X+c38w==,iv:rnpeV4MWiwgDDIHmOb39kE689Q32wfpqI09i7Ke7jrY=,tag:gUF9uqx3st5KuDlbcXnTZQ==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:sPnaB3kh,iv:fWZ8W7HT3BPBEUuHvrHWC8AMMsPbQ0hWhVFTNGVfFOU=,tag:inPp6Z7DrQf08HdGnilOkw==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:diLLdMLsyk15dVM2YzjyMdphsd8=,iv:geTKcbnl9W0Zc7S0fxoNBFMtGPgx+a7yoapy5Fl+PQc=,tag:a938VHPp7Z9WHYPaYZ0+bg==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:KJb7gK/mUqAk6n4=,iv:gJwlRF2Hp9pSHWC9L2tPF3gnETv2hFFzZ8a47ZhU2WI=,tag:/VF6Z6IzvhCjiJxNqunaaQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:NdhANp5ocXCjoPk=,iv:kSveTU70ZUnUbOK6coRxIVA3rur+9LPSgGGnDtNy5pc=,tag:jkNDpgh5ZTZ+KJgWcux8ew==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:OWaWTh1/tVdYc+Ba/fVgrtn/E1BDrt0L1QyBJFh/c8Z0Yh4VuJCKO6M=,iv:+qfYunWWFhXDGe0MyccHXI81rWljWKWwHw50Um9bELI=,tag:YgMSFpXik0FoJgs0hkqYzw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Q8bTkGXYaZ0mh+JGKYkvviSPWJc=,iv:3GF6aEwWIkI4dqF9orUjOFmdrn4zerkW4jMsrYTjCRo=,tag:rEGGumxw/Tp5z7PfppaKCA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:su6OchSL,iv:xT714D2zIaYA9xRR9w/pKTSkwIjw5fPLnZg1oUa52zc=,tag:jtCDL2Jz70kfRqxCDuWBRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T07:33:22Z"
    mac: ENC[AES256_GCM,data:LF/7kkuDULd02XFsQstENK78osS7IYF+1d/eaGmCR7wDYYBntofUu0gFAzHYClsrILjbSSkSU9HUru3fiph3Wz8BZQSaCEC9LKJ0/nXQkO2BfENvT+vpIcFA7avGupqyP1jyyf1xNnz+mpEru3WeapiFtfv47OlG5XI6SGav7wg=,iv:3bLHEfQG5DT2NTjKWL0H/bw2xjEVeX2RGVRp9VlVuE8=,tag:8KYt4ozkdom7sn5/iToUPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
