apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app transmute
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      transmute:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/transmute-app/transmute
              tag: 1.2.0@sha256:9a644e42082c010604b4299674eb1722eafdc83e5b6b85d1feb1782610d6ef38
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
    persistence:
      data:
        globalMounts:
          - path: /app/data
        path: /media/transmute
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: selfhosted
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: *app
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 3313
