# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: utilities
type: Opaque
stringData:
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:/LewZ9CemmDoTBUxXt9snonRzG7IWHJdoNO3rO+V7obrVtv1KwAtqg==,iv:xLs7SJwmhhiFvp2yPIZRKcsiKf4BZSu1GxGrbDTrBpI=,tag:zC7OSTW303zk9EECR8Mi7Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:EK+is2a631vf1W+OI165C5mj0TYrh+c3kD0bsLeck6ZAY2Hl,iv:RlmY9R0AhGG5lVnrR+edXnI3CjI6MM+iBAolptp4pso=,tag:aqnRp64BaxsBtous+FkH7w==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:g2o5ldox6EyBC7TsMQ+5h13UvVuHbrRYjYKrLrSndWk=,iv:PUy14bVWvSOujXuG3Y/FUI6+P8Mo4wpwN+7e8Hua4ZA=,tag:RwfevCNtjvt4YpSmmIxPDg==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:58RxHCbwm9Mjz/Yxs8EAqGNzkvE=,iv:Oc6i2C/6bUjnsweGIfsBJN5JajY/8xVSrbPdvRkJGuE=,tag:PviN5Ym2KOjQ83n3SJHTAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T14:06:27Z"
    mac: ENC[AES256_GCM,data:CtgykB+xH0OOWovMWdxhgPFG5Pql/cP768NukjnIvhc8kYO14KBLQnc7N4/nIxZNCTzvQJi8Gs2+3pNGGjE4k/xTyFnOA+e0NfGytymsO6LoqDqbCYbGEZlsOeNxlU8gyUJghx9MXIU/jwMEB7hZCj5nnW8ZS0zjWfBWQsDanYQ=,iv:FCWI3377+ZdY7WnStZzHoi6gsMEA8IJ+xk1PWK5oXyk=,tag:/qqOA6rrJRV2QQjgfI2h3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
