apiVersion: v1
kind: Secret
metadata:
    name: atuin-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jp6k5A==,iv:MsydI/ddUme2S8xYQqyBWBKnZ9p1CYoyhivuXL61mes=,tag:T1BjXJfKFnVAeBLdtkwQrw==,type:comment]
    ATUIN_DB_URI: ENC[AES256_GCM,data:6kJboriQCrvo+BrbmqK8hjojhVhHmgfpjDnFQJ1beJ3jK+weo8yfKP2XreWfbL0R1Y7+3vJUtwULXMswRkSSjmE9/pvj3N3oY9zHGrZ5zs96tMiabl0e7Q==,iv:pem15t3X88BHvO6hdPHfD339JFV5Izy09Liz5DI5xrE=,tag:n7r/IZZjDelK0JKmWKrFnw==,type:str]
    #ENC[AES256_GCM,data:lQHwGeIGy7vSS+p/YQg=,iv:PmSrqbzgVECxv26UUOpfiu6msjzesHNdTAVpOTGjJQI=,tag:HqPVGkQCjO+Z6zg1i7pTOA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ZMzxLQ0=,iv:tRpdDmOLUD4SnMvm4onxsJpL/K1WG+BSQPsvUTeCkzI=,tag:UzXcMiWhufRxNsu8CB+CUw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:wsKRrOzMiYlPWk4UOBTUjlGuJlxAarwN9fgOoJDbZpldggxDn2zffg==,iv:vudrJOOId4GYiJigvTnCdzbbo5t7q7O/qKJataMRk9Y=,tag:LzaxOhFmLD8IWSdkQgg4VA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:M5gp+AfWa80DIhslK6NfOsKtfW2E2393,iv:BHHfCNd0TZQbFWgYF6E05VIJSeHfu7E1y/5fzoJ0CcI=,tag:164vPyxXu8EPGh1SKVFL3Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:spalcW4=,iv:9coQaBFLF0LBpbfNd0fghzvyhuSg/UPfYSaig0PT15Y=,tag:ordiZpbSF/OhOcaKJ4XNjQ==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TExyL0FwNEsraWYzT1NU
            b2lsdGkvUkM3T0R4NUtDVlRIdGh4ODdreW1BCnJYS1lyY3hiZkNCRHFIK3V0TEFU
            WDN1a1BlRVRyc3dxclg3M09WTFZrZjQKLS0tIFNEMGovNmV2ZFp3SVkvVUVJNG5l
            S05QMEI0a0QveERic3FmNXMrdEl6RjgKp03aXneRhjHRtP8hXLs2/ebAubf6q1Af
            HEZIxwyxfm8nMDgIw+6OsHO6l5ZfSsfaIUiJiLIbvkv1Hjmq7IsjMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MEpKZU0xeHUwT2lmUDZQ
            SnllLzg1U1FQcjNjdDVJT1cycUJxQlZLcjFrCk1rMUV6Z2hsQ1F3blgzMktZZGRK
            UUFQL3RWRkR1bEZ1ZXdjQUdndkxXa0kKLS0tIFhXK3QySW4rZ1BZVXJGV3RONUJw
            RzJFSDBSM3VKanhtVXo4NytuaEJFN00KxYW/JINnoRuHQn5USyvC9T+Ls8Jo1ztI
            ZCKSNgdYAZcKTVML2DIw6Z1YAhqpeAAEInYJF97jeenlAm8AFGeg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T01:39:09Z"
    mac: ENC[AES256_GCM,data:Q8XGhgB5ag5GGiM3fGOjmOk4Hr5ORmz6oL9z/m0VWXn6r8qb3HcqKs1vpQN3Enc6XAsypVga0OJaF3ga68tp+/LYB6Iollf5Y+8Taoqcf4LLPRvgA5NC1ysfcU4+I9KwcD4zZEcGrVTEyxhDS+l9HlKBr3zQ5D0/nNB8Fu2pfG4=,iv:mIOBnUSZrXtUVCQez5KivzvqhEl9nYmirklM6M+VtN8=,tag:RHMDHFiG7Lo9dAk2kpfLlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
