apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ytptube
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      ytptube:
        containers:
          app:
            env:
              AUDIO_DOWNLOAD_DIR: /audio
              TZ: ${TIMEZONE}
              YTP_BROWSER_CONTROL_ENABLED: true
            image:
              repository: ghcr.io/arabcoders/ytptube
              tag: v2.5.8@sha256:8790aaf2b0fccce127475196f0f3862403ef8ca24d87d0b12451ef4ef50869ce
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
    persistence:
      audio:
        enabled: true
        path: ${NFS_PATH}/navidrome/media/ytdl
        server: ${NFS_HOST}
        type: nfs
      config:
        existingClaim: *app
      downloads:
        enabled: true
        path: /media/ytptube
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: *app
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8081
