apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ytptube
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      ytptube:
        containers:
          app:
            env:
              AUDIO_DOWNLOAD_DIR: /audio
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/arabcoders/ytptube
              tag: v1.2.8@sha256:a8f1be3c60a8b5284befffb18d1cb5ef4c452f804189875838d99f986ad67448
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
    persistence:
      audio:
        enabled: true
        path: ${NFS_PATH}/navidrome/media/ytdl
        server: ${NFS_HOST}
        type: nfs
      downloads:
        enabled: true
        path: /media/ytptube
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        hostnames:
        - '{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}'
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        ports:
          http:
            port: 8081
