apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ytptube
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      ytptube:
        containers:
          app:
            env:
              AUDIO_DOWNLOAD_DIR: /audio
              TZ: ${TIMEZONE}
              YTP_BROWSER_CONTROL_ENABLED: true
            image:
              repository: ghcr.io/arabcoders/ytptube
              tag: v2.1.2@sha256:393d83f21618f5416e04b7900869de16e57e4c72a34692c1ed92147ea2d0b793
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
    persistence:
      audio:
        enabled: true
        path: ${NFS_PATH}/navidrome/media/ytdl
        server: ${NFS_HOST}
        type: nfs
      config:
        existingClaim: *app
      downloads:
        enabled: true
        path: /media/ytptube
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8081
