---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats-opencloud
spec:
  chart:
    spec:
      chart: nats
      version: "2.14.*"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: cloud
  interval: 30m
  values:
    config:
      cluster:
        enabled: true
        replicas: 3
        merge:
          name: opencloud-cluster
      jetstream:
        enabled: true
        fileStore:
          pvc:
            size: &pvc 10Gi
            storageClassName: ceph-block
          maxSize: *pvc
        memoryStore:
          enabled: true
          maxSize: 256Mi
    natsBox:
      enabled: false
    container:
      env:
        # Should be ~80% of memory limit
        GOMEMLIMIT: 410MiB
      merge:
        securityContext: &sec
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            memory: 512Mi
    reloader:
      merge:
        securityContext: *sec
    serviceAccount:
      enabled: true
    podTemplate:
      topologySpreadConstraints:
        kubernetes.io/hostname:
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
      merge:
        spec:
          # hostUsers: false
          automountServiceAccountToken: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
