apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ngx
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100          # max weight = 100
          preference:
            matchExpressions:
            - key: cpu
              operator: In
              values:
              - high
    controllers:
      paperless-ngx:
        containers:
          app:
            env:
              COMPOSE_PROJECT_NAME: paperless-ngx
              PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_CONSUMER_RECURSIVE: true
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
              PAPERLESS_CONSUMPTION_DIR: /paperless/consume
              PAPERLESS_DATA_DIR: /paperless/data
              PAPERLESS_DBHOST: ${POSTGRESQL_HOST}
              PAPERLESS_MEDIA_ROOT: /paperless/media
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_REDIS: redis://valkey.default.svc.cluster.local
              PAPERLESS_TIME_ZONE: ${TIMEZONE}
              PAPERLESS_URL: https://paperless-ngx.${ROOT_DOMAIN}
            envFrom:
            - secretRef:
                name: paperless-ngx
            image:
              repository: quay.io/11notes/paperless-ngx
              tag: 2.20.3@sha256:f6fb81106d797f6ff93f268ef72001336c6aa26db1db3af5ccbf9d8a19d131e1
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      paperless:
        existingClaim: "{{ .Release.Name }}"
    route:
      app:
        hostnames:
        - '{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}'
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        ports:
          http:
            port: 8000
