# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: pocket-id-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: pocket-id
        INIT_POSTGRES_HOST: ${POSTGRESQL_HOST}
        INIT_POSTGRES_USER: |-
          pocket-id
        INIT_POSTGRES_PASS: |-
          {{ .POSTGRES_GENERIC_APP_PASSWORD }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPER_PASS }}
        DB_CONNECTION_STRING: |-
          postgresql://pocket-id:{{ .POSTGRES_GENERIC_APP_PASSWORD }}@${POSTGRESQL_HOST}/pocket-id
  dataFrom:
    - extract:
        key: pocket-id
    - extract:
        key: cloudnative-pg
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: pocket-id-encryption
    template:
      data:
        ENCRYPTION_KEY: |-
          {{ .ENCRYPTION_KEY }}
  dataFrom:
    - extract:
        key: pocket-id
