apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: utilities
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.2
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/library/eclipse-mosquitto
              tag: 2.0.21@sha256:94f5a3d7deafa59fa3440d227ddad558f59d293c612138de841eec61bfa4d353
            resources:
              limits:
                memory: 16Mi
              requests:
                cpu: 10m
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.21
            command:
              - "/bin/sh"
              - "-c"
            args:
              - cp /tmp/secret/* /mosquitto/external_config/;
                mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd;
                chmod 0600 /mosquitto/external_config/mosquitto_pwd;
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: mosquitto-pvc
        globalMounts:
          - path: /data
      config-file:
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
        name: mosquitto-configmap
        type: configMap
      external-config:
        globalMounts:
          - path: /mosquitto/external_config
        type: emptyDir
      secret-file:
        advancedMounts:
          mosquitto:
            init-config:
              - path: /tmp/secret
        name: mosquitto-secret
        type: secret
    service:
      app:
        controller: mosquitto
        ports:
          http:
            port: 1883
