apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: utilities
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:VB5gWqM=,iv:YSgsc0gv/kU8Bq2sTHMMBvXN1qENi4BWhs0mlzxGiLM=,tag:pAlKM7itVNYXbOnmvCbqRg==,type:str]
    password: ENC[AES256_GCM,data:nZxzPLjkYW25JcTVaDlnM4h2/qAr87c8,iv:kVu415wdiHo9E6q3MBLHRWS3/ze/s69tAaiwoMrn5Uc=,tag:r0r33A7Y8TTQfF708AW83g==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:ppyM8FmsxDK4al1gcXISsJPjOMOGA7zm35AYk7f4,iv:lhYLRxl1Kk+VgLX0JmiX7PbD6llcYmQ2oBrr3H/6AQA=,tag:JTUMTR8N1J5AFAowR1Yv+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTTVPRUV3RGQ0T29PWHFO
            bmFncGxRLzlhK0FoblVyMzNaRGJQNGZsNUc4CnB1Mk9Hd3lTV0plQ1QxZWJDTERH
            S0ZwMHNHd0dpdnNPdkdwODFMU0duUmsKLS0tIFJUWXdrdkoxU3RQejd2a3EwR3Nq
            MmYvTTNwNW1XT0Z6RlRJRWVhdlZJYjgKkg5RsFui5WjujVGu9rnfJy4/eJ8MMH4L
            CPk0OPPqeJcPoYa2cRaDVQs9UQcIb1KhkS+RSsRiVCRDGL9eUIZxeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaU53YWNuQU9pc2s5YWM3
            N21Nc2NudEoyVHRnRjN3UlRqQ1JYdWVOcW0wCnNva0MrRDhXVy80VThaZDloWk1v
            bWdMRm9MUVlxaDJGREorZmc5MXM0Z2sKLS0tIHpra0xuTjRJa2pab1VoaWZxTk5Q
            UlRFUlFWR1JsUGFOUEF3MDN0Uzg0cnMK3oekzmVq3k9LImkRuYebp1WBImetrRmn
            aHv4icOI7jr86IRxgSCXgBLLrk0FxNA1YKoJvEt+Jji1UbtLEw95wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T00:38:31Z"
    mac: ENC[AES256_GCM,data:G8VuBsrkBZoQY4NBygJfnV0lXB/lGFyFjquDB8YzqZ8WaEIFQ3HYtVZIe4V/e8mb4d75NtNeJLPXn4kkKyQE377Rzxv2e2lFIs1XlvyT15c+3ptzA8o5cVuAeC+JDCKJUhYs1khQRZTxntk+2aMBxRyjhHNweT+WjvggsvGR2tM=,iv:Q3RoaZySsjJhXNWYX2qLz9gUhQloYdeUFYJ6GryMcT0=,tag:OQjovVPt3ENbhaKc7MuJ6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
