apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kavita
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      kavita:
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/kareadita/kavita
              tag: 0.8.4@sha256:07393ed7d6860e7312c0197b8c1ebcd4d53c52b7cabd542db08613410ff22c69
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host '{{ .Release.Name }}.${ROOT_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      books:
        enabled: true
        path: ${MEDIA_PATH}/books
        server: ${NFS_HOST}
        type: nfs
      config:
        enabled: true
        path: ${NFS_PATH}/kavita
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5000
