# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: tuwunel-secret
    namespace: selfhosted
type: Opaque
stringData:
    TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:zjddAo1kJqDOQyJHSGi9Zd6XlF+p16wAzLoSUxKi0Pf740HpR+Wh8GcIhI0ZcMcC,iv:REe0Pf0VKNFGZ0FYoUcu4I/8flUgTz8yxM+bBMtTRJQ=,tag:QgxLt7GsP9gE3UpwzDiioQ==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-23T13:28:46Z"
    mac: ENC[AES256_GCM,data:D0DbDwR4ya4pW2SOWEMUY32ezdHKZy8M5vFSiKPGtsIqirln+LVXpC0k80dymCFR7uvkpdaHNYUMg9iZfTzT/v/W17Tes6jRxqy8Gy8IR4KxOVDZ3grDTi2JzBIWkvvU0eFQxc+XXVRTLBoziDMCKB1QOJwEs+SsxCnjaxTLn0k=,iv:6k2P3dS6Wtw3362RjzhG9RoTjgLn35UdeZxzoyqKJOU=,tag:NRd5hN6Bo143LBQcQ/rLuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
