---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: selfhosted
spec:
  interval: 15m
  chart:
    spec:
      chart: matrix-synapse
      version: 3.11.3
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    config:
      enableRegistration: false
      registrationSharedSecret: ${SECRET_MATRIX_REGISTRATION_TOKEN}
      trustedKeyServers:
        - server_name: ""
    extraConfig:
      registration_requires_token: true
      suppress_key_server_warning: true
    externalRedis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
    externalPostgresql:
      host: ${POSTGRESQL_HOST}
      port: 5432
      username: synapse
      database: synapse
      existingSecret: matrix-synapse-extra
      existingSecretPasswordKey: postgresql-password
    image:
      repository: ghcr.io/element-hq/synapse
      tag: v1.123.0@sha256:7e8e20f2c0e7b344ce4d31bab943cb1677ee66de4de0f6a24107e8641a4a8122
    ingress:
      className: internal
      hosts:
        - &host "matrix.${ROOT_DOMAIN}"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: matrix-synapse
              port:
                number: 8008
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      existingClaim: matrix-synapse-pvc
    postgresql:
      enabled: false
    redis:
      enabled: false
    serverName: *host
    signingkey:
      job:
        enabled: false
      existingSecret: matrix-synapse-extra
      existingSecretKey: signing.key
