apiVersion: v1
kind: Secret
metadata:
    name: backrest-secret
    namespace: selfhosted
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:9DJ5Egyd/oRALst2alb2nb+xe8/rbAyq3uiCQjuk5mtCMS6B6X1bIbQ1YrWA7R3TZ6ne/3UcJ9Kha4iSsY/lM1Owq4QollrqEOQDCxtOBDcaOFpjCvkoAT+l0+u6FhzxKp/6ypCrz6sbR7NYijKi1UAN5lN/z9w0AnwXXbUoBn6btBqfmdPeUJUvuCxQ0Bsb4vSv5LEqd7Adr2iQamBWLs87fyIXoUY3CUAUbxVh2mUy/x1uFuuB7FuHjhClt+RFKoWEyOlH49EByHHJD2soA5WNSxQ52LrKyKSW1niJHZem7M5mfsgrAccDETYZ542pCWKPu45stRE12PytN7IOj044vooztWwOuHcUJRTfnARXNKWg1kB4Ql85Bp61YKjaxbnzkVw2KF0VlcZQc/oycGGjwzpNk5Lc64FSaWDQmb0sqqtMK9NblbQvTNasXZ/yAKOU6NgpOJQyGUj7vgjfy/IkWBG8bSUdWIFl46UVg/V5mb0yoskDmbZoMldSwufUEHs/SqEG3PdxPlqJi0FrEvE/md48mYZ5oYKzWajB8ZOpQGg9jskXOMdIyryPfxilt68KeMbsTtfnElpSwyEuG+mpoT0UGLRmjke4M/mBPPp0C0nnyUUQ+2KMcacvF+aYeCR/HsbBhuU/dGB0emIU0FHrN+miqJPQOO1JCn1oxYnO4pzVVwMJIgCI8UR9PWZUmaWpPfZMz14kXP70ImW3ZsZ92ABNtkE/aWdaWRJKVRhDH1tAc7FTUEDeUUJvSZp97XAI7S+aqmu+j9K0mUnlLL18f6q+3tYS1Do9n9JZl5yYvxyXayd/iVsAi+RoQnKUzAdQTrXWaD6w/d6fEaP/CPiY46LIDZ28VtTXuFPKm98G7srGXX3e0U39a9dhyhtTp+mTB+vzc0L1nqNCvafXxSxdrmyJXy8Znk5ZPV6xyRC0t8iRqo5AfhfaUupHgeVu7u6WflKXkNtR27DibLsTj6wMKVZTAFgt/pb31M/jA6n6IinM4Yw8/dm1f66R4vH1Idkl6pjU3tiFzsH0Qx8Iv1lK+Lr3fXzjd5QMkX1MvfkK0exOKSRf62H7aVlQl8cfuyPjJD7KgOrZ6kjn1N/uch20QZqK8bfGuZ/P4jXoolo1Z8vFD6C4+DvrQ69X8ogyEJ5XzupZtueUdVOaPD/Kr1NVkbGtyVhXtJynh7h11Ns9FDaxrlPWJeJPTrk24plwdLhvINHI0Zk+QZPYDx7yZHDX4xgx1BDWI6aSJMzCAHIETlXzr3uHtRLKySwSKDZlRzjTElVHdpoaCeiTXu/3fMgu63KssQdE0kmZRFkc7bk88vwFMLNpC+yO572yddWfbPMuKESnm6pNU04xA1M0pluwZBD2SWlJ5dSzdTnPLTxK/TQlRIkAq64eDnlZNOvg5S8inS5Siw==,iv:BQRxiEV8dHjaqfALup765iTSLxkhVN5NNC5evUQ/0ww=,tag:DXnhaIwEAEAIc60N+KNHIQ==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TExyL0FwNEsraWYzT1NU
            b2lsdGkvUkM3T0R4NUtDVlRIdGh4ODdreW1BCnJYS1lyY3hiZkNCRHFIK3V0TEFU
            WDN1a1BlRVRyc3dxclg3M09WTFZrZjQKLS0tIFNEMGovNmV2ZFp3SVkvVUVJNG5l
            S05QMEI0a0QveERic3FmNXMrdEl6RjgKp03aXneRhjHRtP8hXLs2/ebAubf6q1Af
            HEZIxwyxfm8nMDgIw+6OsHO6l5ZfSsfaIUiJiLIbvkv1Hjmq7IsjMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MEpKZU0xeHUwT2lmUDZQ
            SnllLzg1U1FQcjNjdDVJT1cycUJxQlZLcjFrCk1rMUV6Z2hsQ1F3blgzMktZZGRK
            UUFQL3RWRkR1bEZ1ZXdjQUdndkxXa0kKLS0tIFhXK3QySW4rZ1BZVXJGV3RONUJw
            RzJFSDBSM3VKanhtVXo4NytuaEJFN00KxYW/JINnoRuHQn5USyvC9T+Ls8Jo1ztI
            ZCKSNgdYAZcKTVML2DIw6Z1YAhqpeAAEInYJF97jeenlAm8AFGeg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-29T23:20:42Z"
    mac: ENC[AES256_GCM,data:MA7O5s29mP4YtltBSjWSws1FRGWzNY6cX027NvU4pIK0e2PtnqKLLL7oGslI5dEN7uDGmzxIzoBDvo8mvNikMlgpiT9LBbBRevTWUym1tuENj4fsAuAQX/bwNoSKH8Kj/uTV4ePBtunl0BtigSJkQdG+Y+xGgyUf74j1pT0aOT8=,iv:FzyXK3TJ0kx605hjLaji7vJ9MFqEaCwvtt8gCFmTldQ=,tag:7QPKnsKKYcOtoVeEONyX7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
