---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adguard-dns
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    # domainFilters: ["internal.${SECRET_DOMAIN}"]
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v11.1.1@sha256:b3dfe851982b59a36bf2e15f42ca4015b7ef39ddf7a808c39a855a05a61b5892
          pullPolicy: IfNotPresent
        env:
          - name: ADGUARD_URL
            value: https://adguard.${ROOT_DOMAIN}
          - name: &name ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: &secret adguard-dns-secret
                key: *name
          - name: &name ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: *secret
                key: *name
          - name: SERVER_HOST
            value: 0.0.0.0
        securityContext:
          readOnlyRootFilesystem: true
    interval: 1h
    triggerLoopOnEvent: true
    policy: sync
    registry: noop
    sources: ["gateway-httproute", "gateway-tcproute", "crd"]
    extraArgs:
      - --webhook-provider-url=http://localhost:8888
      - --gateway-name=envoy-internal
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    logLevel: debug
