# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql16
spec:
  env:
    - name: TZ
      value: ${TIMEZONE}
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: longhorn-ultra-fast
  superuserSecret:
    name: cloudnative-pg-superuser
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "250"
      shared_buffers: 128MB
  resources:
    requests:
      memory: "512Mi"
    limits:
      hugepages-2Mi: "512Mi"
  monitoring:
    enablePodMonitor: true
