apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-dev
  namespace: dev
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.3
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            envFrom:
              - secretRef:
                  name: immich-secret-dev
              - configMapRef:
                  name: immich-configmap-dev
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.130.1@sha256:767946d7143630a08f954d070dd442bf69e8aa99faf472d1530b14693dfa2e21
            resources:
              limits:
                memory: 5000Mi
              requests:
                cpu: 100m
                memory: 800Mi
      server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            envFrom:
              - secretRef:
                  name: immich-secret-dev
              - configMapRef:
                  name: immich-configmap-dev
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.130.1@sha256:6c8b4ddf5fd5a25443078eef47d015c231b1ce092fe3b6f2d758b182f0066e26
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: immich-dev.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: server
                  port: http
        tls:
          - hosts:
              - immich-dev.${ROOT_DOMAIN}
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc-dev
        globalMounts:
          - path: /usr/src/app/upload
      model-cache:
        type: emptyDir
        advancedMounts:
          machine-learning:
            main:
              - path: /cache
      nextcloud:
        existingClaim: immich-nextcloud-pvc-dev
    service:
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
      server:
        controller: server
        ports:
          http:
            port: 2283
