apiVersion: v1
kind: Secret
type: Opaque
metadata:
    creationTimestamp: null
    name: immich-secret-dev
    namespace: dev
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:MbNVbLx6V5IH,iv:W4VhFVV+Vtjc3Ty/81OUqxJ145krFKG3++mFBTLe4fA=,tag:VRsGJEV2And/v/ujS3hjRQ==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:QmC4ocRCTwQSrDY2WLAbx+Bu0WLqOKt8gt/3QsUBykS/gQ==,iv:sneSotNfQmHQfq5ATIVgjT2QbpzA/6hZJHUegf9rFqs=,tag:XZfvAeKEL6OufSVF/OXrkw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:vEUzlOMUCFKh,iv:hDeYJWwwQuY7vsHVdWQqajdqEVUEl9jISDrQ5hkKkA4=,tag:9B34Dn6jT4Vymqtv9rz/xQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:jlpAxc0kab/ivHxdWjnpQ/8vhCELC24nL8Hmurri8fyXEza3j8GrOBBUeIwfMlqt,iv:yo0XywrDstgJN5ZSuUVKKhGUhfUh+2LnLGWpmp4/jk4=,tag:YgvCsu5DAHYrYen+WOiqng==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZlkyR2wrQTJ0R2ZLRysw
            SzVBRlQ4Rm40OERuZXZ6RGo4OCtGNk5nazFBCnhaL0FMa0JDK0hSclU0blcvZEsy
            RHZ5dHlaOFFUZUFJMU9yUDBONjRKRzgKLS0tIDRiMklmdE1ZWUI3ajZqQXQ4cUVV
            UXplOUsyUWdtRkpmQnEyRVJGdzI2b0UK0veZ/y78gEq4gNYD/ZJuCbRt1U5MYNPq
            F4H/5hxSe7Uf09dFdQqa9rdXey2z7XBKWpvWgy616N2l3vYibd/gqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcVFzalcyMHN5TWUwTmRO
            MGYwZ2VkS2ZmQ3cyNCt1M1FBNms1NEJBRGpRCjg0U0h6WVl0UlFsZTg0b2RTMHhN
            Wm1LTjA5MHB3L1R1amVYd0pNUmJ1ODgKLS0tIFFwSFNNcWJEck9rL3hHeE9qc1Zn
            dTRsQ2RVc1VkL0RwSFhic1hyOWlWdXcKbPURscQjqFAIqznqum53Kazlog0XgT5L
            CKx4spGO6xCmaTmMfUeSP6fOfvFb+71ebPohY8caQczrnaW886juUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-14T00:31:47Z"
    mac: ENC[AES256_GCM,data:2MyEYEuuCZAsvH580ouL4rPAt0ZHn7TU9TNBb4NljrscK+jTei5rsBauypMI5PcOd3oa3xU7pSVCbGMXcCgtCVSUGBAKQNzADCVCH0M/gJTdQl87qN82XbE5zJ7izRzrm6GW82k6ASv6e+bX1dG4ol22VZmFj+nSoVTezOvVxlk=,iv:VYZ0F5DoJgBQLEgYHFXlXc46CwiBToMKsSFYQwJV2vc=,tag:z8AXeHq5/1K/cLS0lNbQlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
