apiVersion: v1
kind: Secret
type: Opaque
metadata:
    creationTimestamp: null
    name: immich-secret-dev
    namespace: dev
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:SMpWkr9YBujuSw==,iv:AGV6yNbptAk11h+If5VEFvrqsqU1tZyzfWsEyH03YvE=,tag:oJUiDultHJiDx11DtuZcog==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:ggMf7JIuDkVMsiar0YUVWOUuO9MSQNlydvs3+9fW,iv:K9pkG1IanYpW7BGlDpqwfxMprvoWpiSC8ShSqAhJxMw=,tag:QJRIH3O6DZiGc/QGMyeTPQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:yAfF/37WTplwGQ==,iv:W86q9D4B9YyjaHXMjKW0SKIbupwQqy68boUlmyNcMZo=,tag:wIDFqA3cFQWWqKdUCjCerg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:jlpAxc0kab/ivHxdWjnpQ/8vhCELC24nL8Hmurri8fyXEza3j8GrOBBUeIwfMlqt,iv:yo0XywrDstgJN5ZSuUVKKhGUhfUh+2LnLGWpmp4/jk4=,tag:YgvCsu5DAHYrYen+WOiqng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZlkyR2wrQTJ0R2ZLRysw
            SzVBRlQ4Rm40OERuZXZ6RGo4OCtGNk5nazFBCnhaL0FMa0JDK0hSclU0blcvZEsy
            RHZ5dHlaOFFUZUFJMU9yUDBONjRKRzgKLS0tIDRiMklmdE1ZWUI3ajZqQXQ4cUVV
            UXplOUsyUWdtRkpmQnEyRVJGdzI2b0UK0veZ/y78gEq4gNYD/ZJuCbRt1U5MYNPq
            F4H/5hxSe7Uf09dFdQqa9rdXey2z7XBKWpvWgy616N2l3vYibd/gqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcVFzalcyMHN5TWUwTmRO
            MGYwZ2VkS2ZmQ3cyNCt1M1FBNms1NEJBRGpRCjg0U0h6WVl0UlFsZTg0b2RTMHhN
            Wm1LTjA5MHB3L1R1amVYd0pNUmJ1ODgKLS0tIFFwSFNNcWJEck9rL3hHeE9qc1Zn
            dTRsQ2RVc1VkL0RwSFhic1hyOWlWdXcKbPURscQjqFAIqznqum53Kazlog0XgT5L
            CKx4spGO6xCmaTmMfUeSP6fOfvFb+71ebPohY8caQczrnaW886juUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-22T10:26:22Z"
    mac: ENC[AES256_GCM,data:QsuctCT+DewNCbgGlnldI0QDlzeIeVkVaAzaysFnkpzUi67ngI/eTxtwEZ235A82ybr9byKEM794/3GSTs18N+T2Qbj3tRm5FSQN2BjINUqe4WnmJhq9L6bvohvyda1bO+MnngCx3mHsMiraJMxoCWLDvwYsoHZicuA0xwgzC5o=,iv:x7vC+yepyNqTuUL7mIvwYD76WbsIOi1GI8Wu5bcsfWo=,tag:zwOPiRN6MwD/COU5ZCt1iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
