apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app filebrowser
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100          # max weight = 100
          preference:
            matchExpressions:
            - key: cpu
              operator: In
              values:
              - high
    controllers:
      filebrowser:
        containers:
          app:
            env:
              FB_DATABASE: /config/database.db
              FB_LOG: stdout
              FB_NOAUTH: true
              TZ: ${TIMEZONE}
            image:
              repository: filebrowser/filebrowser
              tag: v2.52.0@sha256:363c1eae79e7c08bbb994c3511875cbcb65e70df9ac850221d60400c362f4ff9
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
            - 10000
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
        - path: /config
      media:
        globalMounts:
        - path: /srv/media
        path: ${MEDIA_PATH}
        server: ${NFS_HOST}
        type: nfs
    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 50Mi
    route:
      app:
        hostnames:
        - '{{ .Release.Name }}.${ROOT_DOMAIN}'
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        ports:
          http:
            port: 80
