apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant-code
  namespace: utilities
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      home-assistant-code:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            args:
              - --auth
              - none
              - --user-data-dir
              - /config/.vscode
              - --extensions-dir
              - /config/.vscode
              - --port
              - "80"
              - /config
            env:
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.101.1
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 10m
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsUser: 568
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: hass-code.${ROOT_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - hass-code.${ROOT_DOMAIN}
    persistence:
      config:
        enabled: true
        path: ${NFS_PATH}/home-assistant
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: home-assistant-code
        ports:
          http:
            port: 80
