apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app piped
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: piped
      version: 7.4.5
      sourceRef:
        kind: HelmRepository
        name: teampiped
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    postgresql:
      enabled: false
    frontend:
      env:
        BACKEND_HOSTNAME: &pipedapi pipedapi.${ROOT_DOMAIN}
      image:
        repository: docker.io/1337kavin/piped-frontend
        pullPolicy: "Always"
    backend:
      config:
        PORT: 8080
        NUM_WORKERS: 2
        PROXY_PART: https://ytproxy.${ROOT_DOMAIN}
        database:
          connection_url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/piped
          driver_class: org.postgresql.Driver
          dialect: org.hibernate.dialect.PostgreSQLDialect
      image:
        repository: docker.io/1337kavin/piped
        tag: latest@sha256:2fcc0dcec2dfec853506434876219b2a8fe8715f2bdc88bbe2ce559c840d68bc
    ytproxy:
      image:
        repository: "docker.io/1337kavin/piped-proxy"
        pullPolicy: "Always"
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.${ROOT_DOMAIN}, https://ytproxy.${ROOT_DOMAIN}, https://pipedapi.${ROOT_DOMAIN}"
        ingressClassName: internal
        hosts:
          - host: &host piped.${ROOT_DOMAIN}
            paths:
              - path: "/"
        tls:
          - hosts:
              - *host
      backend:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.${ROOT_DOMAIN}, https://ytproxy.${ROOT_DOMAIN}, https://pipedapi.${ROOT_DOMAIN}"
        ingressClassName: internal
        hosts:
          - host: *pipedapi
            paths:
              - path: "/"
        tls:
          - hosts:
              - *pipedapi
      ytproxy:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.${ROOT_DOMAIN}, https://ytproxy.${ROOT_DOMAIN}, https://pipedapi.${ROOT_DOMAIN}"
        ingressClassName: internal
        hosts:
          - host: &proxy ytproxy.${ROOT_DOMAIN}
            paths:
              - path: "/"
        tls:
          - hosts:
              - *proxy
  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: database.password
      targetPath: backend.config.database.password
    - kind: Secret
      name: *app
      valuesKey: database.username
      targetPath: backend.config.database.username
