apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app piped
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: piped
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: teampiped
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    postgresql:
      enabled: false
    frontend:
      env:
        BACKEND_HOSTNAME: &pipedapi pipedapi.${ROOT_DOMAIN}
    backend:
      config:
        PORT: 8080
        NUM_WORKERS: 2
        PROXY_PART: https://ytproxy.${ROOT_DOMAIN}
        database:
          connection_url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/piped
          driver_class: org.postgresql.Driver
          dialect: org.hibernate.dialect.PostgreSQLDialect
    ingress:
      main:
        enabled: true
        image:
          repository: 1337kavin/piped-frontend
          tag: latest@sha256:fa1f56517b50c5f0092169672486fea8b7223961eef69d5b9c24aa798264a15f
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.${ROOT_DOMAIN}, https://ytproxy.${ROOT_DOMAIN}, https://pipedapi.${ROOT_DOMAIN}"
        ingressClassName: internal
        hosts:
          - host: &host piped.${ROOT_DOMAIN}
            paths:
              - path: "/"
        tls:
          - hosts:
              - *host
      backend:
        enabled: true
        image:
          repository: docker.io/1337kavin/piped
          tag: latest@sha256:e9938cdda0745c4986d4add0f255777d3989849b851f290d94a4ab2b21c25384
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.${ROOT_DOMAIN}, https://ytproxy.${ROOT_DOMAIN}, https://pipedapi.${ROOT_DOMAIN}"
        ingressClassName: internal
        hosts:
          - host: *pipedapi
            paths:
              - path: "/"
        tls:
          - hosts:
              - *pipedapi
      ytproxy:
        enabled: true
        image:
          repository: 1337kavin/piped-proxy
          tag: latest@sha256:1822ff4d93be0119d5fe6526f74b034a0ff35db1a9c8b652e095e17d2f8edab5
          pullPolicy: always
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.${ROOT_DOMAIN}, https://ytproxy.${ROOT_DOMAIN}, https://pipedapi.${ROOT_DOMAIN}"
        ingressClassName: internal
        hosts:
          - host: &proxy ytproxy.${ROOT_DOMAIN}
            paths:
              - path: "/"
        tls:
          - hosts:
              - *proxy
  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: database.password
      targetPath: backend.config.database.password
    - kind: Secret
      name: *app
      valuesKey: database.username
      targetPath: backend.config.database.username
