---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  NFS_HOST: 192.168.2.5
  LOCAL_PATH: /mnt/raid/local
  MEDIA_PATH: /mnt/raid/media
  NVME_NFS_PATH: /mnt/nvme/nfs
  NVME_LOCAL_PATH: /mnt/raid/local
  NFS_PATH: /mnt/raid/nfs
  TIMEZONE: Asia/Singapore
