---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  LOCAL_PATH: /mnt/raid/local
  MEDIA_PATH: /media
  NFS_HOST: cobalt.internal
  NFS_PATH: /nfs
  NVME_NFS_PATH: /mnt/nvme/nfs
  NVME_LOCAL_PATH: /mnt/raid/local
  SMTP_HOST: 172.16.0.125
  TIMEZONE: Asia/Singapore
