---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole-dns
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    envFrom:
      - secretRef:
          name: &secret pihole-dns-secret
    extraArgs:
      - --pihole-api-version=6
      - --pihole-server=https://pihole.lithium.${OLD_DOMAIN}
      - --gateway-name=envoy-internal
    interval: 1h
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    policy: sync
    provider:
      name: pihole
    registry: noop
    securityContext:
      readOnlyRootFilesystem: true
    sources: ["gateway-httproute", "gateway-tcproute", "crd"]
    triggerLoopOnEvent: true
