---
alerting:
  matrix:
    default-alert:
      description: health-check failed
      failure-threshold: 5
      minimum-reminder-interval: 1h
      send-on-resolved: true
      success-threshold: 3
    server-url: https://tuwunel.${ROOT_DOMAIN}
    access-token: $${ACCESS_TOKEN}
    internal-room-id: $${INTERNAL_ROOM_ID}

