# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: gatus-alerts-secret
type: Opaque
stringData:
    alerts.yaml: ENC[AES256_GCM,data:e2nyrYgwZA2KMc8lL16ncDAVxfa3/lvxzFglx84dRwJgAbkpC/ubIwEaG55YNvmT0mWFbowlGMK95yVc4Pa7f1IehDmtKE6PfYzfB1rMKQrIpJq+81x3IABENnI1GQeUPK0Iu0/LdIBnl3MimCS5krxp+xqq6+I89hmGsdczfjsP29yrAQTNr08nBtc1SaSR+hdRWG5ytD3xpSC3MLnADvmFwFofOeqxGoeaTiN0C9yXp3a+SL4L7xqKLQ4xC3kMOn+xXP89s4ypr9ZCSxwEpRAEmpYvEF/0euuW+pFVyCxav7F70x5DBbB57kFiGG+hvyEyrwakoS4T25wtsQ0syzkR9yBw4+q+Gn7HeYNEIkLvhXmxsL4lVwSCCRyKWkxiKD2BfFY0YwFPU3U/Geh/OpiE6VId9yf2Vd/Y3xBsnxFz3CpbM5V9jTpAq9zNQvGkIjSPq/Ek0k4ykv12tG1PJ7faNWudgCHVUL4+mNYh2VMLE0wyyScgp/vPmdG6+/iHbQZBnt5tzWh+jEbK2A==,iv:JeI+eF8kqGOXK+GpF6Vnd696Yu4yf+ZvbFzb9ffREvY=,tag:9sNjXztA07AMaVHyGN5XDg==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeXYyVE9BQnlpc1J2cnBy
            SmdFbm1WOVZyMURjQjdFTjBESFYrRm1ENzNvCitCUkxMdUdhRW9UN0t5RXRIMTRs
            dWVlMER4eU44ckN1WHBySmVIZXJSU00KLS0tIERpSHF3bktLYjRwMkkrMm9OaVpL
            T1o4ME9yRktCNWdBN24zNmkzMkpZVlkKsobY0e246RlZzHIxqynmc7epDk7kaw2p
            tBQBZpuiKmW8DGnEtQRKP9BqzUEkb7JaMiodDg4TLMWZxLNts7B7hA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaTIvcmZRSU1NbzFQVndr
            WG9rVGRlN2RqVHREZEN2N0tLRytrQVB6Z0I4Cit2ZW1rallkaVpRMXdQMTdXZ253
            aXVJbmFYTklxaW1zcmZ5cTdrYzJtQVkKLS0tIE9oRkM1K2FDQmZCdXdHcEtNSEZh
            eTRGVWpCZXp2djIzSlRhVlIyS0JwRHcKjsb6VcauWzgHUZ/4oWBvE4b2AwExeWLD
            sNZ5oENfEXTw1d2AlzR3t/KHYBeJi+rBaIMdusyvumTGMJYeuXEhsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T00:54:19Z"
    mac: ENC[AES256_GCM,data:Q0TaLVLPe62HsVqpvzLe9K1wuxMwmkS0KcwSQpWO+vvk53sXiNAgEeeZEE132f2twoaWwRTDWBP8Mez38zRmtegPiwNixYzFYM3ZYbcve0nazS4Q8TnUFu2Egm3LR4eC16I9NA2mgHQVBVm6qi38uQQfOadaBbEMyKtEbLDFNaQ=,iv:BjhV4fsoXyCJPI7QHuj/AEecjWknyTifqPnPjIQOPOY=,tag:bL5dEDjiwgQqPAbiqVOirA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
