# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: gatus-alerts-secret
type: Opaque
stringData:
    alerts.yaml: ENC[AES256_GCM,data:ZCOASNtrJBOTUH3Ga/aZYQLN2HbJYE8q3tNTYkqI5LJJRv1Yotc6bk2Miii8tZFBipgmLPsniIx4HJSoWqLZFGlAskHAv3jrTQ5Mt0GjhUeD2+PemMJEhn98sr5c6UoD4+bsgbS2ifjD1tQ4P1mshvyTsxhBJpxYophmUWMiE4uoDsq0cpGcvNlds54nARWUmIdilRd1qg9+Fvqr1NmGyNhbyT59ZZdpNSco2puVQkLtTdWmN1Ve32ITAqrQEhu4k/pLtP9UtY0iVuoRo6iPORRNvATWhLOxvdEwmrBnmOCME7p1wv3y39vGRee0PtB5YuRjeg+vtmHXDFkafRh52LUM39tgeU8RTZfDNpgQ6NIfz5pqU8SbZGrk5jFccbRobRFVAU/99EPn9PrLOggs6JXXJXj7UcDWKoinI9obI7EpVnGHSd37WGwdZ+WfSvvyXGLAQwwzPI82Ykt9KKcGbpaKr4eDVuCrVQPVTMBsJSNUerhtP1MqDQfzKJK67XpHvWIPzz8k,iv:lvGahlPt7fpup1kNIh21yeieOcExgEY+bUTRhw6LEPg=,tag:Z2LuRN7X2ezeIQOmV9Hymw==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeXYyVE9BQnlpc1J2cnBy
            SmdFbm1WOVZyMURjQjdFTjBESFYrRm1ENzNvCitCUkxMdUdhRW9UN0t5RXRIMTRs
            dWVlMER4eU44ckN1WHBySmVIZXJSU00KLS0tIERpSHF3bktLYjRwMkkrMm9OaVpL
            T1o4ME9yRktCNWdBN24zNmkzMkpZVlkKsobY0e246RlZzHIxqynmc7epDk7kaw2p
            tBQBZpuiKmW8DGnEtQRKP9BqzUEkb7JaMiodDg4TLMWZxLNts7B7hA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaTIvcmZRSU1NbzFQVndr
            WG9rVGRlN2RqVHREZEN2N0tLRytrQVB6Z0I4Cit2ZW1rallkaVpRMXdQMTdXZ253
            aXVJbmFYTklxaW1zcmZ5cTdrYzJtQVkKLS0tIE9oRkM1K2FDQmZCdXdHcEtNSEZh
            eTRGVWpCZXp2djIzSlRhVlIyS0JwRHcKjsb6VcauWzgHUZ/4oWBvE4b2AwExeWLD
            sNZ5oENfEXTw1d2AlzR3t/KHYBeJi+rBaIMdusyvumTGMJYeuXEhsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T00:59:01Z"
    mac: ENC[AES256_GCM,data:jn1FyTjJ51KiodEgSd5TTzVbRm4CoQflSdBDdTx0svLWc4LF05SvIrwqBLwEckTlOepIUKs5EsFIcHV0aaC77Ps1+wd93EZCIACiJOJ/3pgKVcKToyR1CV8a7/HDXchG0naVRd8qeE6FsfFxcIdE5USFHryELaSYGvY+SdchJ7g=,iv:TB60fUafdZG6cq1OgDCAjkb9Dl+PzueO+AfHYt0g7WE=,tag:v++Ho3hzSydad1Zq5N6nkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0

