---
connectivity:
  checker:
    target: 192.168.1.1:53
    interval: 1m

alerting:
  matrix:
    default-alert:
      description: health-check failed
      failure-threshold: 5
      minimum-reminder-interval: 1h
      send-on-resolved: true
      success-threshold: 3
    server-url: https://tuwunel.${ROOT_DOMAIN}
    access-token: $ACCESS_TOKEN
    internal-room-id: $INTERNAL_ROOM_ID

metrics: true

ui:
  title: Status | Gatus
  header: Status
  link: https://forgejo.lithium.${ROOT_DOMAIN}

web:
  port: 80
