-- udp/tcp dns listening
setLocal("0.0.0.0:53", {})

-- disable security status polling via DNS
setSecurityPollSuffix("")

 -- K8S DNS
 newServer({
   address = "10.96.0.10",
   pool = "k8s",
   healthCheckMode = "lazy",
   lazyHealthCheckMode = 'TimeoutOnly',
 })

newServer({
  address="9.9.9.9:853",
  tls="openssl",
  subjectName="dns.quad9.net",
  validateCertificates=true,
  checkInterval=10,
  checkTimeout=2000
})
newServer({
  address="149.112.112.112:853",
  tls="openssl",
  subjectName="dns.quad9.net",
  validateCertificates=true,
  checkInterval=10,
  checkTimeout=2000
})

 -- Routing rules
 addAction('cluster.local', PoolAction('k8s'))
