apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: theme-park
  namespace: utilities
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      theme-park:
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/theme-park
              tag: 1.17.0@sha256:df753be9371fd663795cd9784d79ba0af1ea86f69ef42774b02a9dabb67afa8c
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: '{{ .Release.Name }}.${ROOT_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - '{{ .Release.Name }}.${ROOT_DOMAIN}'
    service:
      app:
        controller: theme-park
        ports:
          http:
            port: 8080
