---
clusterName: home-cluster
talosVersion: v1.11.5
kubernetesVersion: v1.34.1
endpoint: https://cluster.habjam.xyz:6443
allowSchedulingOnneons: true
cniConfig:
  name: none
patches:
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/controller/cluster.yaml"
  - "@./patches/controller/admission-controller-patch.yaml"
  - |-
    machine:
      kubelet:
        extraMounts:
          - destination: /var/mnt/local-hostpath
            type: bind
            source: /var/mnt/local-hostpath
            options:
              - rbind
              - rshared
              - rw
          - destination: /var/mnt/host-nvme
            type: bind
            source: /var/mnt/host-nvme
            options:
              - bind
              - rshared
              - rw
nodes:
  - hostname: hydrogen0
    ipAddress: 192.168.2.50
    controlPlane: true
    installDisk: /dev/sda
    nameservers:
      - 192.168.2.1
    networkInterfaces:
      - interface: ens18
        addresses:
          - 192.168.2.50/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.1
  - hostname: neon1
    ipAddress: 192.168.2.100
    controlPlane: true
    installDisk: /dev/vda
    nameservers:
      - 192.168.2.1
    networkInterfaces:
      - interface: ens18
        addresses:
          - 192.168.2.100/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.1
  - hostname: neon2
    ipAddress: 192.168.2.101
    controlPlane: true
    installDisk: /dev/vda
    nameservers:
      - 192.168.2.1
    networkInterfaces:
      - interface: ens18
        addresses:
          - 192.168.2.101/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.1
  - hostname: neon3
    ipAddress: 192.168.2.102
    controlPlane: true
    installDisk: /dev/sda
    nameservers:
      - 192.168.2.1
    networkInterfaces:
      - interface: ens18
        addresses:
          - 192.168.2.102/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.1
controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/nfsrahead # NFS Performance
  userVolumes:
    - name: EPHEMERAL
      provisioning:
        diskSelector:
          match: system_disk
        maxSize: 50GiB
    - name: local-hostpath
      provisioning:
        diskSelector:
          match: system_disk
        minSize: 50GiB
        grow: true

    # - name: host-nvme
    #   provisioning:
    #     diskSelector:
    #       match: "!system_disk"
    #     minSize: 50GiB
    #     grow: true
