---
clusterName: home-cluster
talosVersion: v1.10.7
kubernetesVersion: v1.33.3
endpoint: https://192.168.1.224:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none
patches:
  - "@./patches/global/machine-sysctls.yaml"
  - |-
    machine:
      kubelet:
        extraMounts:
          - destination: /var/openebs/local
            type: bind
            source: /var/openebs/local
            options:
              - rbind
              - rshared
              - rw
nodes:
  - hostname: kmaster1
    ipAddress: 192.168.1.224
    controlPlane: true
    installDisk: /dev/vda
    nameservers:
      - 192.168.1.200
    networkInterfaces:
      - interface: enp1s0
        addresses:
          - 192.168.1.224/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
  - hostname: kmaster2
    ipAddress: 192.168.1.225
    controlPlane: true
    installDisk: /dev/vda
    nameservers:
      - 192.168.1.200
    networkInterfaces:
      - interface: enp1s0
        addresses:
          - 192.168.1.225/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
  - hostname: kmaster3
    ipAddress: 192.168.1.226
    controlPlane: true
    installDisk: /dev/vda
    nameservers:
      - 192.168.1.200
    networkInterfaces:
      - interface: enp1s0
        addresses:
          - 192.168.1.226/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
controlPlane:
  userVolumes:
    - name: local-hostpath
      provisioning:
        diskSelector:
          match: disk.transport == "sata"
        minSize: 19GiB
  patches:
    - |-
      - op: add
        path: /cluster/apiServer/extraArgs
        value:
          feature-gates: MutatingAdmissionPolicy=true
          runtime-config: admissionregistration.k8s.io/v1alpha1=true
      - op: add
        path: /cluster/controllerManager/extraArgs
        value:
          bind-address: 0.0.0.0
      - op: add
        path: /cluster/scheduler/extraArgs
        value:
          bind-address: 0.0.0.0
    - |-
      cluster:
        proxy:
          disabled: true
        coreDNS:
          disabled: true
