---
clusterName: home-ops
endpoint: https://192.168.1.220:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none
nodes:
  - hostname: master
    ipAddress: 192.168.1.220
    controlPlane: true
    installDisk: /dev/vda
    nameservers:
      - 192.168.1.200
    networkInterfaces:
      - interface: enp1s0
        addresses:
          - 192.168.1.220
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
        vip:
          ip: 192.168.1.220
