---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-unbound-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: opnsense-unbound-dns-secret
    template:
      data:
        OPNSENSE_API_KEY: "{{ .KEY }}"
        OPNSENSE_API_SECRET: "{{ .SECRET }}"
  dataFrom:
    - extract:
        key: opnsense-unbound-dns
