---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
spec:
  chartRef:
    kind: OCIRepository
    name: adguard
  interval: 1h
  values:
    controllers:
      adguard:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          adguard:
            image:
              repository: adguard/adguardhome
              tag: v0.107.78@sha256:1ea34eafe5dc691007946e8eaab7bf46b0de9412f39213d8c06e48b53bf9a6c5
            env:
              TZ: ${TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
          unbound:
            image:
              repository: alpinelinux/unbound
              tag: latest@sha256:7b54409d68f7550ee31b4417d76807ff6cdc274ae3acfa32d178e05c5d1cd0c6
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${ADGUARD_DNS_HOST}
        ports:
          http:
            primary: true
            port: &adguard-port 80
          dns-udp:
            port: 53
            protocol: UDP
          dns-tcp:
            port: 53
            protocol: TCP
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Utilities
          gethomepage.dev/icon: adguard-home
          gethomepage.dev/widget.type: adguard
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}` }}"
          gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_ADGUARD_USERNAME}}` }}"
          gethomepage.dev/widget.url: https://adguard.${ROOT_DOMAIN}
        forceRename: "{{ .Release.Name }}"
        hostnames:
          - "adguard.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *adguard-port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          adguard:
            adguard:
              - path: /opt/adguardhome/conf
              - path: /opt/adguardhome/work
      unbound-config:
        type: configMap
        name: unbound-configmap
        advancedMounts:
          adguard:
            unbound:
              - path: "/etc/unbound/unbound.conf"
                subPath: "unbound.conf"
      root-hints:
        type: configMap
        name: unbound-configmap
        advancedMounts:
          adguard:
            unbound:
              - path: "/var/lib/unbound/root.hints"
                subPath: "root.hints"
