apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: forgejo-admin-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        email: "{{ .email }}"
        oauthsecret: "{{ .oauthsecret }}"
  dataFrom:
    - extract:
        key: *name
