apiVersion: v1
kind: Secret
metadata:
    name: forgejo-ssh
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:9fff/sI+MnWdFGnnnUCih11VxiexTZTAcLcFzTasHUSRiIqPgtvcUaLb5cID5p+iGurU07wmz1gCm7HhLUXBOrXHnwinjPQDAOefRQ06rpBZSQDB/U7bLKHNHPHhd7BvS+ERlF+XBoSvebG2HuA2hlj8H5JvKozmr/6VsiWFYamqbVU00IjCjt3IYCwYEXNMlS4vXBKVgsoh9XH8fF/pEkZcqJybYJtJCSiJGffH5FV9MoH7kUnRp0hZZgX3K/zBZmf5S9U1g01Mqls4mU20hypwasQCwqTUSL7iBaYe0k6kYmMgO+4haHzlWTHo1KBpbZ1GjbpiM74kHIIMqRK1/Ic0x0gNTXttTRnl9X358Aq66Ot/l+0fzzys0rYtWLmoaK+KC/ca90Fe/FNICnNO4O1IR7Z85NPnza6Lyc7CSekArjew1HIp4O888fFX4eIK/e5sOvOGw/mQeGOF5smV5yyzJ9JLGxF5YYuN2hGI6aodSy8DKY6Y8XeRdKMlVnPHdHXPTUjlLPFvosCCBv21xpyaus3v5jFIDzY3PQ==,iv:3onvV32X42VsUqec7dkbt6SOP5xTPLBmMGmGVpJOr5k=,tag:ORRdU4DNgKrBc7YORF+7Sg==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYjVuRlR0TUN3T2NGZUds
            Um9nYjQ5SVoyUWpuQ3lXeHFsSmt6R0cyd2pjCnUzdHpsOG5pYVc3U1lwRVFkNDNs
            Z0hoWER3aEJ1dGlNNGV1cFNxL29OZE0KLS0tIFNWOVFEL1kxMHJwUDFFcHdJYVc1
            SmhkMCtPYXVVa1hSelNuRGR6OEk4KzAKBP15TiHfJU3jigsnRWgYdRUMNk+t3KJM
            QmrsxCiQ+XDKOZgT3pi+GGH9pRqNkXmF4E1GfB1wSi9Bx6OAfpqvxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZXRwMGRxL081TEZJRlYr
            ZnhBcEw1d0I1ZGtlWWhiWmcxeG9uYkJsTkRFClAvR3J1L2FIM0hBZjJaWDY1TTdL
            ZUJlMlhDaCtTWVpxdmxidng3cnhTVmMKLS0tIDlEYkdxYi9vcE55ZHA1a24zU3kz
            WjBNaHo1Z2tVU29aOS9RTmxhaG5qUEkKqW+XgUxURufsKUjYDUrYPCneX8kuZ4Qp
            3sMmF7cWLYD9CRS1ycvrxyr8yJUiVH8UMlaYwGOvCekWVNyrxDdG2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T03:36:12Z"
    mac: ENC[AES256_GCM,data:D4xDVOg0ZfPFFVB3pY17mbEwDoBCV4V6I9j8n6K7MjR0fTzCPdl12wiyRXEeikZcr4LKTYfBUmxxgn+n0zDlQfN5YfwvIq3eKyYXCZbjK4Kao5VJynzrvxcrxQPfhug/X0/mHKAeCS4ssRJJFMWvfejGu6AG4J/3cUkY6JmLeKE=,iv:997wVFBzFk4thouWyLOxPU/LMiLG4DSWPztprskP7Q8=,tag:kP3xypTXPWzEY/h+tIY0tQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
