# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
    namespace: downloads
type: Opaque
stringData:
    LIDARR__POSTGRES__HOST: ENC[AES256_GCM,data:hK7HPbnbFI+hGltkxx/Vtqt530w4jVxQeJ4KSFDV2E46EVIT,iv:7+8RmpR4Jyhm0jmpaU7jxduRyFTKQ5YFGfEbfebdi8I=,tag:17pIRIX8jXOB442msiIiMw==,type:str]
    LIDARR__POSTGRES__PORT: ENC[AES256_GCM,data:GR3YDw==,iv:zMiRS3+B+GwJG1c2LlOl7tO/qjQzuto/SrZgu/duxQ8=,tag:IDG4GZtqLtrMOJLUGCMO2Q==,type:str]
    LIDARR__POSTGRES__USER: ENC[AES256_GCM,data:wHbF7j0Y,iv:COK/vkosfyeb0AawxG8BrHTy06FkU4MqbX+v2YVGpxo=,tag:Ztj6QgwSbqLNtbXwm6YUkQ==,type:str]
    LIDARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:ngfoFlADl71bRtgbokpxb3p5TKbQ+oZMGw3TsAHV848=,iv:GmwQN71vYpYpjfTzTDc9IU+sXS1qDJ8pyiA3DJh1VIg=,tag:Pmg89EDWq5SHSoOfqlZN5w==,type:str]
    LIDARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:m4rcEwVENCdrw7U=,iv:Jsqizvpr79Tci3FGUdfEbTAwAUCtqC3odXqmtYmHweA=,tag:jGrtOElynMotVj371n8ccg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:u+IMKmPjzsJslt8=,iv:+0eLWHnGwYZkQT4NcJOixAIL0MYf9buPQ1aRLf/xE2U=,tag:aTelfefPz8RagYyocLWkWQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:f6jJtyDlt+EkziVDds7U4rwsY4DupKGuHRMBOe467UXAnIcG,iv:nPPdD4opxna6Em5CHLQi136xZ5sr2jBcaivB7OjUbZk=,tag:WehX9I/VlRGOaFggiIJNIQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:hUnNq22vx8Xomz2xKjVgJQvZVfguBH8tbNey8XQvB9M=,iv:3PWO/nlPQbgN7J8FeN+ZmMfihHx9/tOh8clC6A535Ck=,tag:Hlu81QNBdJzB54pkXyWWPA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:QlY0iEqs,iv:OMLBA65D1YZcaorGd5o5TWuGFUOg47iWvOERywRzIrs=,tag:io+sEhgB1w/1FvbDo2hLKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T03:19:33Z"
    mac: ENC[AES256_GCM,data:sCCTQjL1VKveqK/oDMAffJ3/so8LDk34kixwo8IprndFcPPsnm7H6lxXMMpJWiQ3cfB7HQXeTXJsuSDs5HisPJAhRB+ChV+Lvs7FZmQvuzgOawT5xFZptwBmn19exqxETVQfuCcU7JksYEX5ncNi8IJOHDisvrV3U2NWR0hJbi0=,iv:ty6XOFt8NKr7jRhbw/upeaub8EiAL/hk29vIw1JssNk=,tag:vwpD2zbVr5WIiiETdbXMfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
