# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: conduit-registration-secret
type: Opaque
stringData:
    TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:zjddAo1kJqDOQyJHSGi9Zd6XlF+p16wAzLoSUxKi0Pf740HpR+Wh8GcIhI0ZcMcC,iv:REe0Pf0VKNFGZ0FYoUcu4I/8flUgTz8yxM+bBMtTRJQ=,tag:QgxLt7GsP9gE3UpwzDiioQ==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T13:52:26Z"
    mac: ENC[AES256_GCM,data:Ri/Qx+FPv6D46cuABSA0Yg1Pb5Ch2VNV0tQxzWu9CFT2ZV0pSo8FCCoqiBCLIGEloDS2zHsc0Ie4tJqZCf88itGkKV+9mIsYeroWBGKVpT1XHJirfdlykNL/dqZUmyLcd0C4ta5wYTGp15NLpykUMtJ5jBHEParA0kJtxEy+dJI=,iv:vliiVEkJUmLe8ksfHGiwggId6h0WAyrTyfQWFEiiO0w=,tag:b3W5nBlFyPbhIuedh4BsHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
