apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: crunchy-postgres
    namespace: dev
stringData:
    s3.conf: ENC[AES256_GCM,data:q3W+O5zSpLjAE+RyZQF8F5yLFYP1wGIFS9S/YGNg37aOCJLGP02ij8p4Bu6eUI9H3QThILVArZhDSiVt7idjwlxoHRHfhhrOnfrb6yOK0y6zvewFecZRTtWa50T8yBQaxOlosg==,iv:9oZ5+6mON7WSYIN4ogSIRd+8CAMYwzMpq5QT/UW5UnA=,tag:vd6UD0JVi6O2Jk3Im0VmLg==,type:str]
    encryption.conf: ENC[AES256_GCM,data:u15ivJ+0GUTq0QFNmVhtN4a+bS0xQAvLG1ig5OL7N71UM3Iy0iwhV0ZGlZrDDV6tb2nPkdqYsgmaSjz0,iv:z84AE2546LRsrXofJ9yoC9soHnW6WoLEYKaCZf5Xfmk=,tag:VC/U7FFEO3KQL7augkTAMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UzV0WGUvc3BSWE9UdFpn
            ODM2QXNWczNnYTIycHd1V1R5ZytIaEJjaERNCkVSTDllRDcyNWRtTERSWWVXQ2oz
            RnJ6UnhYUE1LMWNTM2V1MVhvbTZNYW8KLS0tIGd2VHh2b2JqN2t1TXVSOC9MNzlE
            YlYvMG1VVlRrcnBWUUxhRUE1bGQySFkKla+ySMNyHM+YdbBjROTX5mA0MNCTvqXH
            RnMHwoLvHTZK8uVXo1LHO7S+TQmzcFG6CnUTQfKc8U97eus5nqm8pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZCsrd0U0eG1LbWpCZnBv
            Tm5oYWRXRVBvRnNTMUdkRlIxQ0Z2TERLaVUwCmFYKytoV0JGQVpvemhDS0g2V0tR
            YXpwRW5Yd1AwQ2wveGUxKzYrNzh2TTgKLS0tIEk5Ynl2NzNNMjNYWTRsamR1Vk53
            T21rL1ZMdzlNTmVLb0Ixdlh2clYyVFUKD6Zosa3uSVi4124AudUXuI5AucyqnvNm
            EO+aYm3pMs2RJoomZDJycERrH4QRXMEdibuuvzL/FZSmWpwPcn+iNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T00:08:56Z"
    mac: ENC[AES256_GCM,data:9D6rr+QZM1q5QeeCUnaUHLGwh2i/GYWFppxFX0CWX7o27+RFxql6RodQRtcXXtUlMRwsJ4InMr/c86jEHc73cbz2B778HiK9Ka7HPsz+EPl3KDUoJA1CIyobXJV5n/TfjborYWn6xiDuCz636mc4xTk+Gd+3mPiqzHkmIoF8w8M=,iv:sc1Oe/vy3jSDdNxxa8y5bKkJD8w7qd7UGYm7WC5rgcA=,tag:ioZ77pdh5IADkggIAMSEkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
