---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: homepage-secret
    template:
      data:
        KOMODO_KEY: "{{ .KOMODO_KEY }}"
        KOMODO_SECRET: "{{ .KOMODO_SECRET }}"
        RADARR_API_KEY:  "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY:  "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: komodo
    - extract:
        key: radarr
    - extract:
        key: sonarr
