apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.2
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      sonarr:
        containers:
          app:
            env:
              PGID: "568"
              PUID: "568"
              SONARR__LOG__DBENABLED: "False"
              SONARR__LOG__LEVEL: info
              TZ: Asia/Singapore
            envFrom:
              - secretRef:
                  name: sonarr-secret
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.13.2934@sha256:d871b5816748ecca49e322b905b399d5aaf2ef36fa3ec45179f785f2c5861a41
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${ROOT_DOMAIN}/css/base/sonarr/dracula.css"></head>';
            sub_filter_once on;
        className: internal
        enabled: true
        hosts:
          - host: sonarr.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - sonarr.${ROOT_DOMAIN}
    persistence:
      config:
        enabled: true
        path: ${NFS_PATH}/arrs/sonarr
        server: ${NFS_HOST}
        type: nfs
      media:
        enabled: true
        path: /mnt/raid/media/qbittorrent/downloads
        server: ${NFS_HOST}
        type: nfs
      sabnzbd:
        enabled: true
        path: /mnt/raid/media/sabnzbd/downloads
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: sonarr
        ports:
          http:
            port: 8989
