---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app slskd
spec:
  chartRef:
    kind: OCIRepository
    name: slskd
  interval: 1h
  values:
    controllers:
      slskd:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
          # Configure the gluetun sidecar
        containers:
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
            env:
              DOT: "off"
              DNS_ADDRESS: "172.16.0.53"
              FIREWALL_DEBUG: "on"
              FIREWALL_INPUT_PORTS: "80"
              FIREWALL_OUTBOUND_SUBNETS: 10.244.0.0/16,172.16.0.53/32
              VPN_INTERFACE: wg0
              VPN_SERVICE_PROVIDER: protonvpn
              VPN_TYPE: wireguard
              VPN_PORT_FORWARDING: "on"
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              VPN_PORT_FORWARDING_UP_COMMAND: >-
                /bin/sh -c "wget -O- --retry-connrefused --method=PATCH --header='Content-Type: application/json' --body-data='{\"soulseek\": {\"listenPort\": '$PORTS'}}' http://127.0.0.1/api/v0/options"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            lifecycle:
              postStart:
                exec:
                  # See: https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/kubernetes.md#adding-ipv6-rule--file-exists
                  command:
                    [
                      "/bin/sh",
                      "-c",
                      "(ip rule del table 51820; ip -6 rule del table 51820) || true",
                    ]
            securityContext:
              capabilities: { add: ["NET_ADMIN", "NET_RAW"] }
              readOnlyRootFilesystem: false
              runAsNonRoot: false
              runAsUser: 0
          app:
            image:
              repository: ghcr.io/slskd/slskd
              tag: 0.25.1@sha256:ab9ed50e028b524cefdb7c1dd8ebca368a076e18441ee8ac2326473eb850b4c3
            env:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              TZ: ${TIMEZONE}
              SLSKD_APP_DIR: /config
              SLSKD_REMOTE_CONFIGURATION: true
              SLSKD_HTTP_PORT: &port 80
              SLSKD_NO_AUTH: true
              SLSKD_NO_HTTPS: true
              SLSKD_NO_VERSION_CHECK: true
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
        statefulset:
          volumeClaimTemplates:
            - name: config
              storageClass: ceph-block
              accessMode: ReadWriteOnce
              size: 5Gi
    configMaps:
      config:
        data:
          slskd.yml: |-
            directories:
              downloads: /media/slskd/complete
              incomplete: /media/slskd/incomplete
            permissions:
              file:
                mode: 750
            shares:
              directories:
                - /media/slskd/shared
              filters:
                - \.ini$
                - Thumbs.db$
                - \.DS_Store$
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /config/slskd.yml
            subPath: slskd.yml
      coredns:
        type: configMap
        name: slskd-coredns
        advancedMounts:
          slskd:
            coredns:
              - path: /etc/coredns/Corefile
                subPath: Corefile
      media:
        globalMounts:
          - path: /media
        path: /media/downloads
        server: ${NFS_HOST}
        type: nfs
      tmp:
        type: emptyDir
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: *app
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        primary: true
        ports:
          http:
            port: *port
