---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app databasus
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/utilities/databasus/app
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: utilities
  wait: false
