---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "lithium-${OLD_DOMAIN/./-}-production"
spec:
  secretName: "lithium-${OLD_DOMAIN/./-}-prod-tls"
  issuerRef:
    name: letsencrypt-prod-clusterissuer
    kind: ClusterIssuer
  commonName: "lithium.${OLD_DOMAIN}"
  dnsNames: ["lithium.${OLD_DOMAIN}", "*.lithium.${OLD_DOMAIN}"]
