apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: utilities
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.7.3@sha256:49edf11a71f1c6b8787dc5b190252d7a2e72e40d93091011be26d2162b1cdff6
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 10m
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: hass.${ROOT_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - hass.${ROOT_DOMAIN}
    persistence:
      config:
        enabled: true
        path: ${NFS_PATH}/home-assistant
        server: ${NFS_HOST}
        type: nfs
      tmp:
        type: emptyDir
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
