apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: utilities
type: Opaque
stringData:
    HASS_LATITUDE: ENC[AES256_GCM,data:ZyPIUOdYnQ==,iv:TLcpz7elViaBDpYG/HpYW2e6SV5/kjhBgup1EyRvDAY=,tag:zyPi/uLxlNQfNAe7FuIOcw==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:NWC63aPouLsj,iv:Jv3WxBjY0T//QQ2EI8lAWX33PkeyYfBlfuW8tDGYtEg=,tag:0bckJfWGKJm3TzQU7FFu0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTFJrTEp3bUNvVTVlQmN6
            M0hCd0lxU0NGcEJ3VHd3YzNnT1FkTFh6VERZCjYzbjBEN1BVbkIzUUx3Tkp5ZUlC
            ZCtvZXRGMEJCWVlpcWl6bDJadlZJZkkKLS0tIHRVQ0prbFBGYlAxZWpIVTViTnRo
            RUhGaGxBSDJTdW5uRWRrUnFlcCtaYXcKeO29S0cIZkiLU0/p6rEdaTAoynbsHpbq
            IRGVbEFAWJxgTHEETz+i0vHKEzqQeT1x4bYP47PpozPQrCR+LnhYig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc1dJZEh5Nk1OdlJzMGF4
            WkpTdnI1SVlHSFkyUXR4TmhkRWRNdjl5Q2hnCmJYTTArN3dTVDZ6SFhHOFNQNUlk
            MEdFMkhQYk1QTUcwMjZiQjFONjBRdFUKLS0tIDRzZjd1L09DZ0JGenpVbWdDZDBq
            U0ZWWHZpcmtReW1mdjlwV1RPU1JYWmMKNTJQPkmWgmHlYah59ykN1iNPhbFSRGYf
            4yH0aOn8xfVbwooNGohy4fo+sjT3T+P5xZJXescxFM2LhNPuF6VaRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T05:41:09Z"
    mac: ENC[AES256_GCM,data:WjkPPtbgXWSRCcpI3UzvI3KQkSByB8IiWM14UvZ23VegHS/qm8QuWqNcH/08f0Dgq5P2Lf4PNIkwk+wEg6Gqf84jNZ9sZsErjhTzQToqQUDpmvdo8oIJ7lw8pRwgbT8q+hpGuuFaOPYAetd4dAmE12sbF3uqBw+nX4g9VV5ZJhw=,iv:uHAvKMDtTprvE2TgpeKWKo3F9GAJrTOGYoDwpsGqzjM=,tag:QbUIqemKKxMGKrdc5+1FRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
