---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kite
spec:
  chartRef:
    kind: OCIRepository
    name: kite
  interval: 1h
  values:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    httpRoutes:
      - name: kite
        hostnames: ["{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}"]
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    secret:
      create: false
      existingSecret: kite-secret
