# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kite-secret
type: Opaque
stringData:
    DB_DSN: ENC[AES256_GCM,data:B0kpNZO0hpPREKdO7HbtPw1k7G1anefFt4/mpP4o1Cyb6TEtwx5JchgcM46GVHq7ub8x7RZZpOWA70ObsI73BpRC0vGRo5wXZ8+SbPaqyLZO1XNcHB8kZ2wbD3PORw==,iv:S/ztrnUmNdsbBjHS7RG9zPJVMPt8rCsp7Y3vS4F3SxU=,tag:Aymo46WcwMW8TnM/xD1U8w==,type:str]
    DB_TYPE: ENC[AES256_GCM,data:8kfGhncmpXg=,iv:ZsNIsp75hhOpMd78pAOBZzxWyUHJ8rJu9Wpo8WqECDY=,tag:B/WHYvwvmkich8vh8uVSPQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:3b+qT+NUMNRo1XTLrxZjRa9p8hqgkbII2fN6DJ6buyk=,iv:oZv2/HdQVqnLi9T5yPSwU/adfzKTcA7D56qr5fV5tzc=,tag:IArilqseVEEF0NJoXnKqvg==,type:str]
    KITE_USERNAME: ENC[AES256_GCM,data:Gokeeg==,iv:iWgbh0StRI2v+ObkFBGUZhRtx/6k8m+wxgMGrExDbJk=,tag:ULAaL8R5LMJan7jDurxn6A==,type:str]
    KITE_PASSWORD: ENC[AES256_GCM,data:uNGn6Gx8lICA35g3KWZ3YBqozIz3H0Ob,iv:pRtjhFIwTDSZIupKZD1eWSFlmKbvt6uT648ms61mItw=,tag:HvfDhIr1pSMlKFNH6jt+tw==,type:str]
    KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:/fhXShVw50PLDnHogd8gMw6yu8pXv7WIvMm+gCT/SRY=,iv:qldQ9q671wPY5AYn1n0QQ8Z1qH7viZNM/WALuszyfZk=,tag:fIpo+47jYHKtFbe5hW07lw==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2U1eHMwQUprMWtLNk12
            YlIxczZuUGhwbi9kbXpGUjVjRGIyQ2JUT1NZCnhIVVFhdUltOE00Y0xiYzBZVXVu
            QS9IRitkazg2VjVpbVdPYlBrTjFYVXcKLS0tIGRUd3l2K0ZsV2lubmpGbnkwN1BS
            ZDVma0NnZnVXcE9KSmVVb1BqR0o4NGMK9mvf1zKbdu/xKk04Tty0ejpmzz509cJs
            V+qJj2IXrYAU6xd9XvSZYz6UJIyMifAmVEl2wy4Fdgw2rPkNTwCdlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDZKdzJxL0tVY2FIeWJX
            YUo1TTVYNmZiUXJyQWl3K3praDAyRGNjQUVBCnp6TW5MZTJkd1h6UWc3UlBCTTI1
            NldVbnBhZEdXbEtTaExPcktEa09uckUKLS0tIGFNNmhoVmsxZjR6d2NwenRGQi9k
            RmtpK251d3BDSUh0QjJvWng5UGEwcFkKhtaXqGkxuCw2Y0myGeCCKbXh8WjFnRww
            SYj0Q80K/6fAiuPWsC+JlZ8ZnjPQVCrT+YTTEDkx5ZQI/9mVUi7Itw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T09:14:31Z"
    mac: ENC[AES256_GCM,data:CJyMM8Ga9aeai4cvg4BjY1kXFzplUOue9+O1ucsuSy7awxiZPEkRCifV0SuckpBoUkbG9BWrrn7esrvE+6OKC51CJ/mr4GiVTVFN/XTUsKknI4hueQLR/n0DGGPZIuY1L59F0S554Th3gi80Q61zwHkiQCNaMgKnoxWi6KM3cjI=,iv:L7nNfBuYjNMsoezgL9pqYNngy1N5SBw7pYomYVx56Fo=,tag:Sx0ionPouVIfOSIadFatHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
