---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "podfetch-pguser-secret"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: podfetch-secret
    template:
      data:
        DATABASE_URL: postgres://${APP}:{{ .${APP}_postgres_password }}@${CNPG_NAME:=cluster-18}-rw.database.svc.cluster.local:5432/${APP}
  dataFrom:
    - extract:
        key: cloudnative-pg-users
