---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: podfetch
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: podfetch-secret
    template:
      data:
        DATABASE_URL: postgres://podfecth:{{ .podfetch_postgres_password }}@$cluster-18-rw.database.svc.cluster.local:5432/podfetch
  dataFrom:
    - extract:
        key: cloudnative-pg-users
