apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app planka
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      planka:
        containers:
          app:
            envFrom:
              - secretRef:
                  name: planka
            image:
              repository: ghcr.io/plankanban/planka
              tag: 1.24.4@sha256:b5825120d00d8e6f6603e866cbece373a72ca6c46006b67d7640a2040bc1d8df
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host '{{ .Release.Name }}.${ROOT_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: planka-pvc
        advancedMounts:
          planka:
            app:
            - path: /app/public/user-avatars
              subPath: user-avatars
            - path: /app/private/attachments
              subPath: attachments
            - path: /app/public/project-background-images
              subPath: project-background-images
    service:
      app:
        controller: *app
        ports:
          http:
            port: 1337
