apiVersion: v1
kind: Secret
metadata:
    name: planka
    namespace: selfhosted
stringData:
    BASE_URL: ENC[AES256_GCM,data:9a3hh9rSHN1oQ3m4T7inPIKteCA+RQfPLhcq2Gm9,iv:jqlMLqsa6W49ybwJPuKMqWLpekXbA8OXginUh/dPhLA=,tag:wzJwMY3716XHdtRcFktO3A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:dlIGR46P1+x6OOKz6bCDnpxA9/uDPesHbc9lfWzfbJRqkO27371ByIzdoo8oqZKeBf3heTra+11NHw8B,iv:JhJtLymBikiRn2VTbyvQ3AVQkOpRaWgrkaAYZjdFjPI=,tag:bltHCMpW6HHdMwsBO7Yc7Q==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:FHNRhTyzf+eT1Za4,iv:0rYfhOG7B8sVrSRGggTy98z5VO6OILv0aXDlsFhxNUc=,tag:v0X6C6S+vP1hVEY/NvSApA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibEFjWGg5TmhSWThXRWhJ
            UFgzVlNEVzhxSElJNkxPUWJLamhkUlBJWEZ3ClYzaE1JSGZiYzVidWhLRTJPajU5
            TGZQRnlYK3JhTFMvblJyYS81eWhtcVEKLS0tIGtqcnZtTmlJejRBeE1aaFcvZlNH
            S1JVYXJ4UUFmRXI3OHlyemhlU0lReTgKgjN2Qu0uZiwVwrN0hS0z/WJIzoYWFenK
            3Ew0jHqw/wXncQ/N3RysOAJ6yY3ZdX2d7DMuG7XaL4HMJSeLMEKasQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab3V2U210OTg4WXZMQW1K
            Wkp2N0FGbUNrVVEzdUk4aVJHRmNvbUkzUlhZCm5RQytvMFpFZmlDSmJOY1VxbWRI
            NkYwbVNSZkhwMUFhQlcvVmRCVEFVVjAKLS0tIFlwR2JqaEo5Q0MyTmZQYVFmcldl
            aFJNOWV3VStta3R0cXpYV2tHYnRBWWcKgouBQBsJoug3C4BRpwmMGi5uIYaskkY2
            5YlZYPq7X09q5y8twkoGmdpAPaU4JOPmEDKCw2O0Rw/RrAFSgycFyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T21:14:09Z"
    mac: ENC[AES256_GCM,data:ovi2OkxPYLkayYnbkGvhyw62cY75htxa+jrzn79CXQOoP8fpcao18E0O4T7mZb0sr8qx0CXjTN1gqiMoGqMYwQjp0Z8e6w840dW872RaNa5LrkJp4lrAGrUdSOMzswx6DGhulpULpL+npgaMa8uMN1Ecv2bO4DtSMgYBRlBBNrA=,iv:50gzNUvbze1C/3jA1cO0xwxJPtplVUpPLVmVC4zYyR4=,tag:0BJd/SVx/rnzyj8pA+LNRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
