# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:/vgMD0+HjGE7YoEvzaGm3a25x4N0slP2,iv:CD2Pr9rDRnH5/KT8+1QAxOU4vy8y2nGXKGKArd0iF7M=,tag:7KQHrMZg/BTuKHNdqZ3mQw==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYkxtZE9wS3NrM0RDRUx4
            dnQrbitEakpRa0N5VXFXNENFMGdqMlc4bmdZClpKbDRZaWtGVTZsVXl0U2tMZGZw
            cUxHTnBLREIxK0VsLzNkMy96VkF3dUkKLS0tIFpOdGNIUkZraVlrM1UzRlFTRjZl
            Slo2OXVQeFRrT2JvKy9uOVNUSUpkRFEKusjolKMWpOmAvu4uwf1ezAVcMgmH+z16
            RZ/+MymL9jEAJwFO8VK2NuNiKpsd1oze9ZV5JQZCWFAohdKBIELULg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NmlPR3RORjdsRXpHVWUw
            cDZtLzZVNE1uOTBEVUZvcHRBcEh0RkxjMlhFCnY0ZG5rNnJQUTF6aUt4UFBTdXRr
            eG10Tlk5N1AwL0NFak5vZkkwa0hxS1EKLS0tIEYybE9nWVlNcTBtVWdMb2djUGdW
            YzROaFlNTDVpcC9TRGpaaG1yOFhLbkUKAmXHlr0GO4Tjr0kuqe2IVi9EF/j2cBcC
            +fRmjRW/e4pArwBCoY9iiJ+0CjEmcR8ykilARHIJZ1pe4akHAz68Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T21:05:10Z"
    mac: ENC[AES256_GCM,data:9aF0x9iHEb5Aav+BvXiml72NzLpDnZOM/Alan7OPyu2tM7rhAIrLGkDLJGRW6kfz30ZsOhPFu5FRL6V6el5MCeksRcUdtFn+VmEzcdB+zkAwBFGY46OL4wAM9c5mmYFxhdmnU4aIWVVGwlQdGi+Nt9WoRIuj91mCBYBD8G6lz7U=,iv:o28Y0afNeHc4wznuhpiVZCJBwdUx8K37QerE5pHFIGY=,tag:U2BeA2Ss7KxaJlfeUUqLcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
