# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: opencloud-secret
    template:
      data:
        STORAGE_USERS_DECOMPOSEDS3_ACCESS_KEY: "{{ .ACCESS_KEY }}"
        STORAGE_USERS_DECOMPOSEDS3_BUCKET: opencloud
        STORAGE_USERS_DECOMPOSEDS3_ENDPOINT: https://s3.${ROOT_DOMAIN}
        STORAGE_USERS_DECOMPOSEDS3_REGION: us-east-1
        STORAGE_USERS_DECOMPOSEDS3_SECRET_KEY: "{{ .SECRET_KEY }} "
  dataFrom:
    - extract:
        key: opencloud
