---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: opencloud-posixfs-pv-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.2
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: "${NFS_HOST}${NVME_NFS_PATH}#opencloud-posixfs#"
    volumeAttributes:
      server: "${NFS_HOST}"
      share: "${NVME_NFS_PATH}/opencloud/posixfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-posixfs-pvc
  namespace: cloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-csi
  volumeName: opencloud-posixfs-pv-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: opencloud-pv-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.2
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: "${NFS_HOST}${NVME_NFS_PATH}#opencloud#"
    volumeAttributes:
      server: "${NFS_HOST}"
      share: "${NVME_NFS_PATH}/opencloud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-pvc
  namespace: cloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-csi
  volumeName: opencloud-pv-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: opencloud-config-pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.2
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: "${NFS_HOST}${NVME_NFS_PATH}#opencloud-config#"
    volumeAttributes:
      server: "${NFS_HOST}"
      share: "${NVME_NFS_PATH}/opencloud/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-config-pvc
  namespace: cloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
  volumeName: opencloud-config-pv-nfs
