apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
    namespace: utilities
stringData:
    secret.yaml: ENC[AES256_GCM,data:l7zvp5A/S8Hgof53wy/meyDRP9b1ofgSAkbR4nLwS7RJjpBnh784oKKrgZ65t6DGJFGIEVIlXcZqj+YkX7dD+28jntsmSE9sK0PXUbPh2K5i7hvnqfdeAgGMH8r0RT7uR1iLHpeN9ifC1eKyyPXm/W4AV/aPIuONLT/36h4QH+NE+7IJ2qGeN7nLVCaZGVH6dwXzdCBXH/yNyP965PQhEU3ohqXu2HUM0bKdNxs/mCB2jTg/zwNQQt0aQZ6/lfy92oaC3AutY19UzztIuGUmdfoaSv4xGO7M6S2+G9zADDQB5VQobossWPbkKuwVR8Z3cs09uKN82oAYKRuczzWWJLqHWKNHqm0gAb4jKPubPh7dRpe62cBailC02v8KqYp/Vf5y6pZIxQNjT2wnlVoNniucZxX3P2sUUKDFadukMO9MOqKu0gpyz0vTWFthc6VAyTjBdjIGMjzw9upuQHT5yZuoOg==,iv:3O0YxD5018LQ4FT+17Lve5VzQh0TxkcnCMIzN1cMWnc=,tag:EDdWPzJfoQ3fX0LDzglakA==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaUcyZE5ESFM5OU9RdzhM
            cW5wdUNIMjQ2ODhnaVlZN2dHY0NyRnFETVNjCitoRVM3MkgrTldzVjY3b3V4c2hq
            a2E2ZXJGT2F3UVgzbFRXcjBSWlI3N1UKLS0tIFRvVldQZWpOSFdvajJWdlU1cHJu
            MytYTFBVN2FjM1Y1VnhYaEtaSzgzSncKi4OeLDasOZh0AUhgukrVEbIyBKhbf22B
            B3adR//PfQfLu8dF7DWh0g3kDYnr2cbJRMffSD8yNAs+zcTtFq83HA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVU13MDVVS09qMkQwbUZD
            VWRzcUw5Ri9XcEVJZXZ3cE9MQllJQlIxamxvCjg4amxkbC9KMTYrKy9lZEhKTTgr
            cnZBRWRYTUMvMmsxUjUwTjVjTU9Md1UKLS0tIExyRHZNMXRrMXc4ZWNLMzhpZklP
            ZmNkcURIQVFUK1dMNS9zTjdSM2VJR1EK+wk7tm4ZnSS6Hvq25U+E1vfJTBKGG+DV
            fvlmIQKp10LWsDUYEzfOLFzkZFSsan9JuEIajZku24MwYAnGUnanLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:16:00Z"
    mac: ENC[AES256_GCM,data:prkvNIgb5snxYBq8IGaOLvq5TgY/Pm3+C0a6yqEhIliQE2D8jAYLzD2rWqir+GkxXMnXDKGHqMQPMqQl926yKHuYSRnt38kv/aslmtB4ueeqTdXjf7XmgYrUQ8qGrWCxfWdPluX1zbOsqBIepmCNYzafMSak8Lh6bkaa8pRjuOw=,iv:q0/duubXxKjqZEJT7NOmqec0FEwjfLLvcRXLBGpczaY=,tag:sJRYfDq3iz9oCXiau8PtyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
