apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 16.4.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      postgresql:
        auth:
          postgresPassword: ${POSTGRESQL_PASSWORD}
    image:
      tag: 16.3.0@sha256:865e341baf49006e32b3e72254a15a81c939178cb9c48fcd9faf1c0ac4b49664
    primary:
      initdb:
        scriptsSecret: postgresql-init
      persistence:
        enabled: true
        existingClaim: postgresql-pvc
      extendedConfiguration: |-
        huge_pages = off
      extraVolumeMounts:
        - name: pg-sample-config
          mountPath: /opt/bitnami/postgresql/share/postgresql.conf.sample
          subPath: postgresql.conf.sample
      extraVolumes:
        - configMap:
            name: pg-sample-config
          name: pg-sample-config
      resources:
        requests:
          cpu: 15m
          memory: 349M
        limits:
          cpu: 396m
          memory: 400M
    extraDeploy:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: pg-sample-config
        data:
          postgresql.conf.sample: |-
            huge_pages = off
    volumePermissions:
      securityContext:
        runAsUser: 1000
        fsGroup: 0
