apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app navidrome
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      navidrome:
        containers:
          app:
            env:
              ND_DATAFOLDER: /config
              ND_MUSICFOLDER: /music
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.54.2@sha256:d6b2288fb7311ce81e1eaa01e72f9c201c34893627b07e4813b4059dbb5a064d
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host navidrome.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        path: ${NFS_PATH}/navidrome/config
        server: ${NFS_HOST}
        type: nfs
      music:
        enabled: true
        path: ${NFS_PATH}/navidrome/media
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: *app
        ports:
          http:
            port: 4533
