apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app navidrome
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.6.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      navidrome:
        containers:
          app:
            env:
              ND_DATAFOLDER: /config
              ND_MUSICFOLDER: /music
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.54.3@sha256:4915ec6ad11ff76167491654184dfb7bbf341042fea498c20b2534af3dde587f
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host navidrome.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        path: ${NFS_PATH}/navidrome/config
        server: ${NFS_HOST}
        type: nfs
      music:
        enabled: true
        path: ${NFS_PATH}/navidrome/media
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: *app
        ports:
          http:
            port: 4533
