---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloud
  # - default
  - database
  - external-secrets
  - flux-system
  - kube-system
  # - longhorn
  # - media
  - network
  - openebs-system
  - rook-ceph
  - utilities
  - volsync-system
