apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      jellyfin:
        containers:
          app:
            env:
              - name: NVIDIA_VISIBLE_DEVICES
                value: all
              - name: NVIDIA_DRIVER_CAPABILITIES
                value: all
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.9.6@sha256:918f993047ad43e6f240f78bc83734f6478c673d73cbebd50fdc8802ab05e6a1
            resources:
              limits:
                memory: 6000Mi
              requests:
                cpu: 100m
                memory: 1000Mi
        initContainers:
          init-permission:
            command:
              - sh
              - -c
              - chown -R 568:568 /media
              - chown -R 568:568 /transcodes
            image:
              repository: ghcr.io/cbc02009/busybox
              tag: 1.36.1
            securityContext:
              runAsUser: 0
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsUser: 568
            supplementalGroups:
              - 65539
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: jellyfin.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - jellyfin.${ROOT_DOMAIN}
    persistence:
      audio:
        enabled: true
        globalMounts:
          - path: /mnt/audio
        path: ${NFS_PATH}/navidrome/media
        server: ${NFS_HOST}
        type: nfs
      config:
        enabled: true
        path: ${NFS_PATH}/jellyfin/config
        server: ${NFS_HOST}
        type: nfs
      media:
        enabled: true
        globalMounts:
          - path: /media
        path: /mnt/raid/media/qbittorrent/downloads
        server: ${NFS_HOST}
        type: nfs
      metube:
        enabled: true
        globalMounts:
          - path: /mnt/metube
        path: /mnt/raid/media/metube
        server: ${NFS_HOST}
        type: nfs
      transcodes:
        enabled: true
        type: emptyDir
        globalMounts:
           - path: /transcodes
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096
