apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.10.3@sha256:17c3a8d9dddb97789b5f37112840ebf96566442c14d4754193a6c2eb154bc221
            resources:
              requests:
                cpu: 100m
              limits:
                gpu.intel.com/i915: 1
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsUser: 568
            supplementalGroups:
              - 65539
              - 44 # video
              - 105 # render
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: jellyfin.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - jellyfin.${ROOT_DOMAIN}
    persistence:
      audio:
        enabled: true
        globalMounts:
          - path: /mnt/audio
        path: ${NFS_PATH}/navidrome/media
        server: ${NFS_HOST}
        type: nfs
      config:
        enabled: true
        path: ${NFS_PATH}/jellyfin/config
        server: ${NFS_HOST}
        type: nfs
      media:
        enabled: true
        globalMounts:
          - path: /media
        path: /mnt/raid/media/qbittorrent/downloads
        server: ${NFS_HOST}
        type: nfs
      metube:
        enabled: true
        globalMounts:
          - path: /mnt/metube
        path: /mnt/raid/media/metube
        server: ${NFS_HOST}
        type: nfs
      youtube:
        enabled: true
        globalMounts:
          - path: /mnt/youtube
        path: /mnt/raid/media/youtube
        server: ${NFS_HOST}
        type: nfs
      transcodes:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /transcodes
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096
