apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      valkey:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: valkey/valkey
              tag: 8-alpine@sha256:3f8c9cc84611ec9954a339793262ad96af9bebd3599e8712271309013ec1be3c
    service:
      app:
        controller: valkey
        ports:
          tcp:
            port: 6379
