apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app eddrit
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.2
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      eddrit:
        containers:
          app:
            env:
              VALKEY_URL: valkey://valkey.default.svc.cluster.local
            image:
              repository: ghcr.io/corenting/eddrit
              tag: 0.9.4@sha256:95df062b2808c6d0bf270e7bd11e0d56c0fbee4a18c52a4a16e9e806d66f6244
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${ROOT_DOMAIN}
        className: external
        enabled: true
        hosts:
          - host: &host "{{ .Release.Name }}.${ROOT_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
