apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app eddrit
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.6.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      eddrit:
        containers:
          app:
            env:
              VALKEY_URL: valkey://valkey.default.svc.cluster.local
            image:
              repository: ghcr.io/corenting/eddrit
              tag: 0.9.1@sha256:f4d3d0ec4c70be85867aeb582cab7bb31be06f278763dfdb0291d17527aac393
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${ROOT_DOMAIN}
        className: external
        enabled: true
        hosts:
          - host: &host "{{ .Release.Name }}.${ROOT_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
