apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stump
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.3.2
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      stump:
        containers:
          app:
            env:
              PGID: 1000
              PUID: 1000
              STUMP_PORT: 10801
            image:
              pullPolicy: IfNotPresent
              repository: aaronleopold/stump
              tag: nightly@sha256:01c044aabf217b5cffb79f1077391bca8b689984088e51c55295d0da9553234a
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: &host stump.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        path: ${NFS_PATH}/stump
        server: ${NFS_HOST}
        type: nfs
      data:
        enabled: true
        path: ${MEDIA_PATH}/books
        server: ${NFS_HOST}
        type: nfs
    service:
      app:
        controller: *app
        ports:
          http:
            port: 10801
