---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portabase
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: portabase-secret
    template:
      data:
        PROJECT_SECRET: "{{ .PORTABASE_SECRET }}"
  dataFrom:
    - extract:
        key: portabase
