---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app portabase
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      portabase:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "18"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-initdb-secret"
        containers:
          app:
            env:
              PROJECT_URL: https://{{ .Release.Name }}.${ROOT_DOMAIN}
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-pguser-secret"
                    key: uri
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            image:
              repository: portabase/portabase
              tag: 1.15.5@sha256:2ccd67790d51c9523a226cd5d2afb9ccbd282f9793665d2714b5f07f9b2f7631
        pod:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      data:
        existingClaim: *app
      nginx:
        type: emptyDir
        advancedMounts:
          portabase:
            app:
              - path: /var/cache/nginx/
                subPath: nginx
              - path: /var/lib/nginx
                subPath: body
              - path: /var/log/nginx/
                subPath: log/nginx
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 80
