apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app frigate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
    controllers:
      frigate:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
              USE_FP16: "False"
              YOLO_MODELS: yolov4-tiny-416
            envFrom:
              - secretRef:
                  name: frigate-secret
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.16.0-rc1@sha256:994bdb674fcb665e259a5f74d17c9f357c0d31e3fd2f2a48da361df93d2b522a
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: &port 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 600
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 100m
            securityContext:
              privileged:
                true
        pod:
          nodeSelector:
            feature.node.kubernetes.io/custom-google-coral: "true"
    persistence:
      cache:
        enabled: true
        globalMounts:
          - path: /dev/shm
        medium: Memory
        sizeLimit: 4Gi
        type: emptyDir
      config:
        globalMounts:
          - path: /data
        path: ${NFS_PATH}/frigate
        server: ${NFS_HOST}
        type: nfs
      config-file:
        globalMounts:
          - path: /config/config.yml
            readOnly: true
            subPath: config.yml
        name: frigate-configmap
        type: configMap
    route:
      app:
        hostnames:
        - '{{ .Release.Name }}.${ROOT_DOMAIN}'
        parentRefs:
        - name: envoy-internal
          namespace: network
    service:
      app:
        controller: frigate
        ports:
          http:
            port: *port
          rtsp:
            port: 8554
