apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: utilities
type: Opaque
stringData:
    FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:dd9mEzA=,iv:uYbxYQl5esgMADGz1J9nr/2hwtMH9TfGm+87ePm5fOg=,tag:BLzihe2edy1w+Kdid1Y36Q==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:CZO2kspMxgcbLGRq+0DHxOOMow8Hifhw,iv:CLWPmz3qOIaXxRbCPSyXSsaTaCMsnE+yaSWIhX3W34A=,tag:jDaK8L5MssULjd7ofUeY5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTTVPRUV3RGQ0T29PWHFO
            bmFncGxRLzlhK0FoblVyMzNaRGJQNGZsNUc4CnB1Mk9Hd3lTV0plQ1QxZWJDTERH
            S0ZwMHNHd0dpdnNPdkdwODFMU0duUmsKLS0tIFJUWXdrdkoxU3RQejd2a3EwR3Nq
            MmYvTTNwNW1XT0Z6RlRJRWVhdlZJYjgKkg5RsFui5WjujVGu9rnfJy4/eJ8MMH4L
            CPk0OPPqeJcPoYa2cRaDVQs9UQcIb1KhkS+RSsRiVCRDGL9eUIZxeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaU53YWNuQU9pc2s5YWM3
            N21Nc2NudEoyVHRnRjN3UlRqQ1JYdWVOcW0wCnNva0MrRDhXVy80VThaZDloWk1v
            bWdMRm9MUVlxaDJGREorZmc5MXM0Z2sKLS0tIHpra0xuTjRJa2pab1VoaWZxTk5Q
            UlRFUlFWR1JsUGFOUEF3MDN0Uzg0cnMK3oekzmVq3k9LImkRuYebp1WBImetrRmn
            aHv4icOI7jr86IRxgSCXgBLLrk0FxNA1YKoJvEt+Jji1UbtLEw95wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T01:28:13Z"
    mac: ENC[AES256_GCM,data:xzjMnhxFa6+ZMBBfZHP46x0nTOpfPTDxVCndgbJ9AJt+zAtpobzizRpxmCI/9RMgT+qBZIUZRBzX69FN8wJVRDJznsQ1br1OlmQ4+1tVjkVvNGzvVjMc0LwqUcjx7SjcEdlTaeZP0+MsOvldI/KSXvbiDAi3SjXF42iAzY5QTrU=,iv:i28NgqqyDlIXj5P53NcaMuJYsZWEkU+mkXV5t2f2CoM=,tag:76gFVq58r2wcTxkXw/HN/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
