---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app renovate-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
  interval: 1h
  path: ./kubernetes/apps/utilities/renovate/operator
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: utilities
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-jobs
spec:
  dependsOn:
    - name: renovate-operator
  interval: 1h
  path: ./kubernetes/apps/utilities/renovate/jobs
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: utilities
  timeout: 5m
  wait: false
