apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: utilities
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:HXtK8GX4ELTyo/QmAnDi/jjEG8KXeh/loH7+AanG+OON97sSnAK9xJJ6s+O7JeX2hWaZ9sR6QrMIaXtq7VSxIzW1Ss2ik3HKe9GA2d7qQuXqhgu9WQc1s5IObcxP,iv:UFFktS5hqMU7MfSsRqpEusmm45/fAAhctUWDkGEkEFE=,tag:AfysfvADBl30KOtGaP078Q==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:rWMH4ywmG+9696m1PslsQT5OkxO0AbgsadaKe7WfnxMTau4jyRddTLcqIPlaZw==,iv:K6XHNKGd/plG07C6+xwQQbsGyy9bnOqHH2MG+YtGYY8=,tag:nXP4txLscdKSrMcoFTInCA==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:52FijgLU9mj6AftU3MdMfzKEw4Fg3NbH+rcVWeh/k1q3efA7cdKA,iv:NlHpfK5ApcPoDXhLSIGq33UPcSkHZwQpJAi30/4O5lo=,tag:pmKwLqtD8UNIN3qJLzMDAw==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:cvN6ndrL6cnkLUILBuHDywreHbIydmBro/Tdum7TqUMp4/H3z5u+Kg==,iv:+TC62bA/bm5Sik1znUU7xGRrfm6s6/kCNlmfybzFl7I=,tag:CcKdnhNx+4hSBfY3gjIOVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNForb082dG1vdERHNU9s
            TGJ6V00xdzIwZW9NRG5laWNnbWdKQVAvejJFClpIYU9EeW00K1ZQMWdaMHZ5Z1ZD
            aStqMjhIT0xvOTByVlBEclozUEtpdW8KLS0tIHM0Nzc3VjJUcnJkM1c1RSt6M2hq
            TU9hNjBiM3JFbWtNZUJmUUl0M0VCejQK1j1oZMBa1MPxWsug8H7YP8d6Jm636fCs
            IczwWSjJYYnU1VXuS5AovlzAfJQzn61ahjBIBCrvRpS6f5XOATuwLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ako2TWtRbnpIaFoxOVRu
            dFhVSmVQcWNFZmpSTCtSN1ovQURqMGhkcjNzCmIxcVBGVlYwQXNVRmxIRVMwbFp4
            RWpnM1UwZFFNUEdyODJYSDVMNklNKzQKLS0tIE1PNWsrWkhIL1ZEcWZScUJIYkV6
            ZVpRYkx1NVhEL2gweHJwdGpqK2tFdmsKRIPxTwafZDAob05BTULCt6SkXK4RJTGx
            4hb/O9fkkqmFBes8creJtx6i8EECCDoq7L63EshdLhv+NXdT8k3SaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T14:28:14Z"
    mac: ENC[AES256_GCM,data:dEk9wp1Os6WP98iB5Ep8IYAYuK1zEbnlStXOJV3R7OeKPxFKmY1l4TDnYt3dLXRgOItfcktctZ+OYnxyOOyTZ4BBMUQxgyD9fXdlyIbu50ykSA1SGe8G9wKp4qw/GtbmN8C8KbyWl0COHPbIRMSgJKlp1pjP7Uh16uwOnIlIffA=,iv:AaovkGRwl/nTJrI51Lc9aN+fEt2rHQv3P5DnpQVb194=,tag:yWI3GcnQRe5po5rzm7cLaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
