apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: utilities
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:WzASF98rSxMeq55F0oZj5HtZByk9voJgfhdSZ/TNWJ2NPL4Y+oIH8EcJjHH3wU8WZYdApi38n07/QwLWPjjQL2J36WBGzDCluZeH/VS7CrwNU6gmA1Dm00TehESe,iv:PcFYfoo9prGBmN45sGtgLVMdhccp84yEV4w7ulEpT7I=,tag:3nkH6vSPvspLQoj9PqHfeg==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:iNdvONN/I21CmhwgzTKytNeth0GFxHD8+gfm0JKlt+2uSAVe6q+IQtxBNb0=,iv:uaMQ/N54xU4TPaXpl1ytoTfs9ujlCqQwoFyOZHNTOeg=,tag:ulOennJETXvIsFnKp08jrA==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:DCP6h5bhQukZrPC9crtVr2iV0oXK785NgOljI/bDIlTxVB1E68U=,iv:p7HucAjINFOETeQYjGTH7x9jwtubAxc1WuAfMTfyhxU=,tag:NXY7rg4l6Xq2dMqkLqZ55g==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:NZrAbPizJXQRaR3O7MIOfORb6h8HQZIAlaAquyFUyKyh41ZLM6C9lw==,iv:BN5yO13l+t11Hfxh4PXxkTreP2txH6kpkCArO790+yA=,tag:52tMsg/Z2/rjIHjn/iH+Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNForb082dG1vdERHNU9s
            TGJ6V00xdzIwZW9NRG5laWNnbWdKQVAvejJFClpIYU9EeW00K1ZQMWdaMHZ5Z1ZD
            aStqMjhIT0xvOTByVlBEclozUEtpdW8KLS0tIHM0Nzc3VjJUcnJkM1c1RSt6M2hq
            TU9hNjBiM3JFbWtNZUJmUUl0M0VCejQK1j1oZMBa1MPxWsug8H7YP8d6Jm636fCs
            IczwWSjJYYnU1VXuS5AovlzAfJQzn61ahjBIBCrvRpS6f5XOATuwLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ako2TWtRbnpIaFoxOVRu
            dFhVSmVQcWNFZmpSTCtSN1ovQURqMGhkcjNzCmIxcVBGVlYwQXNVRmxIRVMwbFp4
            RWpnM1UwZFFNUEdyODJYSDVMNklNKzQKLS0tIE1PNWsrWkhIL1ZEcWZScUJIYkV6
            ZVpRYkx1NVhEL2gweHJwdGpqK2tFdmsKRIPxTwafZDAob05BTULCt6SkXK4RJTGx
            4hb/O9fkkqmFBes8creJtx6i8EECCDoq7L63EshdLhv+NXdT8k3SaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T07:47:30Z"
    mac: ENC[AES256_GCM,data:QZTwzSMRGsign9u9tNCfL7w3Yy3SVFBXd3E57u2a+3/DrfMVTjD1rgovzzMMDVgGVGYZUR2hRHM9YneO1g14xGTAZPeAryOv2UUYcPrGIc3j/sXJV8LwR2NQuc/Vzq82TAci39QkYUWN4kDYbqPWIzkmXxXEHplVdDaR2xotwnI=,iv:X0wetgxSEpwKZiHJw0IkIDSDc+5D+KPLDRHJdfdXLjE=,tag:VXkNWEIPahVC6x1250Y3qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
