apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app navidrome
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      navidrome:
        containers:
          app:
            env:
              ND_DATAFOLDER: /config
              ND_MUSICFOLDER: /music
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.61.2@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      music:
        enabled: true
        path: ${NFS_PATH}/navidrome/media
        server: ${NFS_HOST}
        type: nfs
      slskd:
        globalMounts:
          - path: /media
        path: /media/downloads/slskd/complete
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: *app
          gethomepage.dev/widget.type: navidrome
          gethomepage.dev/widget.url: https://navidrome.${ROOT_DOMAIN}
          gethomepage.dev/widget.user: ${USERNAME}
          gethomepage.dev/widget.salt: "{{ `{{HOMEPAGE_VAR_NAVIDROME_SALT}}` }}"
          gethomepage.dev/widget.token: "{{ `{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}` }}"
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 4533
