apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app navidrome
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      navidrome:
        containers:
          app:
            env:
              ND_DATAFOLDER: /config
              ND_MUSICFOLDER: /music
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.59.0@sha256:4edc8a1de3e042f30b78a478325839f4395177eb8201c27543dccc0eba674f23
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      music:
        enabled: true
        path: ${NFS_PATH}/navidrome/media
        server: ${NFS_HOST}
        type: nfs
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SHORT_ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 4533
