---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ./helmrelease.yaml
  - ./volumes.yaml
labels:
  - pairs:
      app.kubernetes.io/name: postgresql-dev
      app.kubernetes.io/instance: postgresql-dev
