apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app planka
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      planka:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            envFrom:
              - secretRef:
                  name: *app
            image:
              repository: ghcr.io/plankanban/planka
              tag: 2.1.0@sha256:32c919d9e65b0479d1bbf0e4fb8e00fb11403a5234242b9f5fc900e595c2e2ce
            resources:
              requests:
                cpu: 15m
                memory: 145M
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: selfhosted
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        controller: *app
        ports:
          http:
            port: 1337
