apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app planka
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      planka:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-npm:
            image:
              repository: busybox
              tag: 1.37
            command: ["sh", "-c", "npm run db:upgrade"]
        containers:
          app:
            envFrom:
              - secretRef:
                  name: *app
            image:
              repository: ghcr.io/plankanban/planka
              tag: 2.0.0@sha256:f82726333b953bd0d11184fa95a4fe4b068bab0e43e49254cf2963ad91b7c21a
            resources:
              requests:
                cpu: 15m
                memory: 145M
              limits:
                cpu: 15m
                memory: 249M
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: selfhosted
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        controller: *app
        ports:
          http:
            port: 1337
