apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app planka
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      planka:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            envFrom:
              - secretRef:
                  name: *app
            image:
              repository: ghcr.io/plankanban/planka
              tag: 2.1.1@sha256:19b507ae3ab5cb1855c3f6984249e4a4881ed0b912febdfd492139c29bf10f39
            resources:
              requests:
                cpu: 15m
                memory: 145M
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: selfhosted
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Selfhosted
          gethomepage.dev/icon: *app
        hostnames:
          - "{{ .Release.Name }}.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        controller: *app
        ports:
          http:
            port: 1337
