apiVersion: v1
kind: Secret
metadata:
    name: planka
    namespace: selfhosted
stringData:
    BASE_URL: ENC[AES256_GCM,data:xOAq8MKAnQr4hCnE5/WRDT0BXLOCiDRq1g==,iv:ldlKMw+LKoDFP0JTG+rJjtSOeSTVLaLkTf13Ge29GIk=,tag:SYmQHdjkGipt8SxVOCtseA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:uodP8yztOnk7izzi+I5OwtAXFCl6TKhHoTqebSDevrLMGr+D7ynQgYQq6gRPStgVtpzhK8coA4R40SZPonsZCjdVDgTU8mBIZJuUQtebR6joLA==,iv:CkYyiFFWZ9BVHBV1O0tVlKNhKX7Y8ra8DHg9VIBakBo=,tag:EXBuVXa8nvDkCusN48hlJA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:NwA5PWIJyapYaEw0bO2zTMm75QOw3yZevuXOdHjXGxY2lEb7YR2CZ13sT40=,iv:dMBGn9TMQBL9YdVHYHMswVjrPfn/iP43tVx0yLha/xY=,tag:3KMhHpDVz6T9CYqPQQBZCg==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibEFjWGg5TmhSWThXRWhJ
            UFgzVlNEVzhxSElJNkxPUWJLamhkUlBJWEZ3ClYzaE1JSGZiYzVidWhLRTJPajU5
            TGZQRnlYK3JhTFMvblJyYS81eWhtcVEKLS0tIGtqcnZtTmlJejRBeE1aaFcvZlNH
            S1JVYXJ4UUFmRXI3OHlyemhlU0lReTgKgjN2Qu0uZiwVwrN0hS0z/WJIzoYWFenK
            3Ew0jHqw/wXncQ/N3RysOAJ6yY3ZdX2d7DMuG7XaL4HMJSeLMEKasQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab3V2U210OTg4WXZMQW1K
            Wkp2N0FGbUNrVVEzdUk4aVJHRmNvbUkzUlhZCm5RQytvMFpFZmlDSmJOY1VxbWRI
            NkYwbVNSZkhwMUFhQlcvVmRCVEFVVjAKLS0tIFlwR2JqaEo5Q0MyTmZQYVFmcldl
            aFJNOWV3VStta3R0cXpYV2tHYnRBWWcKgouBQBsJoug3C4BRpwmMGi5uIYaskkY2
            5YlZYPq7X09q5y8twkoGmdpAPaU4JOPmEDKCw2O0Rw/RrAFSgycFyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T15:19:05Z"
    mac: ENC[AES256_GCM,data:9w7iOyO2wY7SyzO0KEUkWTpZxmTC+pO5XrtFt2lSb003J2BrIqW3Cwd1kHWFK7K4QGAYkbaRPm8fFT1fpGIlDnLyaJa3KqJ5zzEb22iWdKJjCOf12tibV4p9JpjtAS45b7haglqCZ99X0W0LhQIgq971rEAV9SiFd5AE5jGMtts=,iv:Q3hJsEFz38yZdd9g2eEFI7W3IPrx5UfhsPQmnwpk1ss=,tag:UAKDU3s5C5viBfOLF+Gl+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
