apiVersion: v1
kind: Secret
metadata:
    name: planka
    namespace: selfhosted
stringData:
    BASE_URL: ENC[AES256_GCM,data:9a3hh9rSHN1oQ3m4T7inPIKteCA+RQfPLhcq2Gm9,iv:jqlMLqsa6W49ybwJPuKMqWLpekXbA8OXginUh/dPhLA=,tag:wzJwMY3716XHdtRcFktO3A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:wdSySJr7NUoEcCUxf315mtSorZuY3+j4VhNskwKdUoUdbJ/aX0vBN8BlLeMI1g2Setn0rsOTI9MmaoYW82D8qT8=,iv:wjBJ3FHGO8/wSJVuwh2BBgHLPsbps8XMyne6nJPNIbI=,tag:6Wjl2vENdUv/M11HCjsU1w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:FHNRhTyzf+eT1Za4,iv:0rYfhOG7B8sVrSRGggTy98z5VO6OILv0aXDlsFhxNUc=,tag:v0X6C6S+vP1hVEY/NvSApA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibEFjWGg5TmhSWThXRWhJ
            UFgzVlNEVzhxSElJNkxPUWJLamhkUlBJWEZ3ClYzaE1JSGZiYzVidWhLRTJPajU5
            TGZQRnlYK3JhTFMvblJyYS81eWhtcVEKLS0tIGtqcnZtTmlJejRBeE1aaFcvZlNH
            S1JVYXJ4UUFmRXI3OHlyemhlU0lReTgKgjN2Qu0uZiwVwrN0hS0z/WJIzoYWFenK
            3Ew0jHqw/wXncQ/N3RysOAJ6yY3ZdX2d7DMuG7XaL4HMJSeLMEKasQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab3V2U210OTg4WXZMQW1K
            Wkp2N0FGbUNrVVEzdUk4aVJHRmNvbUkzUlhZCm5RQytvMFpFZmlDSmJOY1VxbWRI
            NkYwbVNSZkhwMUFhQlcvVmRCVEFVVjAKLS0tIFlwR2JqaEo5Q0MyTmZQYVFmcldl
            aFJNOWV3VStta3R0cXpYV2tHYnRBWWcKgouBQBsJoug3C4BRpwmMGi5uIYaskkY2
            5YlZYPq7X09q5y8twkoGmdpAPaU4JOPmEDKCw2O0Rw/RrAFSgycFyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T06:52:34Z"
    mac: ENC[AES256_GCM,data:pQ4FRrDK8iJ/ZqcCr+/B/u0if1loPCptGyLssOanSo5B3kUFQDw+DM0w0kP3lg2nwK0b1TZ0cLWtSOsMSZWHx+i9jQmnCkeyRL9dxZbP5lNxwCPuqqkh5w0gkWX5H3k7GvWbl6x9YjHelCOjBzoltsg+Mx0ReFe+K83v2eN0HzA=,iv:0V3lWFjebsgqVVyG/uj2WwFnfJt+lkQOHuv1o5b6hks=,tag:ESsED02Oa5KPIwhO2VVNSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
