apiVersion: v1
kind: Secret
metadata:
    name: opencloud-secret
    namespace: cloud
type: Opaque
stringData:
    OCIS_JWT_SECRET: ENC[AES256_GCM,data:QXncGpHft4Ba3c1KWkZ+odmzfKxXkkLl1y/JOzpSsIT04JYsVWk5L0wV2UPF1qA50hPmqwRk3oJ4hCt2UIPTNec9c5Ko23VFz+g/0xZQaH9z7rDvCv7Qp/Wakt0+l3LVetlQdKc79rFSVg6oQpwnI0ymjn43qurQZC+BQzjXZ1bf/D/8Y1RqyK+KfO/icNmmLSy4wRjHaX0PXzN6iRJkA0qGN1KALDEubjUL9A==,iv:pAaYRx9m66ofPmq8hRmgE6Ei7VhxPd0e42BFG4jgmLk=,tag:fNxeplckNDpVaUDqtn+upA==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeXE1aTdZejkxVU1iRm1m
            WTFxRjhmUHR4Vjhsdm1XVUpZNHphZk00cWlJCnZJbWx6MGpJVHhtSXRuY2JTSEJP
            cDRZczVhalpNeVRvcWY3c1AvK2pzOVUKLS0tIDdpVFdOWUFZTndiOVNBNVRLMGdH
            NFZoMmZxdC9mKzduTFBOV1ZYSGVlRmMKAraNNHOhZw+LlnB1/oMOzmNYpn19W0yZ
            A9AtpJW8tJ2U5PaXTRRrFuQ7c6TJLuOxv8KHHmuxADczSgZMv1JcrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcnFxcWhURjJRcHdtTGMx
            WmxvWm1QcGFHeHZmanc5d1FKQXZ3bGQySTFNCkkxS2h3ZlZzaUFwVk5kazlJR3JK
            U05xNHhnc0xlS29kTkhLRTNqeDhNZ0kKLS0tIHBNVkI1T2ZiRnQ4WXhZNWZTK3NF
            akxodHM5eVpLOExwRE85ZlhxOGNTMHcKMjUn9pZybTjA+NcTW1wsCPllO9YgjaK2
            dnPgvC6/PGV+tmryvVkzgRSrzDsVt7eHZBcWnk79jphhcP3oRXLdVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T09:13:51Z"
    mac: ENC[AES256_GCM,data:rk9hV92dBc0WHf1KKpAk8bxLcEc2I6lFJ2yJUoeWrsGoRxZ4PU6JOloBdNoOyKyV5w/4Ms7H82mxxVNbO4t8/7SlyXgzifS6lsowpSzIwGmZNKkz/LaWMBJy5ejxN5ey/PuxJLDmtodrsx5tu7WkmuAFVgI3gdQlKKMsaDVAB64=,iv:z+1YFEsRglTLk/HM3v3y/QTfdfb8ovu6QGjQKW4v0F0=,tag:WqWJMQSp3o59nlxU4L8TTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
