apiVersion: v1
kind: Secret
metadata:
    name: opencloud-secret
    namespace: cloud
type: Opaque
stringData:
    NOTIFICATIONS_SMTP_USERNAME: ENC[AES256_GCM,data:pCRuSTTc5voD+WWh+u1HPEK6tbI=,iv:VP8vWUKtNHm4ap7cyqSeRpo9+jPgyE8MM3RQGOsZCGg=,tag:3XJS3AUwo2+Cxe3DsJxRLg==,type:str]
    NOTIFICATIONS_SMTP_PASSWORD: ENC[AES256_GCM,data:PEW1H1LXFGN8F8watIGoIvYEWh7rsGhFjSW8/XfnqushfkhhfaySh272IAQ=,iv:3COvPHipiwICln7i16eLSSabx4GMyGdU7truAAb41XI=,tag:pMavPAsqsniodg4n/fq+oA==,type:str]
    OC_JWT_SECRET: ENC[AES256_GCM,data:elGJFepEGSw68g4KCOP3X8fodFddwBmRZlBvY1/l5vb0lIDuPkgwczCFezXNDEK5rhnJwzI7GQ2NEppBBafUeUrSMEEL11PHHZfabeWJ9yaH8gBqzfu+xyCQ8cgBXMrtJXa7syc6+ADBMAtAnFSbqDhUejVu7vsqSVy4TUHCgFBh0jlkURwSpc4SCxs7Ih/kS/4dBboIUCm9Dpycg5S7Jx1XrD+dBRIH1dmYFw==,iv:0+m4rhtCKMobMKpg0UfJe/6qZDlQj3APZXSvjKVPXTM=,tag:RsYaFFmglBio5AsX+K+KXQ==,type:str]
    #ENC[AES256_GCM,data:Kx8KNdK6qLU/ADO1DkxwVWxgZjxK5xUNQy8I8r4sxIIWHfyNW4X5P7IQ91vXbjs7rli93zl17QsBJ+Fp2Zgn7g0QivwKeg0igFgEVdks5uYk0qR0NYpfjovyDrAStSTVZWwDHHlMrY6nJDIG9ueYE43t1LdF3PfLj15dtdZ97NpYKLZODXH2+1cFfetY6CYo2nAyVSYFUh26CcRCduqHWUxw1undQssoauZsi/8EzjZlJpz+WlYtWa7fvegSonahpA==,iv:Pw/Y2hnzkCBOnQELCOZR0R3AIq6hC4OI1lsIp3wiWYw=,tag:yvZ3KQBxu3ltUCLCCBgaPA==,type:comment]
    #ENC[AES256_GCM,data:hr/ThKtE+8VTh0N7mGzAIwyvUBX7lE5/T5E9aiPWayyjycoF/SPAGfuaBOs5Lj7uBHoVaB9zRbAKhXbc50ofHs241rvfOnpwYYA=,iv:uhYCnF1YUv1dxx6UT82RFI/oFoj7zQJH0bxVpuGPXoE=,tag:+sEh8qANHSNueb1tdvmITg==,type:comment]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeXE1aTdZejkxVU1iRm1m
            WTFxRjhmUHR4Vjhsdm1XVUpZNHphZk00cWlJCnZJbWx6MGpJVHhtSXRuY2JTSEJP
            cDRZczVhalpNeVRvcWY3c1AvK2pzOVUKLS0tIDdpVFdOWUFZTndiOVNBNVRLMGdH
            NFZoMmZxdC9mKzduTFBOV1ZYSGVlRmMKAraNNHOhZw+LlnB1/oMOzmNYpn19W0yZ
            A9AtpJW8tJ2U5PaXTRRrFuQ7c6TJLuOxv8KHHmuxADczSgZMv1JcrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcnFxcWhURjJRcHdtTGMx
            WmxvWm1QcGFHeHZmanc5d1FKQXZ3bGQySTFNCkkxS2h3ZlZzaUFwVk5kazlJR3JK
            U05xNHhnc0xlS29kTkhLRTNqeDhNZ0kKLS0tIHBNVkI1T2ZiRnQ4WXhZNWZTK3NF
            akxodHM5eVpLOExwRE85ZlhxOGNTMHcKMjUn9pZybTjA+NcTW1wsCPllO9YgjaK2
            dnPgvC6/PGV+tmryvVkzgRSrzDsVt7eHZBcWnk79jphhcP3oRXLdVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T12:11:57Z"
    mac: ENC[AES256_GCM,data:VPvf6YJUJkMl861Ol5wr/i3ge0NNEBy0SvpPejZ0qiiitA4F2dHEHDFOKqXJUT9Cu1A9kBwSrLp4xDUAWP0O5Pch2VyLWOtgOX8P3Z17xOkfcEa7Zsrsk/qoc6n9plm2uJQR2E/3xUlxNX84HfTmhw+SrMU0QnYCWZLQ4CioOik=,iv:jZ+Su/h+xtre1Cj+IJDYyNsoyxYVTVk3rIOnifMzJu0=,tag:wNsetHRAXIUBGauzNyNP1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
