apiVersion: v1
kind: Secret
metadata:
    name: bitwarden
    namespace: external-secrets
type: Opaque
stringData:
    organizationID: ENC[AES256_GCM,data:rv7qGy2Pbr3tLx6SYVe+9Hq9tcE63OtwiiwfLMRrV3A8nsSP,iv:wbkVmUEqnFQySy+vLIKdt5bH55jS9WWnM7dHPLhIXsg=,tag:h2au364NTAWEu04N8gma2g==,type:str]
    projectID: ENC[AES256_GCM,data:DGvklI4VV5RaYnvQiGgmdoa1RXZw77x6jZOUy6asL9H9sQD9,iv:VKdnwT6ZKvxn2QDXQeOwRh+NNwT9Cr4BrlweXWKz1mA=,tag:Ots6xMQSl2Gm1S9lLNSQgg==,type:str]
    token: ENC[AES256_GCM,data:s8f9PXOsft7p9I/D4jPiaLWRe5CWfAx8ZuylZmJ5kqXS//2mg00MwdjHEYEdaID0ZJf0QD4Z1w00pgnI6J755+ZK2tpMsXDxp8PDbUmhw4d5IIyUEsvZQpMf6+JOrQ==,iv:lEmUzo10BhrdhI+6xGAMtJpIk34o+fVmNS2quaIMO0I=,tag:ALFEacCog7/Zt52c8L+v9w==,type:str]
sops:
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWlRNOXRuem9ZTFJZZVFr
            MWpIRzRXTUJzMDROengwUVhEcE51STF5OFJ3CjV0YThvbHUzMmg2akdBYURaUFYw
            Vkx1MnAzc0R3d1QxZ3YzNUZjNzhUR0EKLS0tIDlHeldGZFpJZ0kxL28weHp4L3VP
            NWM5UDFXZDVJYkpMR29XTUJGeTJqSmsKl7Gchir37oQlnafIyyRyBTJirlCJqCzI
            HC4nIoZde5m5yJWYydU/tUPpLjv4yT6dBCcXU2qmSFhRb4pIM8zQSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UWpZWEFUZENHR0dQempV
            Ky9abDJEcmxJMlBQMVhDR3pZOUR4SU9BZ0dvCjlRd3lTNHcxK3QzSmNtMUhVclhJ
            alFGY1RnM0ZGMUJUR25Yc1JEb0F0Yk0KLS0tIGwrUDRVSFk2a0lVd2Exb3dvMWxk
            TForajNHVkNIM2ovYVo1RFBSc1dNQVkKVPK7Ljv3g/dIqZcdnYMRKrBvIDHU1hVZ
            7Ozm+m9OP2p4+B6bMQB7EKwuX9rBwcF79bc1+n7ftKZdSV5JxuoQRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T12:08:21Z"
    mac: ENC[AES256_GCM,data:vwumPbvQsQlRmxxOlDRuJa9exMnro1sCTIwBeKkqQPdxg7I5CnWpj+Aph0KWmfX82heXw/5gSglY3DcalX6VUsdNsMOxh63BgK4HGHBFVYFBrl27UiL8KtUVD3VkwyqBozpVSRKArdVGKSv4XU/0htWIIbBzqZkpxQRed1r5uz0=,iv:AovWvJ2qCgeOxdX79HXIYnMSaLdkJ+LYJkHAh8R3rNE=,tag:ZfEefvD3+hu/tcwSvpQVqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
