session:
  remember_me: 1M
  inactivity: 2d
  redis:
    host: ${REDIS_HOST}
    port: 6379
access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
identity_providers:
  oidc:
    cors:
      endpoints:
        ["authorization", "token", "revocation", "introspection", "userinfo"]
      allowed_origins_from_client_redirect_uris: true
    lifespans:
      custom:
        opencloud-web:
          access_token: "2 days"
          refresh_token: "3 days"
    clients:
      - client_id: grafana
        authorization_policy: two_factor
        client_name: Grafana
        client_secret: "${SECRET_GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.${ROOT_DOMAIN}/login/generic_oauth"]
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: "client_secret_basic"
      - client_id: forgejo
        authorization_policy: two_factor
        client_secret: "${SECRET_FORGEJO_OAUTH_CLIENT_SECRET}"
        public: false
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris:
          ["https://forgejo.${ROOT_DOMAIN}/user/oauth2/authelia/callback"]
        userinfo_signed_response_alg: none
      - client_id: forgejo-lithium
        authorization_policy: two_factor
        client_secret: "${SECRET_FORGEJO_LITHIUM_OAUTH_CLIENT_SECRET}"
        public: false
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris:
          [
            "https://forgejo.lithium.${ROOT_DOMAIN}/user/oauth2/authelia/callback",
          ]
        userinfo_signed_response_alg: none
      - client_id: gitea
        authorization_policy: two_factor
        client_name: Gitea Lithium
        client_secret: "${SECRET_GITEA_OAUTH_CLIENT_SECRET}"
        public: false
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris:
          ["https://gitea.${ROOT_DOMAIN}/user/oauth2/authelia/callback"]
        userinfo_signed_response_alg: none
      - client_id: gitea-lithium
        authorization_policy: two_factor
        client_secret: "${SECRET_GITEA_LITHIUM_OAUTH_CLIENT_SECRET}"
        public: false
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris:
          ["https://gitea.lithium.${ROOT_DOMAIN}/user/oauth2/authelia/callback"]
        userinfo_signed_response_alg: none
      - client_id: immich
        authorization_policy: two_factor
        client_name: Immich
        client_secret: "${SECRET_IMMICH_OAUTH_CLIENT_SECRET}"
        public: false
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "email"]
        redirect_uris:
          [
            "https://immich.${ROOT_DOMAIN}/auth/login",
            "https://immich.${ROOT_DOMAIN}/user-settings",
            "app.immich:///oauth-callback",
          ]
        token_endpoint_auth_method: "client_secret_post"
        userinfo_signed_response_alg: none
      - client_id: memos
        authorization_policy: two_factor
        client_name: Memos
        client_secret: "${SECRET_MEMOS_OAUTH_CLIENT_SECRET}"
        public: false
        pre_configured_consent_duration: 1y
        redirect_uris: ["https://memos.${ROOT_DOMAIN}/auth/callback"]
        scopes: ["openid", "profile", "groups", "email"]
        token_endpoint_auth_method: "client_secret_basic"
        userinfo_signed_response_alg: none
      - client_id: nextcloud
        authorization_policy: two_factor
        client_name: Nextcloud
        client_secret: "${SECRET_NEXTCLOUD_OAUTH_CLIENT_SECRET}"
        public: false
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "email", "groups"]
        redirect_uris: ["https://nextcloud.${ROOT_DOMAIN}/apps/oidc_login/oidc"]
        userinfo_signed_response_alg: none
      - client_id: nextcloud-user-backend
        authorization_policy: two_factor
        client_name: Nextcloud-User-Backend
        client_secret: "${SECRET_NEXTCLOUD_USER_BACKEND_CLIENT_SECRET}"
        require_pkce: true
        pkce_challenge_method: "S256"
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_post"
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "email", "groups"]
        redirect_uris: ["https://nextcloud.${ROOT_DOMAIN}/apps/user_oidc/code"]
      - client_id: weave-gitops
        authorization_policy: two_factor
        client_name: Weave GitOps
        client_secret: "${SECRET_WEAVEGITOPS_OAUTH_CLIENT_SECRET}"
        public: false
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "email", "groups", "offline_access"]
        redirect_uris: ["https://weave.${ROOT_DOMAIN}/oauth2/callback"]
        userinfo_signed_response_alg: none
      - client_id: opencloud-web
        authorization_policy: two_factor
        client_name: opencloud web client
        lifespan: "ocis"
        public: true
        pkce_challenge_method: "S256"
        pre_configured_consent_duration: 1y
        require_pkce: true
        redirect_uris:
          - https://opencloud.${ROOT_DOMAIN}/
          - https://opencloud.${ROOT_DOMAIN}/oidc-callback.html
          - https://opencloud.${ROOT_DOMAIN}/oidc-silent-redirect.html
        scopes: ["openid", "offline_access", "groups", "profile", "email"]
        userinfo_signed_response_alg: none
