apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app websurfx
  namespace: selfhosted
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      websurfx:
        containers:
          app:
            image:
              repository: neonmmd/websurfx
              tag: redis
    ingress:
      app:
        annotations:
        className: internal
        enabled: true
        hosts:
          - host: &host websurfx.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config-file:
        globalMounts:
          - path: /etc/xdg/websurfx/config.lua
            readOnly: true
            subPath: config.lua
        name: *app
        type: configMap
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
