apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tuwunel
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      tuwunel:
        containers:
          app:
            env:
            - name: TUWUNEL_SERVER_NAME
              value: ${ROOT_DOMAIN}
            - name: TUWUNEL_WELL_KNOWN__CLIENT
              value: https://tuwunel.${ROOT_DOMAIN}
            - name: TUWUNEL_WELL_KNOWN__SERVER
              value: tuwunel.${ROOT_DOMAIN}:443
            - name: TUWUNEL_DATABASE_PATH
              value: /data/db
            - name: TUWUNEL_ADDRESS
              value: 0.0.0.0
            - name: RUST_LOG
              value: debug
            - name: TUWUNEL_ALLOW_FEDERATION
              value: 'false'
            - name: TUWUNEL_ALLOW_REGISTRATION
              value: 'true'
            - name: TUWUNEL_ALLOW_LEGACY_MEDIA
              value: 'false'
            envFrom:
            - secretRef:
                name: tuwunel-secret
            image:
              repository: ghcr.io/matrix-construct/tuwunel
              tag: v1.4.8@sha256:0e4a55713e5b2bbcae1c9d120395f502fc96bb546c0da589aa87e2c561c6e2f4
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
    podAnnotations:
      configmap.reloader.stakater.com/reload: tuwunel
    route:
      app:
        hostnames: [ "tuwunel.${ROOT_DOMAIN}" ]
        forceRename: *app
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: 8008

      well-known:
        hostnames: [ "${ROOT_DOMAIN}" ]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /.well-known/matrix/
            backendRefs:
              - identifier: app
                port: 8008
    service:
      app:
        ports:
          http:
            port: *port
            protocol: TCP
            targetPort: 8008
