apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tuwunel
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      tuwunel:
        annotations:
          configmap.reloader.stakater.com/reload: "true"
        containers:
          app:
            env:
              - name: RUST_LOG
                value: debug
              - name: TUWUNEL_ADDRESS
                value: 0.0.0.0
              - name: TUWUNEL_ALLOW_FEDERATION
                value: "false"
              - name: TUWUNEL_ALLOW_REGISTRATION
                value: "true"
              - name: TUWUNEL_ALLOW_LEGACY_MEDIA
                value: "false"
              - name: TUWUNEL_DATABASE_PATH
                value: /data/db
              - name: TUWUNEL_PORT
                value: "8080"
              - name: TUWUNEL_SERVER_NAME
                value: ${ROOT_DOMAIN}
              - name: TUWUNEL_WELL_KNOWN__CLIENT
                value: https://tuwunel.${ROOT_DOMAIN}
              - name: TUWUNEL_WELL_KNOWN__SERVER
                value: tuwunel.${ROOT_DOMAIN}:443
            envFrom:
              - secretRef:
                  name: tuwunel-secret
            image:
              repository: ghcr.io/matrix-construct/tuwunel
              tag: v1.8.2@sha256:6f950bb139411a7964781e986321e395e045e4a6a52240a4dda9d23d04075f78
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
    service:
      main:
        ports:
          http:
            port: &port 80
            protocol: TCP
            targetPort: 8080
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: selfhosted
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Selfhosted
          gethomepage.dev/icon: *app
        hostnames: ["matrix.${ROOT_DOMAIN}"]
        forceRename: *app
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: 80
      well-known:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          gatus.home-operations.com/enabled: "false"
        hostnames: ["${ROOT_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /.well-known/matrix/
            backendRefs:
              - identifier: app
                port: 80
