---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: openebs
  values:
    localpv-provisioner:
      localpv:
        enabled: true
        image:
          registry: quay.io/
        basePath: &hostPath /var/mnt/local-hostpath
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: *hostPath
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
    engines:
      local:
        zfs:
          enabled: false
        lvm:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
    alloy:
      enabled: false
    minio:
      enabled: false
