---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app searxng
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      searxng:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2026.4.17-e8299a4c3@sha256:0bbe85fb9bebe413a26c0e385c76309d15c91fdb9dc8a6bf01b35b714d0ece43
            env:
              TZ: ${TIMEZONE}
              SEARXNG_BASE_URL: https://search.${ROOT_DOMAIN}
              SEARXNG_VALKEY_URL: redis://valkey.default.svc.cluster.local:6379
              SEARXNG_URL: https://search.${ROOT_DOMAIN}
            envFrom:
              - secretRef:
                  name: searxng-secret
    persistence:
      config:
        type: configMap
        name: searxng-configmap
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
          - path: /etc/searxng/limiter.toml
            subPath: limiter.toml
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /etc/searxng
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: selfhosted
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: *app
        hostnames:
          - "search.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
