apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: selfhosted
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:UBCSUaiW0nPc+M7EhPlDr6WNXbDmpr24u+6Qbvj77R7QhZ2ggOw/IHLrQToV2NQWfNlFflzM3eA0jbUdV4ksFw==,iv:xVaiJVVLLhstBU2ph5LM/TSvgdsak3sD9KqVtNpgLLs=,tag:5AJtWxyT2cUFx5/chqsImQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibEFjWGg5TmhSWThXRWhJ
            UFgzVlNEVzhxSElJNkxPUWJLamhkUlBJWEZ3ClYzaE1JSGZiYzVidWhLRTJPajU5
            TGZQRnlYK3JhTFMvblJyYS81eWhtcVEKLS0tIGtqcnZtTmlJejRBeE1aaFcvZlNH
            S1JVYXJ4UUFmRXI3OHlyemhlU0lReTgKgjN2Qu0uZiwVwrN0hS0z/WJIzoYWFenK
            3Ew0jHqw/wXncQ/N3RysOAJ6yY3ZdX2d7DMuG7XaL4HMJSeLMEKasQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e74hyawmdpk4xjhu9xd7rshw85jzedkd2mc73nwuw7r5a8yu3uvq2e3u6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab3V2U210OTg4WXZMQW1K
            Wkp2N0FGbUNrVVEzdUk4aVJHRmNvbUkzUlhZCm5RQytvMFpFZmlDSmJOY1VxbWRI
            NkYwbVNSZkhwMUFhQlcvVmRCVEFVVjAKLS0tIFlwR2JqaEo5Q0MyTmZQYVFmcldl
            aFJNOWV3VStta3R0cXpYV2tHYnRBWWcKgouBQBsJoug3C4BRpwmMGi5uIYaskkY2
            5YlZYPq7X09q5y8twkoGmdpAPaU4JOPmEDKCw2O0Rw/RrAFSgycFyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T09:04:44Z"
    mac: ENC[AES256_GCM,data:aLyYsruCZdbtJE8RaRt6YkPLj30guQ/mCjWyNzX6u/EdLKym/JKuffqmlts4t/JENsqjsIvctgPZPTZrQozv9NqMe3I+qscM7TBcgYhA0qATHEL/XWUqrag6Bei/cU2N4vaWl6/CGQkRSdh/A+8IohPuMPPXk+QNzXGCOx6lA7M=,iv:JGacB2Tbh2FfuGXBonLJBmM4IQiy+SYVPIMKOqTuHS4=,tag:4sw/J6fRgQsNYVgv6xhWhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
