---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: pihole-secret
    template:
      data:
        FTLCONF_webserver_api_password: "{{ .PIHOLE_PASSWORD }}"
  dataFrom:
    - extract:
        key: pihole-dns
