---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole
spec:
  chartRef:
    kind: OCIRepository
    name: pihole
  interval: 1h
  values:
    controllers:
      pihole:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          pihole:
            image:
              repository: ghcr.io/pi-hole/pihole
              tag: 2026.05.0@sha256:70a9c11171ded2eee735d88c127996da209284a329d50f5ae59c06b861d401b3
            env:
              TZ: ${TIMEZONE}
              FTLCONF_dns_listeningMode: all
              FTLCONF_dns_upstreams: 9.9.9.9
              # FTLCONF_dns_dnssec: true
              FTLCONF_misc_dnsmasq_lines: "server=/${OLD_DOMAIN}/#;address=/.lithium.${OLD_DOMAIN}/192.168.1.200"
              FTLCONF_webserver_interface_boxed: false
              FTLCONF_webserver_interface_theme: default-darker
              FTLCONF_webserver_port: &pihole-port 80
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
              limits:
                # looking at the query log can spike the memory usage very high
                memory: 512Mi
          unbound:
            image:
              repository: alpinelinux/unbound
              tag: latest@sha256:49c2f9a99e7951220a01786cbf75dae15d9e96dfd669e78eb04fdd7090671767
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${DNS_HOST}
        primary: true
        ports:
          http:
            primary: true
            port: *pihole-port
          dns-udp:
            port: 53
            protocol: UDP
          dns-tcp:
            port: 53
            protocol: TCP
    serviceMonitor:
      app:
        forceRename: "{{ .Release.Name }}"
        service:
          identifier: app
        endpoints:
          - port: prometheus # exporter-port's name
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 1m
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 403"]
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Utilities
          gethomepage.dev/icon: pi-hole
        forceRename: "{{ .Release.Name }}"
        hostnames:
          - "pihole.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *pihole-port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          pihole:
            app:
              - path: /etc/pihole
                subPath: pihole
              - path: /final
                subPath: init
      unbound-config:
        type: configMap
        name: unbound-configmap
        advancedMounts:
          pihole:
            unbound:
              - path: "/etc/unbound/unbound.conf"
                subPath: "unbound.conf"
      root-hints:
        type: configMap
        name: unbound-configmap
        advancedMounts:
          pihole:
            unbound:
              - path: "/var/lib/unbound/root.hints"
                subPath: "root.hints"
